### ISSUE TITLE
Lien Flux RSS et flux tronqué

### ISSUE THREAD

**Issue by quentinus95** [NextINpact/Next#1]
Bonjour !

Le bouton pour les Flux RSS dans le pied de page est désactivé (redirige vers la page d'accueil).

Le lien Wordpress standard https://beta.next.ink/feed donne un flux tronqué.

Prévoyez-vous bien de mettre à disposition un flux complet de la même qualité que celui de l'ancien site (en particulier, la mise en page était bien respectée et lisible) ?

Merci beaucoup

**Comment by dragonis41** [comment]
Bonjour, il est prévu de faire un flux RSS aussi complet que l'ancien site oui !

**Comment by Otiel** [comment]
Et concernant LeBrief : 
* Dispo dans le RSS en global (un article RSS pour tous les articles du Brief du jour) svp !
* Est-ce qu'on pourrait avoir les images des articles (elles ne sont pas présentes dans le flux RSS "Brief global") de la v7 ?

**Comment by arena94** [comment]
Toujours sur les flux rss : https://beta.next.ink/feed/ versus https://www.nextinpact.com/rss/news.xml

petit comparatif du rendu de mon lecteur rss : 

![rss](https://github.com/NextINpact/Next/assets/1025411/6ecfa087-2439-46d9-bdb7-a2fa111464da)

**Comment by arena94** [comment]
Pour information, le contenu des flux n'est pas strictement identique (le #Brief est manquant, le texte est coupé plus tôt dans la version nextinpact.com), l'image ci-dessous est le résultat de deux copies d'écran.
![contenu](https://github.com/NextINpact/Next/assets/1025411/7e8dd36d-aa12-449d-a88b-c495a148ec00)

l'outil utilisé (plugin wordpress) : 
[dashpress.zip](https://github.com/NextINpact/Next/files/13054661/dashpress.zip)

**Comment by dragonis41** [comment]
Oui c'est normal, on n'a pas encore touché au flux RSS de la beta, c'est encore celui par defaut de WordPress, on est en train de dev l'intégration de clés privée comme l'ancien NXI pour permettre aux abonnées d'avoir le flux complet et des images (qui ne sont pas intégrés par défaut) 😊

**Comment by dragonis41** [comment]
Petite note de mise à jour pour ceux qui suivent cette issue :
* Il y a maintenant un flux RSS custom sur `/feed`
* Le flux RSS pour avoir les articles complets pour les personnes abonnées est aussi fonctionnel, il faut juste que nous ajoutions une entrée dans votre profil pour que vous puissiez générer un lien unique pour pouvoir accéder à ce dernier (c'est en cours)
* Il y aura un deuxième flux RSS avec uniquement les Briefs comme l'ancien site et pareil pour avoir le flux complet pour les abonnées

Voili voilou pour la mise à jour, on ajoute ça au changelog aussi :)

**Comment by pipoupoip** [comment]
J'ajoute un commentaire reçu par mail :) 

[Il manque] les différents RSS aussi affinés que sur Next INpact qui en faisaient toute sa différence (https://www.nextinpact.com/p/rss-social) avec notamment les articles en "Accès libre (https://www.nextinpact.com/rss/acces-libre.xml) et "LeBrief" (https://www.nextinpact.com/rss/lebrief.xml).

**Comment by dragonis41** [comment]
@arena94 tu utilises quel agrégateur RSS pour que je puisse tester avant de faire l'annonce de mise en prod ? 
(Même question pour les autres au passage)

**Comment by dragonis41** [comment]
Je l'ai marqué dans #94 mais je vais le remettre ici pour la postérité.

Si vous voulez tester les différents flux :
* `/feed/full?rsskey=xxx`  ->  Flux par défaut avec 1 article par post et un article de brief par post (c'est le même flux que /feed )
* `/feed/nobrief?rsskey=xxx`  ->  Flux avec seulement les articles
* `/feed/briefonly`  ->  Flux avec seulement les articles de brief (un article par post)
* `/feed/condensedbrief?rsskey=xxx`  ->  Flux avec 1 article par post et un Brief par post (tous les articles de brief sont condensés dans un seul post)

Pour générer un token, il suffit d'aller dans votre profil, tout en bas.
Si vous aviez déjà généré un token avant le 6 novembre à 17h, n'hésitez pas à me ping pour que je vous régénère un token avec le nouveau format en attendant qu'on implémente un bouton pour ça

**Comment by M-M-M-M** [comment]
> @arena94 tu utilises quel agrégateur RSS pour que je puisse tester avant de faire l'annonce de mise en prod ? (Même question pour les autres au passage)

The Old Reader

**Comment by typhoe** [comment]
> @arena94 tu utilises quel agrégateur RSS pour que je puisse tester avant de faire l'annonce de mise en prod ? (Même question pour les autres au passage)

FreshRSS (docker container selfhosted) https://hub.docker.com/r/freshrss/freshrss

**Comment by arena94** [comment]
> @arena94 tu utilises quel agrégateur RSS pour que je puisse tester avant de faire l'annonce de mise en prod ? (Même question pour les autres au passage)

J'utilise un développement perso qui utilise les librairies utilisées par wordpress (agrégateur RSS simplepie)

[dashpress.zip](https://github.com/NextINpact/Next/files/13054661/dashpress.zip)

**Comment by Alkarex** [comment]
> tu utilises quel agrégateur RSS pour que je puisse tester avant de faire l'annonce de mise en prod ? (Même question pour les autres au passage)

@dragonis41 Je vous ai envoyé par mail un compte de test [FreshRSS](https://github.com/FreshRSS/FreshRSS), en espérant que cela puisse vous être utile :-)

**Comment by Albirew** [comment]
tinytinyrss (quand en déplacement et au taff) et rssowlnix (à la zonzon, car c'est le seul qui gère les arborescences de plus de 2 niveaux pour ranger les flux)

**Comment by dragonis41** [comment]
Je ferme cette issue maintenant que tout est testé et que tous les liens sont dispos dans le profil :)
Enjoy

**Comment by ldidry** [comment]
La balise `<premium>` dans le flux RSS pose problème à mon tinytinyrss : il la supprime carrément et son contenu avec.

Y aurait-il moyen de la faire sauter ou de la remplacer par une div ?

**Comment by typhoe** [comment]
Hum, merci @ldidry pour la popup, j'avais pas fait gaffe que le lien de la beta marchait plus :-p

Sinon, même soucis, sous FreshRSS, le flux complet (avec ou sans mon token premium) ne semble plus valide et n'est pas pris en compte.
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fnext.ink%2Ffeed%2F

![image](https://github.com/NextINpact/Next/assets/881171/6087745a-382f-427e-8c20-173b6cc20d2a)

**Comment by dragonis41** [comment]
> Hum, merci @ldidry pour la popup, j'avais pas fait gaffe que le lien de la beta marchait plus :-p
> 
> Sinon, même soucis, sous FreshRSS, le flux complet (avec ou sans mon token premium) ne semble plus valide et n'est pas pris en compte. https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fnext.ink%2Ffeed%2F
> 
> ![image](https://user-images.githubusercontent.com/881171/284849517-6087745a-382f-427e-8c20-173b6cc20d2a.png)

Oui a priori il y a eu des changements de dernière minute dont je ne suis pas au courant et qui ont pété le flux RSS que j'avais fais, je suis en train de le fix

**Comment by typhoe** [comment]
Autre remarque:
une fois le token généré, sur la page profil: les liens des flux n'apparaissent pas directement (et le lien générer ne devient pas "copier" comme la dernière fois que je l'avais fait).
J'étais un peu perdu sur le coup.
Un refresh forcé (F5) et ils apparaissent.
Merci et bon courage !

**Comment by dragonis41** [comment]
#140 👀

**Comment by typhoe** [comment]
> #140 👀

lol, qui c'est qui a posté sans faire de recherche... 
Coupable, j'avoue.... Toutes mes excuses à Jeff !
Merci encore ;-)

**Comment by dragonis41** [comment]
J'ai fait pas mal de fix, je vois avec le chef pour mettre en prod dans les minutes qui viennent

**Comment by dragonis41** [comment]
C'est good, n'hésitez pas à rouvrir les issues si vous rencontrez de nouveau un des bugs susmentionnés :)
Bonne lecture à tous

**Comment by ldidry** [comment]
:pray: Merci !

**Comment by informatiqueJ23** [comment]
Bonjour, 
un flux "accès-libre" est-il prévu pour les sens-dent et les pingres ?

**Comment by dragonis41** [comment]
> Bonjour, un flux "accès-libre" est-il prévu pour les sens-dent et les pingres ?

Bonjour, oui c'est prévu comme mentionné dans l'issue #133 
On fix 2/3 trucs pour la mise en prod de lundi prochain et on intègre ce flux juste après !
