### ISSUE TITLE
[BUG] Bouton commentaire non cliquable depuis la page d'accueil

### ISSUE THREAD

**Issue by Dadkill** [NextINpact/Next#10]
Le logo "infobulle" des commentaires est inactif sur la page d'accueil du site. Seul celui en pied d'article nous permet d'ouvrir le menu latéral des commentaires.

Je rencontre le problème aussi bien sur smartphone que sur desktop, sur la dernière version de chrome.

**Comment by pipoupoip** [comment]
Hello 

Ça fait un petit bout de temps que c'est corrigé, je ferme :)
