### ISSUE TITLE
Recherche - résultats en doublons

### ISSUE THREAD

**Issue by AnaelMobilia** [NextINpact/Next#101]
Hello,

Lors d'une recherche, certains articles peuvent apparaître plusieurs fois dans les résultats.

Exemple : https://beta.next.ink/?s=dev
-> L'article [Ubuntu 23.10 devrait supporter officiellement le Raspberry Pi 5](https://beta.next.ink/brief_article/ubuntu-23-10-devrait-supporter-officiellement-raspberry-pi-5/) va apparaître 7 fois au total (page 1 & 2 lors de mon test).
![image](https://github.com/NextINpact/Next/assets/6187125/a9557cfc-d517-4aed-9ba4-53cda9d61305)

A noter que ça peut également être un souci sur l'import de cet article en particulier !

**Comment by dragonis41** [comment]
On a fix le code de migration dans la semaine, on refera une migration propre ce soir pour éliminer tous les vestiges des anciennes migrations !
