### ISSUE TITLE
Auteur - Avatar par défaut non présent sur le serveur

### ISSUE THREAD

**Issue by AnaelMobilia** [NextINpact/Next#102]
Hello,

Certains auteurs n'ont pas d'avatar associé (exemple : Xavier Berne) et cela "casse" le rendu du site.
Lien vers un article : https://beta.next.ink/6822/106989-face-a-justice-ministere-linterieur-refuse-dappliquer-lopen-data-par-defaut/
![image](https://github.com/NextINpact/Next/assets/6187125/36456a8b-0b27-4d1d-9139-32c5e4826867)

Un avatar par défaut est prévu :
```html
<div class="author">
        <img class="lazy error" src="images/default/avatar.png" data-src="images/default/avatar.png" alt="Next Journaliste" data-was-processed="true"><p>Xavier Berne</p>    </div>
```

... mais l'image "images/default/avatar.png" n'existe pas sur le serveur ! ;-)

**Comment by Opwi** [comment]
Hello,

Problème résolu.
Merci de votre retour. 😁
