### ISSUE TITLE
Migration des articles - articles ne possédant pas d'illustration

### ISSUE THREAD

**Issue by AnaelMobilia** [NextINpact/Next#103]
Hello,

Certains articles ne possédaient pas d'image d'illustration sur NXI. Exemple : https://www.nextinpact.com/article/5687/79269-tafta-l-exception-culturelle-exclue-negociations-dapres-bruxelles
![image](https://github.com/NextINpact/Next/assets/6187125/2cdc9a52-ae78-4fe0-a00e-11aa05226ca5)

Lors de la migration sur next, l'image associée à l'article est `https://cdn.next.ink/inpactv7/data-next/images/bd/wide-linked-media/0.jpg` -> l'ID d'image n'étant pas correct, une erreur est retournée.
![image](https://github.com/NextINpact/Next/assets/6187125/b30a3073-204d-4210-9c6c-448e5731a6b2)
```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>data-next/images/bd/wide-linked-media/0.jpg</Key>
<BucketName>inpactv7</BucketName>
<Resource>
/inpactv7/data-next/images/bd/wide-linked-media/0.jpg
</Resource>
<RequestId>179624274ED9749A</RequestId>
<HostId>
dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8
</HostId>
</Error>
```

Propositions :
- Soit pouvoir ne pas mettre d'images sur une actualité sur next (et ne pas afficher le carré d'image en entête)
- Soit mettre une image "par défaut" pour gérer ce cas (typiquement le logo Next)

**Comment by dragonis41** [comment]
Hello, on voit avec Flock pour nous faire une petite illustration par défaut :)

**Comment by Opwi** [comment]
Hello, 

Une image par défaut (merci Flock) vient d'être mise en place 😁
