### ISSUE TITLE
Commentaires - Date de création / modification en minutes la 1ère heure

### ISSUE THREAD

**Issue by AnaelMobilia** [NextINpact/Next#105]
Hello,

Lorsque l'on écrit ou que l'on modifie un commentaire, le timer affiché est formaté à minima en heures :
![image](https://github.com/NextINpact/Next/assets/6187125/0cc2aa4b-4561-47d8-81f2-70e80ea5bd3b)

Lorsque l'on vient juste d'écrire son commentaire, on ne s'attend pas forcément à ce qu'il soit déjà considéré comme ayant 1 heure.
=> Suggestion : afficher un temps en minutes pour la première heure.

Bonne journée,
Anael

**Comment by bansan85** [comment]
En lien avec #88 : quand je regarde des articles vieux de plusieurs mois, l'âge des commentaires n'apporte rien.

![image](https://github.com/NextINpact/Next/assets/9248729/fd4b6186-3ccc-43c3-b083-a7528537df5d)

Je serais plutôt partant pour mettre la date / heure et non pas un âge.

**Comment by dragonis41** [comment]
L'heure des commentaires est bien fix :)
@bansan85 je te laisse créer une issue pour discuter avec le designeur si on passe sur un format date/heure ou bien si on garde le format actuel
