### ISSUE TITLE
Champ de recherche - contenu restant tronqué lorsque le champ à le focus

### ISSUE THREAD

**Issue by AnaelMobilia** [NextINpact/Next#106]
Hello,

Remarque sur le champ de recherche : recherche effectuée "Assises de la féminisation du numérique" [lien](https://beta.next.ink/?s=Assises+de+la+f%C3%A9minisation+du+num%C3%A9rique)

Lorsque le champ de recherche n'est pas sélectionné, le contenu fait la taille du champ (comportement normal)
![image](https://github.com/NextINpact/Next/assets/6187125/7983484f-4f51-4830-932f-24bafa541cf1)

Lorsque le champ de recherche à le focus, il s'agrandit, mais le contenu reste tronqué à l'affichage alors qu'il a la place de s'afficher
![image](https://github.com/NextINpact/Next/assets/6187125/5c6a3042-ae15-4e49-bd49-7b356b1f7743)

Bonne journée,
Anael

**Comment by MosieurClement** [comment]
Merci du retour, on va fixer ça

**Comment by pipoupoip** [comment]
C'est tout à fait fixé maintenant :)
