### ISSUE TITLE
"Web App" ou PWA pour iOS

### ISSUE THREAD

**Issue by iSurcouf** [NextINpact/Next#107]
Bonjour,
La version actuelle de Next se transforme en "application" (Progressive Web App ?) lorsque l'on crée un raccourci sur l'écran d'accueil iOS.
Est-ce prévu à terme sur next.ink ? En tout cas je l'espère, cela permet d'avoir une appli à part entière sans l'encombrement du navigateur (barre d'adresse, boutons.. etc).
A ce jour l'enregistrement sur l'écran d'acceuil iOS ne génère pour next.ink qu'un simple raccourci qui s'ouvre dans Safari (ou le navigateur par défaut).
Merci par avance.

NextINpact sur iOS en version "WebApp"
![nxi_ios](https://github.com/NextINpact/Next/assets/16901395/25690acd-d072-4843-bd86-76d046110321)

Next.ink sur iOS
![nxt_ios](https://github.com/NextINpact/Next/assets/16901395/97bcf4fc-2225-48a4-b7a1-1c42d11472b1)

**Comment by Dadkill** [comment]
J'utilise exclusivement la PWA sur Android également. Sans ça, ça va grandement réduire ma lecture...

**Comment by ThHareau** [comment]
Ça me manque aussi, c'est pratique d'avoir l'application sans avoir besoin de se reconnecter (Firefox Focus vire les cookies dès qu'on ferme l'app). 

Surtout que j'ai l'impression que c'est "juste" un plugin à installer : https://wordpress.org/plugins/pwa/ ou https://wordpress.org/plugins/pwa-for-wp/

**Comment by ThHareau** [comment]
C'est là pour Android :tada:

**Comment by dragonis41** [comment]
Enjoy :)
