### ISSUE TITLE
Brief - Nombre de commentaires affichés

### ISSUE THREAD

**Issue by AnaelMobilia** [NextINpact/Next#108]
Hello,

Lorsque l'on est dans la liste des articles du brief, le nombre de commentaires est affiché à 0 :
![image](https://github.com/NextINpact/Next/assets/6187125/23231784-1c01-4adf-b5a0-9e535a6de68a)
[Lien](https://beta.next.ink/briefs/lebrief-20-ans-de-patch-tuesday-gta-vi-steam-deck-oled-stmicroelectronics-condamnee/)

Lorsque l'on rentre dans l'article du brief, le bon nombre de commentaires est affiché
![image](https://github.com/NextINpact/Next/assets/6187125/5b66e6cd-81e3-43e5-aa1f-d5b70aa62dad)
[Lien](https://beta.next.ink/brief_article/microsoft-fete-20-ans-patch-tuesday/)

**Comment by MosieurClement** [comment]
Problème résolu ;)
