### ISSUE TITLE
Commentaires : quote

### ISSUE THREAD

**Issue by AnaelMobilia** [NextINpact/Next#109]
Hello,

En complément de #73, certaines citations de commentaires ne sont pas encore parsés lors de la migration.

[Exemple](https://beta.next.ink/brief_article/microsoft-fete-20-ans-patch-tuesday/) : commentaire 2114023
![image](https://github.com/NextINpact/Next/assets/6187125/b684386e-0e30-4d80-8397-eec3b6666d70)

**Comment by dragonis41** [comment]
Je ferme cette issue pour continuer sur #73
