### ISSUE TITLE
[Responsive] Ergonomie de la page d'accueil

### ISSUE THREAD

**Issue by villisek** [NextINpact/Next#11]
Hello, 

Tout d'abord bravo pour le travail accompli en si peu de temps!

Je rencontre quelques difficultés sur le site, plus particulièrement sur mobile ou quand le zoom est augmenté sur PC (accessibilité...)
* Lorsque le site passe en design mobile, le scrolling vertical est fonctionnel seulement sur la partie basse de l'écran. 
* Le titre des articles est très (trop) petit comparé à l'image d'illustration. 
* La marge sur l'axe x est trop élevée, ce qui fait qu'on peut scroller horizontalement dans la liste des news. 

Court extrait vidéo illustrant les soucis sur mobile : https://www.youtube.com/watch?v=i9MVYH_UZB4

Le problème du scrolling est encore pire sur PC quand on a besoin d'avoir un zoom élevé, car la zone scrollable peut se retrouver en dehors de l'écran et il est donc impossible de descendre voir les derniers articles. 

Merci 😄

**Comment by MosieurClement** [comment]
Merci pour ton retour 😄. On va travailler sur ça avec notre DA, on vous tiendra au courant de l'évolution

**Comment by villisek** [comment]
Super, merci :-)
----------------------------------------

*De : *MosieurClement ***@***.***>
*À : *NextINpact/Next ***@***.***>
*Cc : *Clément VILLISEK ***@***.***>; Author ***@***.***>
*Date : *18 oct. 2023 12:43:49
*Objet : *Re: [NextINpact/Next] [Responsive] Ergonomie de la page d'accueil (Issue #11)
