### ISSUE TITLE
Commentaires : chiffres en fraction

### ISSUE THREAD

**Issue by AnaelMobilia** [NextINpact/Next#110]
Hello,

Dans les commentaires, les 5/6 sera représenté en fraction 5⁄6.
Exemple : [commentaire 2114034](https://beta.next.ink/brief_article/microsoft-fete-20-ans-patch-tuesday/)
![image](https://github.com/NextINpact/Next/assets/6187125/7fc76a6b-60cc-4f57-aff7-c4e7e8dc86d9)

Cela n'a pas forcément de sens : `Windows 7/8` n'est pas une fraction :-)

**Comment by pipoupoip** [comment]
tout dépend de la barre oblique utilisée ! 
`5/6 ou 5⁄6`
5/6 ou 5⁄6


<img width="320" alt="Capture d’écran 2023-12-26 à 16 48 00" src="https://github.com/NextINpact/Next/assets/66266210/0935b713-d26f-4ea1-87aa-962897a59fa3">
