### ISSUE TITLE
Commentaire : pas d'émoji / smiley

### ISSUE THREAD

**Issue by bansan85** [NextINpact/Next#111]
Tous les smileys sont en dur et non remplacés par des images.

En regardant le code source, je vois que les smileys sont bien des images mais en lazy. C'est probablement ça qui ne fonctionne pas.

https://beta.next.ink/117791/protection-mineurs-en-ligne-questions-actions-et-craintes-avec-ton-crush-secret/

![image](https://github.com/NextINpact/Next/assets/9248729/937755bc-3c6c-47f7-a0f9-9ba7034c701c)

**Comment by AnaelMobilia** [comment]
Hello,

C'est lié à un problème de certificat sur le cdn NXI qui héberge les smileys.
![image](https://github.com/NextINpact/Next/assets/6187125/dceff587-858d-440c-ad1c-0dc956c6299f)

Dans un commentaire d'une actualité, Ferdi a indiqué que le problème ne serait pas traité et sera résolu suite à la migration sur les infras Next/moji.

**Comment by bansan85** [comment]
C'est bon maintenant.
