### ISSUE TITLE
Appel à votre créativité : une nouvelle image pour le brief ?

### ISSUE THREAD

**Issue by arena94** [NextINpact/Next#112]
actuellement 

![lebrief-ded](https://github.com/NextINpact/Next/assets/1025411/6228d198-50dc-4812-a397-334bd1633ede)

rendu 

![Capture d’écran 2023-11-14 à 12 59 34](https://github.com/NextINpact/Next/assets/1025411/028b103a-6b05-4c89-bf55-8d288024c992)

Changement de site, Appel aux créatifs ?

**Comment by pipoupoip** [comment]
Ah ça c'est une prérogative Flock mais on le submerge déjà de boulot. Je ne sais pas où il en est su ce sujet précis :/

**Comment by xavierforestier** [comment]
Ticket à clore : J'adore cette image d'ailleurs

![](https://next.ink/wp-content/uploads/2023/11/Lebrief200280.jpg)

**Comment by pamputt** [comment]
Sujet résolu depuis 2 semaines apparemment
