### ISSUE TITLE
Fonction copier le lien dupliqué

### ISSUE THREAD

**Issue by DuchkPy** [NextINpact/Next#114]
Hello,

En haut à droite des articles, il y a différents bouton, à savoir des `maillons`, `3 points` et une `bulle`.
Je me suis d'abord demandé à quoi servait les maillons. Il n'y a pas d'information contextuelle en passant la souris dessus et en cliquant rien ne se passe... Donc ça ne m'a pas été d'une grande utilisé, puis j'ai testé un coller, et j'ai compris que ça sert à copier le lien de l'article.

Ensuite j'ai cliqué sur les `3 points` et vu en haut de la liste `Copier le lien`.
Quel est l'intérêt de le remettre ici ?

Pour moi, il faudrait des info-bulles, et le supprimer du menu des `3 points`

**Comment by pipoupoip** [comment]
Hello 

On n'est pas encore super au clair sur ce qu'on va faire de cette partie. Pour l'instant on va laisser comme ça, on va voir coment on évolue sur la question

**Comment by pipoupoip** [comment]
Bon c'est décidé, on garde le menu au dessus de l'article :)
On va mettre des tooltips. A suivre dans #29 :)
