### ISSUE TITLE
Bouton `En Continu` sans fonction

### ISSUE THREAD

**Issue by DuchkPy** [NextINpact/Next#115]
Hello,

Quand on est sur une page du brief, le menu de droite ne contient que le contenu du `En Continu`, mais quand on passe la souris dessus elle se transforme en main, comme si il y avait un bouton. Mais au clic rien ne se passe.
![image](https://github.com/NextINpact/Next/assets/36851093/c6cfde5f-eb74-4dce-9269-4d32d9c18bd1)

Aussi, pourquoi ne pas avoir dans ce menu de droite, le `En Continu` + `Le Brief`, tel qu'il est sur un article standard ?

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement 😄
