### ISSUE TITLE
Liste des articles - poids des images d'illustration des articles en version mobile

### ISSUE THREAD

**Issue by AnaelMobilia** [NextINpact/Next#116]
Hello,

Lorsque l'on affiche la liste des articles depuis un téléphone portable, on charge les images d'illustration des articles.

Pour un affichage des titres de 6 articles, on télécharge 6 images :
- Poids entre 0,5 (dessins de Flock) et 2,1 Mo (images d'illustration) chacune
- Résolution de 1280x620 (dessins de Flock) à 5752x2786 (images d'illustration)

Chacune de ces images sera affichée dans la liste des articles en 100px de côté.
Si la connexion mobile n'est pas parfaite, le temps de chargement de la page est long (>50s sur de la 3G correcte), avec des images qui apparaissent au fur et à mesure dans la liste des articles.

Suggestion : générer une version "low quality" des images (par exemple en 250px) et les utiliser pour la liste des articles lorsque le viewport est petit.

Cela permettrait d'optimiser la navigation mobile (et d'économiser de la BP et des connexions côté serveur).

Cordialement,
Anael

**Comment by MosieurClement** [comment]
On a vu ça, on bosse sur un plugin pour resize les image, ça devrait arriver soon ;)
