### ISSUE TITLE
Forme de la souris au survol du nombre de commentaire

### ISSUE THREAD

**Issue by DuchkPy** [NextINpact/Next#117]
Hello,

Sur la page d'accueil, au survol de la bulle et du nombre de commentaire, la souris prend bien la forme d'une main indiquant que c'est un lien : ![image](https://github.com/NextINpact/Next/assets/36851093/cf052383-5aca-4a10-85c5-5be4e54f1be1)

Par contre, une fois dans un article (brief inclus), la forme de la main n'est valide que sur la bulle, mais pas autour ni sur le texte indiquant le nombre de commentaire : ![image](https://github.com/NextINpact/Next/assets/36851093/3988d30f-0f8a-448e-80ae-29264641b4b7)

**Comment by pipoupoip** [comment]
C'est corrigé :)
