### ISSUE TITLE
Utiliser un outil de validation du code HTML

### ISSUE THREAD

**Issue by francois-dorin** [NextINpact/Next#119]
Le code HTML renvoyé présente de nombreuses anomalies. Certaines peu impactante, d'autres beaucoup plus.

Par exemple, sur cet article, via le validateur du W3C : https://validator.w3.org/nu/?doc=https%3A%2F%2Fbeta.next.ink%2F117789%2Fla-cnil-precise-controles-et-fichiers-consultables-par-professionnels-sport%2F

Si le rendu dans un navigateur ne semble pas affecté, les documents non valides présentes plusieurs défaut : 
- les pages non valides sont moins biens prises en compte par le référencement naturel
- des dispositifs comme les lecteurs d'écran peuvent être très perturbées par ces erreurs
- il peut y avoir des différences de rendu selon le navigateur utilisé

Le plus gros problème que j'ai pu voir, à corriger d'urgence, c'est la présence de code HTML en dehors de la balise `<body>`. Le navigateur rajoute alors automatiquement une balise `<body>`, ce qui fait que la balise `<body>` explicitement présente dans le document se trouve être finalement la seconde balise de ce type, alors qu'il ne peut y en avoir qu'une. Cela peut conduire à des comportements assez aléatoire.

A noter aussi que l'usage des balises sémantiques comme main, article, etc... peuvent avoir des contraintes. La présence de plusieurs balises `<main>` dans un document par exemple est à proscrire (en tout cas, sans hidden). On la retrouve pourtant utiliser de nombreuses fois...

**Comment by MosieurClement** [comment]
Yes, on est en train de passer sur les soucis d'html

**Comment by francois-dorin** [comment]
Super. Bon courage ;)
