### ISSUE TITLE
Lien de partage vers mastodon

### ISSUE THREAD

**Issue by azmeuk** [NextINpact/Next#12]
Il y a des chances pour que les utilisateurs de mastodon soient plus représentés dans le public de nextinpact que dans le reste de la population. Pourquoi ne pas mettre un bouton « partager avec mastodon » à côté (voire _avant_) l'icône d'X ?

**Comment by MosieurClement** [comment]
Yes, on va rajouter mastodon 😊

**Comment by Cqoicebordel** [comment]
J'avous que cette icone '𝕏' me pique salement les yeux. Que ce soit dans le menu, OK, mais visible systématiquement :/  
D'autant plus que je comprend pas pourquoi c'est présent en double
![image](https://github.com/NextINpact/Next/assets/2286246/710f74bf-70ef-4e24-9db0-3596f6086a87)

**Comment by pipoupoip** [comment]
C'est fait, vous pouvez partager sur mastodon. 
@Cqoicebordel le menu va changer ne t'en fais pas. 
Je clos l'issue, le manquement principal étant corrigé.

**Comment by Glandos** [comment]
> J'avous que cette icone '𝕏' me pique salement les yeux. Que ce soit dans le menu, OK, mais visible systématiquement :/ D'autant plus que je comprend pas pourquoi c'est présent en double ![image](https://user-images.githubusercontent.com/2286246/276307607-710f74bf-70ef-4e24-9db0-3596f6086a87.png)

Ça ira mieux avec ![logo xorg](https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/X.Org_Logo.svg/431px-X.Org_Logo.svg.png?20090422155800) ?

Désolé de polluer la discussion, ça me démangeait.
