### ISSUE TITLE
Style des balises <pre> et des blocs de code

### ISSUE THREAD

**Issue by ghost** [NextINpact/Next#120]
En HTML, le texte des balises `<pre>` utilise habituellement une police de type `monospace` (à largeur fixe).

Sur le nouveau site, ce n'est pas le cas. La police utilisée est la même que pour le reste de l'article.

Il serait souhaitable de changer la police utilisée pour les balises `<pre>`.

Pour aller plus loin :

Sur l'ancien site, les balises `<pre class="code_redaction">` avaient également une couleur de fond (`background-color`) légèrement différente du reste de l'article, ce qui permettait de bien les démarquer.

Exemple d'article avec des balises `<pre class="code_redaction">` :  
- https://beta.next.ink/117164/mozilla-propose-depot-debian-pour-firefox-nightly-changement-plus-important-quil-ny-parait/
- https://www.nextinpact.com/article/72793/mozilla-propose-depot-debian-pour-firefox-nightly-changement-plus-important-quil-ny-parait

**Comment by MosieurClement** [comment]
Yes merci pour le retour, on va fixer ça ;)

**Comment by pipoupoip** [comment]
Elles sont toutes belles maintenant :)
