### ISSUE TITLE
Ajourd'hui    ... peut-être ou alors demain .... (air célèbre)

### ISSUE THREAD

**Issue by arena94** [NextINpact/Next#121]
![Capture d’écran 2023-11-15 à 18 08 16](https://github.com/NextINpact/Next/assets/1025411/6e03279d-0858-4b39-a856-c35a3f219e06)
![Capture d’écran 2023-11-15 à 18 08 32](https://github.com/NextINpact/Next/assets/1025411/d38f1952-3bde-4cea-b000-f123c6edc077)

**Comment by Glandos** [comment]
Carmen ?

**Comment by arena94** [comment]
> Carmen ?

Sardou (le père)

https://www.youtube.com/watch?v=f317gvBq26Q
