### ISSUE TITLE
Migration - articles manquants

### ISSUE THREAD

**Issue by AnaelMobilia** [NextINpact/Next#122]
Hello,

Certains articles ne sont pas importés lors des migrations de la base de données de nextinpact vers next.

Liste des articles du 13 et 14 novembre sur Next : 
![image](https://github.com/NextINpact/Next/assets/6187125/fab1a230-406c-465f-8a5f-ebcb8e387925)

Liste des articles sur NextInpact :
![image](https://github.com/NextINpact/Next/assets/6187125/46428a2c-7731-4bb3-93e7-c41a0b912e98)

Articles manquants : 
- [Des centaines d'accidents du travail à SpaceX depuis 2014](https://www.nextinpact.com/article/72861/des-centaines-daccidents-travail-a-spacex-depuis-2014) - Article
- [Dernier billet](https://www.nextinpact.com/blog/72864/dernier-billet) - Blog
- [Poing Dev - Round 4](https://www.nextinpact.com/article/72865/poing-dev-round-4) - Article

Ce schéma se répète à d'autres moments (ex : [Le poing dev 3 – Patch Tuesday du Tuesday soir](https://www.nextinpact.com/blog/72815/le-poing-dev-3-the-fight-before-the-fire) le 06/11).

Cordialement,
Anael

**Comment by villisek** [comment]
Et certains articles du Brief (ex. Celui sur Lydia) emmènent vers une page blanche. 

[Edit 10 heures plus tard]
J'ai créé une issue séparée, c'est visiblement un tout autre souci sans lien avec celui-ci. https://github.com/NextINpact/Next/issues/124

**Comment by MosieurClement** [comment]
Yes, on a vu ça, on refera une importation complète bientôt, ça devrait régler tous les problèmes de doublon, article manquant etc

**Comment by pipoupoip** [comment]
Tous ces problèmes sont effectivement dus à des soucis d'importation partielle. Ça sera réglé à l'heure H du jour J. du coup je clos :) 

ou alors on censure des gens 
![Dramatic_Chipmunk](https://github.com/NextINpact/Next/assets/66266210/6c7a02b7-c247-431d-bfbd-d3be4778c032)
