### ISSUE TITLE
Attention, nous allons aluuuuuuunir

### ISSUE THREAD

**Issue by DuchkPy** [NextINpact/Next#123]
Hello,

En fouillant dans les paramètres du compte je suis tombé là-dessus :
![image](https://github.com/NextINpact/Next/assets/36851093/b8ccf021-b85c-422b-98e0-0e90424f0417)

Je crois que vous avez oublié 1 ou 2 `u` à `annulé` 😁

D'ailleurs, je ne sais pas pourquoi il est indiqué que mon abonnement a été annulé, alors que ce n'est pas le cas. Ou sinon, je ne comprends pas ce que ça veut dire.

**Comment by MosieurClement** [comment]
Merci, on va fix la tyyyypo. En ce qui concerne l'abonnement annulé, c'est juste un problème d'affichage, on n'a pas encore importé toutes les informations des abonnements de l'ancienne base, ça devrait arriver vite ;)

**Comment by Albirew** [comment]
j'imagine que "abo annuulé" veux dire qu'il n'est pas renouveelé automatiquement...😬

**Comment by pipoupoip** [comment]
C'est bien ce que ça veut dire et c'est bien comme ça que ça sera formulé pour être plus clair :)
