### ISSUE TITLE
Liens vers certains articles du Brief buggés

### ISSUE THREAD

**Issue by villisek** [NextINpact/Next#124]
Bonjour les devs!

J'ai trouvé un petit problème sur la Bêta de Next : 

Quand on se rend sur la page d'un Brief (lien n°1), les liens dans le titre de l'entrée menant à la page d'une entrée du Brief est cassé et mène vers une page vide (lien n°2). Cependant, si l'on recherche l'entrée individuellement dans le moteur de recherche du site, on obtient le bon lien (lien n°3). Je n'ai pas trouvé le pattern qui produit cette erreur cependant, car c'est assez aléatoire en fonction des entrées du brief : certaines ont un bon lien, d'autres non. 

Merci :-) et bon courage pour la suite !

Liens: 

1. https://beta.next.ink/briefs/lebrief-apple-tap-to-pay-en-france-satellites-et-environnement-double-ration-pour-lydia-obs-studio-30-0/
2. https://beta.next.ink/?post_type=brief_article&p=118166
3. https://beta.next.ink/brief_article/lydia-doublement-epinglee-par-balance-ton-agency/

**Comment by MosieurClement** [comment]
Merci pour le retour, je pense que ça vient d'un probleme de doublon et on du suprimmé l'article lié a ce brief, on va enqueter dessus

**Comment by pipoupoip** [comment]
Je confirme c'est lié à l'importation. Je ferme donc :)
