### ISSUE TITLE
Mise en page des commentaires cassée sous certains articles

### ISSUE THREAD

**Issue by villisek** [NextINpact/Next#125]
Re-bonjour, c'est encore moi... 

J'ai remarqué un problème de mise en page dans les commentaires d'une entrée de Brief, je n'avais pas encore rencontré ce souci avant et je ne vois pas d'issue ouverte à ce propos, donc ...

Voici l'entrée du brief sur laquelle je rencontre le souci : https://beta.next.ink/brief_article/lydia-doublement-epinglee-par-balance-ton-agency/

J'ai testé sur Firefox et Edge sous Windows, avec différentes largeurs d'écran, même souci.

![Capture d’écran 2023-11-17 à 10 05 58](https://github.com/NextINpact/Next/assets/60393058/972c9060-2bf5-4372-bef9-5ae3498ca1a3)
(il n'y a pas de souci avec la navbar, c'est juste la fonction de screenshot de balises de Firefox qui prend en compte la navbar dans la capture)

Merci et good luck!

**Comment by MosieurClement** [comment]
Ah oui effectivement, on ne l'avait pas vu celui-là, on va essayer de régler ça, merci beaucoup :)

**Comment by pipoupoip** [comment]
C'est corrigé :)
