### ISSUE TITLE
Bouton 'Supprimer' la photo de profil cliquable même en l'absence de photo

### ISSUE THREAD

**Issue by xdelatour** [NextINpact/Next#126]
Sur la page du profil, il est possible de cliquer sur le bouton 'Supprimer' même quand il n'y a pas de photo de profil (alors que le pointeur de la souris conserve sa forme de flèche et que le style du bouton ne change pas lors du survol). 

Après validation du message « Êtes-vous sur de vouloir suprimmer votre avatar ? », le message d'erreur « Une erreur est survenue » s'affiche (il y a une faute d'orthographe à « supprimer »).

[EDIT] La faute d'orthographe à « supprimer » est corrigée mais il manque aussi l'accent circonflexe sur « Êtes-vous s**u**r »

**Comment by pipoupoip** [comment]
C'est corrigé :)
