### ISSUE TITLE
Typo dans la partie abonnement du profil

### ISSUE THREAD

**Issue by DocNimbus** [NextINpact/Next#127]
Une erreur typo est venue s’incruster dans la partie abonnement du profil :  Votre abonnement à été an**u**ulé ---> Votre abonnement à été an**n**ulé

![image](https://github.com/NextINpact/Next/assets/12167900/7f8babc2-b01d-4b91-8570-2f6b360cb691)

**Comment by xdelatour** [comment]
Voire même : Votre abonnement **a** été annulé

**Comment by pipoupoip** [comment]
Merci pour votre retour. La formulation va changer :)

**Comment by DuchkPy** [comment]
Voir #123 
Effectivement, je n'avais pas vu le "à"
