### ISSUE TITLE
Typo dans les résultats de recherche

### ISSUE THREAD

**Issue by xdelatour** [NextINpact/Next#128]
Après une recherche, la plus grosse ligne mise en évidence est « Résultat de rechercher ». Et juste dessous il manque l'accent sur « résultats »

Enfin, mais ça n'a rien à voir avec l'orthographe, un article apparaît à trois reprises : 
![next-recherche-800](https://github.com/NextINpact/Next/assets/4384945/1500763d-201b-4d16-9a04-b7284f8784df)

**Comment by pipoupoip** [comment]
Merci pour ton retour. Les typos seront corrigées très bientôt. 
Le triplon est bêtement lié à des soucis d'importation partielle depuis le site historique. Ça ne sera plus le cas à l'heure H du jour J
