### ISSUE TITLE
L'onglet Abonnement affiche aussi le profil (mobile)

### ISSUE THREAD

**Issue by xdelatour** [NextINpact/Next#129]
Sur téléphone portable (testé avec Brave), l'onglet « Abonnement » du profil affiche à la fois le formulaire du profil et, au-dessous, le formulaire d'abonnement.

Pas de bug sur la version ordinateur de bureau, l'onglet « Abonnement » n'affiche que le formulaire d'abonnement.

**Comment by pipoupoip** [comment]
C'est corrigé depuis un bout de temps, ça ^^
