### ISSUE TITLE
[FEAT] navigation clavier

### ISSUE THREAD

**Issue by hezirel** [NextINpact/Next#13]
Salut,

Je pense que ce serait sympa d'avoir la possibilité de naviguer sur le contenu et les commentaires avec des raccourcis clavier vim-like, pour accéder aux commentaires, y répondre, partager l'article, etc ...

Ce serait un gros plus en terme d'ergonomie

**Comment by pipoupoip** [comment]
Hello,

Vu la quantité de travail pour sortir le site, on ne va pas sortir ça tout de suite mais on le garde sous le coude pour la suite éventuellement.

**Comment by hezirem** [comment]
Salut, j'ai ajouté une version basique de la feature pour l'instant, elle permet de se déplacer sur les comments parents en une dimension uniquement pour l'instant.

Mais je rajouterais des features et des moyens de déplacements progressivement pour vous rendre la navigation clavier plus qu'utile.
