### ISSUE TITLE
Next ! soucis connexion / commentaire / redirection / logo ?

### ISSUE THREAD

**Issue by AIMAR-S** [NextINpact/Next#131]
Hello !

Donc le site est live mais quelques soucis :
- j'ai du me log 2 fois
- J'ai commenté le poing [dev 5 ](https://next.ink/48655/le-poing-dev-round-5/#comments) impossible de voir mon commentaire. Y'a **0-1** sur la home et **0** sur la news :(
- pas de redirection https://www.nextinpact.com/ http://www.pcinpact.com/ > https://next.ink
- Logo avec beta dedans encore

Courage !

**Comment by oliverpool** [comment]
> j'ai du me log 2 fois

Pareil.

> pas de redirection https://www.nextinpact.com/ http://www.pcinpact.com/ > https://next.ink/

Selon curl, nextinpact.com est bien redirigé, mais dans le navigateur ça plante à cause du service worker #132

**Comment by pipoupoip** [comment]
- j'ai du me log 2 fois
  - On travaille à la correction de ce bug 
- J'ai commenté le poing [dev 5 ](https://next.ink/48655/le-poing-dev-round-5/#comments)impossible de voir mon commentaire. Y'a 0-1 sur la home et 0 sur la news :(
  - donc le commentaire ne s'est jamais enregistré ?
- pas de redirection https://www.nextinpact.com/ http://www.pcinpact.com/ > https://next.ink/
  - il y en a une mais on a un souci de DNS/proxy sur lequel nous avons mis nos meilleurs agents
- Logo avec beta dedans encore
  - On enlevera bientôt le "beta". Il manque au moins le thème sombre je dirais ;)

**Comment by AIMAR-S** [comment]
>* j'ai du me log 2 fois       
>       * On travaille à la correction de ce bug

Ok 👍 


> * J'ai commenté le poing [dev 5 ](https://next.ink/48655/le-poing-dev-round-5/#comments)impossible de voir mon commentaire. Y'a 0-1 sur la home et 0 sur la news :(
>       * donc le commentaire ne s'est jamais enregistré ?

En fait non, le 1 c'était mon commentaire :D mais il m'a fallut du temps et/ou la réponse de Ferd pour que je puisse le voir ! Donc je n'ai pas le scénario précis du bug mais ça doit être dans ce laps de temps.

> * pas de redirection https://www.nextinpact.com/ http://www.pcinpact.com/ > https://next.ink/     
>       * il y en a une mais on a un souci de DNS/proxy sur lequel nous avons mis nos meilleurs agents

Il me semble que cela marche maintenant 👍 

> * Logo avec beta dedans encore
>       * On enlevera bientôt le "beta". Il manque au moins le thème sombre je dirais ;)

Yep vu dans la réponse de Ferd ! Merci !
