### ISSUE TITLE
Domaine NextINpact HS

### ISSUE THREAD

**Issue by francois-dorin** [NextINpact/Next#132]
Vous êtes surement au courant, mais au cas où, le domaine www.nextinpact.com est inaccessible.

**Comment by oliverpool** [comment]
Plus compliqué : le service worker affiche une page bleue, mais celle-ci n'arrive à rien charger derrière car https://api-v1.nextinpact.com est inaccessible.

Mettre à jour un service worker est galère...

**Comment by francois-dorin** [comment]
J'apporte des précisions, au cas où cela puisse aider.

J'avais testé en navigation privé, et j'avais l'erreur sur la page même de NextINpact. Le service worker ne pouvait même pas se charger.

Mais sinon, effectivement, en navigation "normale" (pas privée donc), page bleu à cause du service worker.

Donc c'est peut être les 2 domaines qui sont HS...

**Comment by Glandos** [comment]
https://next.ink/48655/le-poing-dev-round-5/

La bascule semble avoir été faite.

C'est vrai qu'un petit redirect 301 nextinpact.com -> next.ink, ça serait pas mal :)

**Comment by francois-dorin** [comment]
@Glandos Effectivement. Merci pour l'info !

Sans la redirection, difficile de le savoir :)

**Comment by oliverpool** [comment]
De mon côté, j'ai bien des redirections 301 avec `curl -v https://www.nextinpact.com` :thinking:

**Comment by francois-dorin** [comment]
Je dois avoir un problème de cache DNS. Pour ma part, pour https://www.nextinpact.com/, c'est toujours : 
> Ce site est inaccessible
> Vérifiez si l'adresse www.nextinpact.com est correcte.
> DNS_PROBE_FINISHED_NXDOMAIN

Je retesterai d'ici quelques heures.

**Comment by JohnXLivingston** [comment]
Il y a des problèmes de cache, en effet.
En allant sur https://www.nextinpact.com/, j'obtiens ceci:
![image](https://github.com/NextINpact/Next/assets/38844060/03fa572f-0d21-44b3-ad68-b94821805f5d)

En faisant ctrl+f5, je suis bien redirigé vers le nouveau service.
Mais même après ça, quand je retourne sur https://www.nextinpact.com/, je retombe sur la page à moitié chargée.


PS: bravo aux équipes pour le taf accompli, et faites gaffe à pas vous surmener !

**Comment by JohnXLivingston** [comment]
Une façon de corriger le bug manuellement (pour débloquer la situation pour soi):
* aller sur about:serviceworkers (manip valable sous Firefox, mais j'imagine que chrome a un truc équivalent)
* chercher nextinpact.com
* cliquer sur désinscrire

![image](https://github.com/NextINpact/Next/assets/38844060/478bb13e-701b-422d-ace1-dfd959254a17)

**Comment by dragonis41** [comment]
En principe c'est fix, n'hésitez pas à rouvrir l'issue si vous avez toujours le souci après avoir supprimé le cache
