### ISSUE TITLE
[Flux RSS] Manque le flux RSS Accès Libre

### ISSUE THREAD

**Issue by jbpaux** [NextINpact/Next#133]
Bonjour,

Avant il y avait ce flux RSS de dispo https://www.nextinpact.com/rss/acces-libre.xml mais celui-ci ne semble plus exister dans la nouvelle version.
Se serait possible de le répliquer ?
Merci !

**Comment by dragonis41** [comment]
Hello, il est prévu dans un futur assez proche mais pas pour le moment, on va d'abord s'occuper de fix les bugs liés à la migration :)

**Comment by dragonis41** [comment]
C'est en prod :) 
Vous pouvez y accéder à https://next.ink/feed/free
Je vois pour ajouter le bouton dans le profil
