### ISSUE TITLE
[Logo] Le mettre à jour

### ISSUE THREAD

**Issue by francois-dorin** [NextINpact/Next#134]
Il trône un bêta qui n'a plus vraiment lieu d'être maintenant que la bascule est faite ;)

**Comment by pipoupoip** [comment]
Attendons le thème sombre pour le cacher dans le noir ;)

**Comment by francois-dorin** [comment]
Donc les autres le verrons encore :p

**Comment by pipoupoip** [comment]
TADAAAAAAAAA
