### ISSUE TITLE
Infos abonnement migrées ?

### ISSUE THREAD

**Issue by JohnXLivingston** [NextINpact/Next#135]
Hello,

Sur la nouvelle interface, si je vais voir mon profil, ça m'indique «Vous n'êtes pas encore abonné... C'est triste !».
Alors que normalement je suis encore abonné pour plusieurs mois.

Avez-vous déjà migré les infos d'abonnement ?
Si oui, il y a peut être un bug sur mon compte (John Livingston).

![image](https://github.com/NextINpact/Next/assets/38844060/2140bbda-f9a9-4334-9cf1-37e4e1c5ab7f)

**Comment by Cqoicebordel** [comment]
Pareil pour moi.  
Mais j'ai accès aux articles abonnées, je pense que c'est juste un problème d'interface dans le profile.

**Comment by pipoupoip** [comment]
C'est effectivement juste un problème d'affichage, je confirme :) La date de fin d'abonnement a bien été conservée :)

**Comment by damien-carcel** [comment]
Pareil pour moi aussi, ça me dit "pas d'abonnement" mais j'ai quand même accès à tout.. J'étais prêt à envoyer un mail à l'équipe de dev, mais j'ai réussi à me contrôler pour aller checker les issues ici d'abord :smile:.

**Comment by Opwi** [comment]
Hello,

Problème résolu.
Merci de votre retour.😁
