### ISSUE TITLE
[Feature Request] voir plus facilement les nouveaux commentaires

### ISSUE THREAD

**Issue by eglyn** [NextINpact/Next#137]
Bonjour, 

J'ai du mal à trouver comment faire un truc :) : 
Lorsque je vois sur une news 80(+11) commentaires, je me dis: cool je vais aller lire les 11 nouveaux commentaires.

Je clique sur la bulle, ça m'envoi sur une discussion en plein milieu des commentaires (donc, j'imagine le premier "nouveau"), mais comment ensuite trouver les 10 autres nouveaux ? 

C'est vraiment compliqué de suivre les nouveaux commentaires, et je passe une bonne partie de mon temps sur NXI à les suivre :D 

N'y a-t-il pas un moyen d'afficher tout en chronologie simple ?

**Comment by dragonis41** [comment]
Ce n'est pas vraiment possible avec l'implémentation actuelle.
Pour le moment il y a une pastille de couleur rouge sur les nouveaux commentaires mais il est prévu d'améliorer la navigation vers les nouveaux commentaires dans un futur proche

**Comment by atchisson** [comment]
ça semble pas mal !

![image](https://github.com/NextINpact/Next/assets/41149397/3f1541e1-1309-4672-9a7a-ba850f079122)

**Comment by pipoupoip** [comment]
Hello
Entre le nouveau style et les flèches de navigation, je ferme ce ticket (d'autant qu'il y en a d'autres ouverts pour les petits bugs liés aux commentaires non lus :))
