### ISSUE TITLE
[profil] photo, reset password

### ISSUE THREAD

**Issue by theoldscudo** [NextINpact/Next#138]
hello, 
2 soucis liés au profil que je mets dans le même ticket
1. j'essaie de changer de photo de profil sur next.ink.
quel que soit le jpg, la fenêtre de chargement se ferme, aucun message de confirmation ou d'erreur et l'image n'est pas changée.
2. j'ai fait un reset password ce matin (ni celui de nxi ni celui de la beta ne fonctionnaient...), la fenêtre de saisie du nouveau mdp sur smartphone est très déformée : l'image next avec la prise qu'on branche prend env 60% de la largeur sur la partie droite de l'écran, et la zone de saisie est tassée à gauche avec les champs tronqués, avec firefox / android.
Pourtant en testant sur la vue adaptative (dev tools) depuis le pc l'affichage est bon????

**Comment by Opwi** [comment]
> j'essaie de changer de photo de profil sur next.ink.
quel que soit le jpg, la fenêtre de chargement se ferme, aucun message de confirmation ou d'erreur et l'image n'est pas changée.

Le problème devrait être réglé ! 
Pour la procédure, appuyez sur `Modifier`, sélectionnez votre image puis sur le bouton `Valider`.

> j'ai fait un reset password ce matin (ni celui de nxi ni celui de la beta ne fonctionnaient...)

Si vous pouvez réessayer, et nous donner plus de détails.😁

**Comment by theoldscudo** [comment]
Bonjour, 

Bien noté sur la partie photo de profil.

Pour le reset mot de passe, voici quelques détails 
- android 14
- firefox 120.0.1
- idem avec chrome 116
- écran  324*720 (selon les outils en ligne)

voici une capture de ce que j'ai sur mon tel:

![image](https://github.com/NextINpact/Next/assets/151625404/9fe0164f-c0c2-465e-a838-8017de9b93c3)

**Comment by pipoupoip** [comment]
Depuis la refonte de la page de connexion c'est parfaitement réglé :)
