### ISSUE TITLE
[commentaires] zone de saisie pour les "membres"

### ISSUE THREAD

**Issue by theoldscudo** [NextINpact/Next#139]
Hello
les membres non abonnés n'ayant pas 36mois d'ancienneté n'ont pas le droit de commenter les articles. 
Ok c'est la règle.
Pourtant j'ai la zone de saisie avec le bouton "envoyer", qui est visible mais qui n'envoie rien....
Autant cacher la zone de saisie, non ?

**Comment by pipoupoip** [comment]
C'est tout bon maintenant :)
