### ISSUE TITLE
Profile : Refresh la page après la génération de la clé RSS

### ISSUE THREAD

**Issue by dragonis41** [NextINpact/Next#140]
Quand la clé est générée, la page ne se refresh pas et donc il y a toujours uniquement le bouton "générer" sans les boutons pour copier la clé et les liens

**Comment by Cqoicebordel** [comment]
J'allais remplir un bug parce que je trouvais aucune URL pour les feeds, effectivement.

**Comment by LudovicRousseau** [comment]
Je propose que le bouton "Flux RSS" en bas de page renvoie vers une page qui ne s'occupe QUE du RSS.
J'ai mis du temps à comprendre pourquoi le lien RSS me renvoie vers mon profile et pas vers un flux RSS.
