### ISSUE TITLE
Redirection NextInpact → Next casse les liens.

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/Next#142]
Lorsqu'on clique sur un lien NextInpact, ou qu'on active un onglet avec une page NextInpact, on se retrouve sur la home de Next, perdant l'article.

C'est pas cool pour les liens, et pour mes 150 onglets NXI ouverts…

EDIT : Y compris les liens internes. Genre, dans https://next.ink/676/microsoft-ignite-2023-puces-maison-maia-100-ia-et-cobalt-100-cpu-azure-boost-et-confidential-vm/ y'a deux liens mis en avant qui sont pétés.  
EDIT2 : A noter que ce même article a un problème d'images intégrées aussi. Probablement la même cause.

**Comment by PocketFR** [comment]
Apparemment ce soucis semble corrigé pour la plupart des liens.

Cependant certains liens de l'ancien site finissaient par l'extension .htm renvoient vers la page 404, il faudrait supprimer l'extension de l'url avait de rechercher la correspondance dans la base de donnée.

**Comment by dragonis41** [comment]
> Apparemment ce soucis semble corrigé pour la plupart des liens.
> 
> Cependant certains liens de l'ancien site finissaient par l'extension .htm renvoient vers la page 404, il faudrait supprimer l'extension de l'url avait de rechercher la correspondance dans la base de donnée.

T'as un lien sous la main pour qu'on puisse tester ça ?

**Comment by PocketFR** [comment]
Oui bien sur, voici un lien cité sur [le blog du hollandais volant](https://lehollandaisvolant.net/?d=2019/11/29/18/30/17-resoudre-le-probleme-nan-mais-punir-ceux-qui-le-resolvent) : https://www.nextinpact.com/news/95165-affaire-bluetouff-cour-cassation-consacre-vol-fichiers-informatiques.htm

Si on retire le .htm du lien la redirection fonctionne bien

**Comment by dragonis41** [comment]
Top ! Merci

**Comment by Cqoicebordel** [comment]
Je suis tombé sur des images cassées : 
L'image de tête d'article de https://next.ink/3179/seagate-nous-parle-avenir-son-stockage-hamr-smr-mach-2-dual-actuator-etc/ (https://cdn.next.ink/inpactv7/data-next/images/bd/wide-linked-media/11333.jpg)

Il y a également une image dans cet article, qui pointe vers Inpact Hardware. Vous avez encore la main sur ce nom de domaine ?
https://cdn.inpact-hardware.com/data-prod/image/bd/2106.jpeg

**Comment by Opwi** [comment]
> Oui bien sur, voici un lien cité sur [le blog du hollandais volant](https://lehollandaisvolant.net/?d=2019/11/29/18/30/17-resoudre-le-probleme-nan-mais-punir-ceux-qui-le-resolvent) : https://www.nextinpact.com/news/95165-affaire-bluetouff-cour-cassation-consacre-vol-fichiers-informatiques.htm
> 
> Si on retire le .htm du lien la redirection fonctionne bien

Les liens se terminant par `.htm` fonctionnent maintenant correctement.

**Comment by Opwi** [comment]
> Je suis tombé sur des images cassées : L'image de tête d'article de https://next.ink/3179/seagate-nous-parle-avenir-son-stockage-hamr-smr-mach-2-dual-actuator-etc/ (https://cdn.next.ink/inpactv7/data-next/images/bd/wide-linked-media/11333.jpg)

Malheureusement l'image n'était pas non plus présente sur l'ancien cdn de nextinpact.

**Comment by Opwi** [comment]
> Il y a également une image dans cet article, qui pointe vers Inpact Hardware. Vous avez encore la main sur ce nom de domaine ?
https://cdn.inpact-hardware.com/data-prod/image/bd/2106.jpeg

Problème aussi corrigé!

**Comment by Opwi** [comment]
Merci pour vos retours 😁
