### ISSUE TITLE
[RSS] Problèmes d'images

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/Next#143]
Dans Feeder sur Android, les images d'illustrations des posts ne se chargent pas, ou sont l'icone de Next.ink.

Je soupçonne #142 d'être responsable, mais les images du Brief d'aujourd'hui semblent agir différemment, d'où ce bug séparé.

**Comment by dragonis41** [comment]
Oui c'est le même souci, on a un souci sur la redirection d'un des CDN, on est dessus

**Comment by dragonis41** [comment]
En principe c'est tout bon, j'ai fix la thumbnail dans les articles et mes collègues ont corrigé les CDNs hier ! N'hésite pas à rouvrir l'issue si tu as toujours un problème avec les images !

**Comment by Cqoicebordel** [comment]
Ca a l'air de fonctionner plutôt pas mal, merci !

J'ai encore des soucis avec deux articles dans le flux : les deux parlant de la conf Ignite de Microsoft (articles de lundi). J'ai deux clients qui ont des soucis avec les images d'illustrations (Feeder, Android ; Vivaldi, Linux), alors que les deux images semblent parfaitement atteignables. C'est bizarre, mais probablement de mon côté.

Après quelques tests en plus, il semblerait que Vivaldi n'affiche aucune image d'illustration, mais n'a pas de problèmes avec des images dans le corps des articles. Étrange.

Bref, wait and see, pour voir les nouveaux articles :)

**Comment by ldidry** [comment]
Pour l’article https://next.ink/117390/panneaux-solaires-en-autoconsommation-on-decortique-le-kit-play-de-sunology/, dans mon flux RSS, j’ai les 2 premières images qui se chargent mais j’ai des images (et des liens !) qui pointent vers https://next.dev.petit.ninja/, domaine qui ne répond pas.

**Comment by dragonis41** [comment]
> Pour l’article https://next.ink/117390/panneaux-solaires-en-autoconsommation-on-decortique-le-kit-play-de-sunology/, dans mon flux RSS, j’ai les 2 premières images qui se chargent mais j’ai des images (et des liens !) qui pointent vers https://next.dev.petit.ninja/, domaine qui ne répond pas.

Je vois avec Sébastien si c'est une erreur ou si c'est de notre faute, merci pour l'info !

**Comment by dragonis41** [comment]
Update : C'est lié à la manière dont fonctionne le panel admin, il y a des soucis de conf un peu bizarres, on checkera au cas par cas demain quand toute la team Next sera à moji
J'ouvre une issue en attendant pour que les autres puissent voir le problème
