### ISSUE TITLE
Lien vers un commentaire précis

### ISSUE THREAD

**Issue by francois-dorin** [NextINpact/Next#145]
Je ne retrouve pas la fonctionnalité d'avoir un lien vers un commentaire précis. Cela peut être pratique quand on fait référence à un commentaire d'un autre article ou pour le partage sur les réseaux sociaux.

Là, j'ai fais un rapport de bogue #144 , mais je n'ai pas pu mettre de lien sur le commentaire concerné ;)

**Comment by pipoupoip** [comment]
C'est en ligne :)

**Comment by francois-dorin** [comment]
Alors oui, mais pas tip top fonctionnel. Cf. #278 

Donc si le commentaire pointé par un lien change, c'est même contreproductif :/

Exemple : ce lien https://next.ink/121483/zorin-os-17-toujours-aussi-soignee-la-distribution-affine-ses-performances/#comm-7.3 référence le commentaire 7.3. Commentaire de lexii.

J'ai publié un commentaire sous le 7.1 (qui est un commentaire à moi)

Le commentaire de lexii est devenu le 7.4. Le lien d'avant pointe donc vers le commentaire de max6
