### ISSUE TITLE
Edition d'un message : renommer "répondre" en "modifier"

### ISSUE THREAD

**Issue by francois-dorin** [NextINpact/Next#146]
Lorsqu'on édite un de ses messages, le bouton pour valider le commentaire est "répondre". Ce qui est un peu perturbant au début.

Serait-il possible de le renommer en "valider les modifications", "enregistrer les modifications", "modifier le message" (ou ce que vous souhaitez) mais qui soit plus explicite ?

**Comment by pipoupoip** [comment]
Done :)
