### ISSUE TITLE
Nombre de nouveaux commentaires dans l'agora

### ISSUE THREAD

**Issue by francois-dorin** [NextINpact/Next#147]
Un petit bogue dans la gestion des nouveaux commentaires au niveau de l'Agora.

Une petite image vaut bien un long discours ! (j'ai un nouveau commentaire sur un sujet, mais tous les éléments dans l'Agora affiche 1 + 1 commentaires) 

![nouveau commentaire dans agora](https://github.com/NextINpact/Next/assets/36440144/ca02caf5-06d6-40ca-88fe-10b3147474f1)

**Comment by dragonis41** [comment]
T'es sur quel navigateur ? Je n'ai aucun indicateur de commentaire non lu dans l'agora :sweat_smile:

**Comment by francois-dorin** [comment]
Je suis sous Chrome. Mais il faut qu'il y ait au moins un article avec un article non lu. Tout à l'heure, j'avais des +5 partout par exemple.

**Comment by dragonis41** [comment]
J'ai bien la notif de messages non lus sur l'article en bas mais pas dans l'agora, je vois ça avec mes collègues qui ont codé l'agora pour voir s'ils ont une idée du pourquoi 
![image](https://github.com/NextINpact/Next/assets/19738080/a797edd0-1864-4e9b-8048-d75dbab02191)

**Comment by francois-dorin** [comment]
Ok. A noter aussi le bogue du nombre de commentaires, qui s'affiche comme 164 +1 +1 (cf. ma capture d'écran). On a 2x le nombre de commentaires non lu

**Comment by dragonis41** [comment]
Oui oui j'ai bien noté le souci, je suis toujours en train de chercher comment reproduire le bug ^^

**Comment by francois-dorin** [comment]
Alors, dans un style légèrement différent, là, j'ai un autre comportement, toujours sur l'Agora : j'ai un message non lu pour le Poing Dev 5 dans la liste des derniers articles, mais au niveau de l'Agora, je n'ai aucun commentaire non lu pour ce même article.

**Comment by dragonis41** [comment]
Pour le moment il n'y a plus l'indicateur de commentaires non lus dans l'agora. Je laisse l'issue ouverte le temps de savoir si on laisse comme ça ou si c'est prévu de remettre l'indicateur dans l'agora

**Comment by francois-dorin** [comment]
Pour ma part, je n'ai pas d'avis : je replie l'Agora :D

**Comment by pipoupoip** [comment]
L'indicateur est revenu et parfaitement fonctionnel :)
