### ISSUE TITLE
[a11y] Contraste trop faible sur les liens

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/Next#15]
J'aime beaucoup le principe des liens qui suivent la couleur des thèmes (y compris le logo, c'est chouette !), mais le choix de ces couleurs est pas top : le contraste est souvent **beaucoup** trop faible pour une lecture rapide et efficace.
Voici la liste des couleurs récupérées sur le site et le calcul de contraste effectué par un site random.

### NOK : 
Economie (gris-beige)
https://coolors.co/contrast-checker/c7b7a8-ffffff

Flock (rose barbie)
https://coolors.co/contrast-checker/ff5abd-ffffff

Hardware (rose orange)
https://coolors.co/contrast-checker/ff4569-ffffff

IA et Algo (mauve)
https://coolors.co/contrast-checker/be6aff-ffffff

Internet (cyan)
https://coolors.co/contrast-checker/50c5ea-ffffff

Logiciels (bleu des mers du sud)
https://coolors.co/contrast-checker/11bfaa-ffffff

Réseaux sociaux (bleu)
https://coolors.co/contrast-checker/0075ff-ffffff

Sécurité (jaune)
https://coolors.co/contrast-checker/fbba00-ffffff

Société numérique (vert pastel)
https://coolors.co/contrast-checker/74d676-ffffff

### Bof : 
Next (bleu)
https://coolors.co/contrast-checker/4f62ff-ffffff

Science et espace (violet)
https://coolors.co/contrast-checker/7000ff-ffffff

### OK : 
Droit (marron)
https://coolors.co/contrast-checker/595151-ffffff

Edit : Je rajoute aussi les sous-titre d'articles (gris clair) https://coolors.co/contrast-checker/b0b0b0-ffffff

**Comment by MosieurClement** [comment]
Merci pour ton partage, on prend note de tes remarques, on va essayer d'ajuster au mieux pour améliorer l'accessibilité  😁

**Comment by Opwi** [comment]
Bonjour,

Le problème n'est plus d'actualité avec la version actuelle de notre design.

Merci pour les retours.
