### ISSUE TITLE
Manque de padding dans le champ saisie de commentaire

### ISSUE THREAD

**Issue by Wivik** [NextINpact/Next#152]
Hello,

Un peu de padding à l'intérieur du champ texte serait le bienvenue car la bordure est beaucoup trop serrée. Cela rend la rédaction désagréable.

![image](https://github.com/NextINpact/Next/assets/48727868/36ab8db6-d6b1-46d2-bd2c-eeb960b2394e)

Ici avec `padding: 1rem;`

![image](https://github.com/NextINpact/Next/assets/48727868/d3dae5aa-95c1-4fa3-bbda-55dea8314111)

**Comment by pipoupoip** [comment]
Effectivement c'est plus sympa comme ça :)
