### ISSUE TITLE
Ouverture des nouveaux commentaires dans un nouvel onglet

### ISSUE THREAD

**Issue by Wivik** [NextINpact/Next#155]
Habituellement, je fais un middle click pour ouvrir les nouveaux messages dans un nouvel onglet. Ici le bouton ne réagit pas à ce signal :'(

**Comment by darkweizer** [comment]
Bonjour,

Gros +1 ! Ce n'est plus une balise `a` mais une fonction js via onclick sur une balise `span`. D'où le fait qu'on ne puisse plus l'ouvrir avec un clique de mollette. Et pareil que vous, je navigue presque que comme ça dans les articles ici ☹ 

![image](https://github.com/NextINpact/Next/assets/15857329/58409e76-9f3c-47f4-9e98-f1fba5a2e1b2)

**Comment by Wivik** [comment]
A noter que ce comportement n'est présent que sur les articles principaux. Les bulles du brief sont bien middle-clickable.

**Comment by pamputt** [comment]
Ca ressemble beaucoup au ticket https://github.com/NextINpact/Next/issues/200. Doublon ?

**Comment by darkweizer** [comment]
> Ca ressemble beaucoup au ticket #200. Doublon ?

Oui, le #200 est exactement le même que celui-ci !

**Comment by oliverpool** [comment]
> A noter que ce comportement n'est présent que sur les articles principaux. Les bulles du brief sont bien middle-clickable

Dans la colonne de droite, toute la Brief est un seul lien (le titre et la bulle) qui renvoi vers l'article:
![image](https://github.com/NextINpact/Next/assets/3864879/4b013f04-920e-49ed-ad02-0f1d2e76b6c3)


Sur la page d'[un Brief](https://next.ink/briefs/lebrief-ps5-slim-en-france-valeo-porte-plainte-contre-nvidia-pertes-publicitaires-x-twitter/), le bug est bien aussi présent.

![image](https://github.com/NextINpact/Next/assets/3864879/e741ac3e-02ca-452d-83ca-59e873e24b67)

**Comment by pipoupoip** [comment]
Tous les boutons de commentaires sont alternativement cliquables :)

**Comment by darkweizer** [comment]
> Tous les boutons de commentaires sont alternativement cliquables :)

C'est-à-dire ?! Actuellement, le clic molette ne fonctionne pas sur les icônes de commentaire sur les articles. Ce que demande le ticket

**Comment by pamputt** [comment]
Je viens de tester. Chez moi (Firefox sur ordinateur de bureau), le clic molette pour ouvrir dans un nouvel  onglet fonctionne parfaitement, aussi bien en cliquant sur l'icone que sur le chiffre indiquant le nombre de commentaires.

**Comment by darkweizer** [comment]
Firefox également, ça fonctionne sur le bandeau droit du brief, pas sur le flux central de la homepage, ni sur la page du brief. Voir mon gif. Le clique molette fait apparaitre le défilement et non une nouvelle page (d'ailleurs quand on passe la souris sur les icônes, il n'y a pas l'url qui s'affiche en bas à gauche en prévisualisation). Pas de souci sur le bandeau de droite par contre. Brief comme flux d'actu courant.
![D'art d'art, c'est de l'art](https://github.com/NextINpact/Next/assets/15857329/1e5dadd0-fa0d-4da8-a7d7-85d82c137f0b)

C'est normal, on a toujours un `span` avec un `onclick='goToComments()'` pour les icônes sur le flux central et non un `a`. Là où tout l'article est `a` sur le bandeau droit (et ne redirige pas sur les commentaires, soit disant passant)

Ce ticket devrait être réouvert je pense (à moins qu'il y est une mise en prod non effectuée contenant le correctif)

**Comment by dragonis41** [comment]
Ça marche très bien de mon côté (Chrome et Firefox). À tous ceux pour qui ça ne marche pas : êtes-vous sur Windows par hasard ?

**Comment by oliverpool** [comment]
Sous iOS/Safari, ça ne fonctionne pas.

Sous Linux/Firefox, ça fonctionne mal (les commentaires s'ouvrent dans un nouvel onglet, mais pas en arrière plan, comme les liens standards).

Pourquoi ne pas faire un lien standard `<a href="...#comments>` sur lequel la capture de clic a lieu (si c'est un clic normal, déclencher la logique JS, si c'est un clic du milieu, laisser faire le navigateur) ?

**Comment by darkweizer** [comment]
> Ça marche très bien de mon côté (Chrome et Firefox). À tous ceux pour qui ça ne marche pas : êtes-vous sur Windows par hasard ?

Je confirme. Sur windows 11 Firefox 121.0.1 et windows 10 Chrome 120.0.6099.225.

(je peux tester ce soir sur un Windows 10 Firefox 121.0.1 s'il faut)

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement :smile:
