### ISSUE TITLE
[UI] Ne pas justifier les textes

### ISSUE THREAD

**Issue by druxstr** [NextINpact/Next#16]
Les textes des articles sont justifiés. [Exemple](https://beta.next.ink/115756/un-an-apres-ladoption-du-dsa-les-acteurs-de-la-lutte-contre-la-desinformation-entre-espoir-et-inquietudes/).

C'est considéré comme une [une mauvaise pratique](https://checklists.opquast.com/fr/assurance-qualite-web/les-styles-ne-justifient-pas-le-texte).

EDIT : 

Ce n'est pas une question de préférence personnelle, et ça ne concerne pas juste les personnes dyslexiques.  

Ça fait l'objet d'un [critère WCAG](https://www.w3.org/WAI/WCAG21/Understanding/visual-presentation).

On peut justifier, mais il y [a des précautions à prendre](https://elbuffeto.github.io/100daysofa11y-day42/) qui font que c'est plus simple et plus efficace de ne pas le faire.

**Comment by eglyn** [comment]
Oui, je suis d'accord, même si c'est plus "joli", ou plus carré, ça enlève de la lisibilité je trouve :)

**Comment by AIMAR-S** [comment]
Perso je me considère dyslexique et je suis dev web mais je préfère visuellement quand c'est justifié :) et c'est pas un espacement qui empêche ou m'aide à ne pas inverser les lettres quand je lis :D

Après c'est plus proche de la presse papier qui depuis longtemps a pour habitude de justifie son texte.

Je dirais donc plus que c'est une question de gout et d'esthétique !

**Comment by HystericalHatter** [comment]
Ça pourrait être option à la discretion de l'utilisateur (par défaut en non justifié pour ne pas obligé les personnes dyslexiques à faire manuellement le changement), au même titre que le thème sombre, la densité du texte ou l'affichage optionnel des boutons sociaux comme on l'a sur la v7.

**Comment by MilesTEG1** [comment]
Je rejoins l’avis de @AIMAR-S , un texte non justifié ne m’aide pas à ne pas confondre certains caractères par rapport à un texte justifié.
En revanche la police d’écriture beaucoup plus.

Je pense qu’il faut faire de la justification une option activable (et donc aussi désactivable)  par l’utilisateur.

et voir à ajouter une police plus propice à la lecture des dyslexiques comme andika ou opendyslexic ou encore d’autres.

**Comment by francois-dorin** [comment]
D'avance, mes excuses pour le "pavé", mais il y a beaucoup de chose à dire quant à la justification, et c'est bien plus complexe que "c'est joli" ou "c'est un problème pour les dyslexiques" (je simplifie grandement, mais c'est pour bien me faire comprendre ;) )

Afin d'être parfaitement honnête : je ne suis pas un spécialiste (je ne suis pas typographe), mais je me suis pas mal intéressé au sujet pour des raisons diverses et variées. Je suis plutôt pour l'usage de la justification en général, mais je vais autant que possible faire quelque chose de neutre, d'autant plus que je n'ai pas d'avis précis sur l'usage sur NXI.

### Déjà, la justification, comment ça marche ? ###
La justification consiste à réaliser un alignement à gauche et à droite du texte, de sorte à faire de "jolis paragraphes". Pour atteindre ce double alignement, la technique la plus couramment utilisée est de jouer sur la taille des espaces entre les mots.
La conséquence directe de ceci c'est qu'entre 2 lignes qui se suivent, on peut avoir des espaces entre les mots très différents.

### Quel(s) est(sont) le problème avec la justification ###
Comme on vient de le voir, la justification tend à jouer sur les espaces entre les mots et surtout, à le faire varier d'une ligne à l'autre. Ce changement visuel peut induire un certain inconfort pendant la lecture, inconfort qui va être plus ou moins accentués en fonction de différent critères : 
- côté lecteur, la présence de trouble de la lecture, comme la dyslexie
- côté site internet, le nombre de mots par ligne, qui va principalement dépendre des 3 facteurs suivants : 
  - la police choisie
  - la taille de la police
  - la largeur du texte.

Pour le côté lecteur, je laisserai les spécialistes aborder le sujet, cela sort de mon cadre de compétence.

Pour le coté site internet, approfondissons un peu les choses. Comme nous l'avons vu, la justification joue principalement sur l'espacement entre les mots. Du coup, plus il y a de mots par ligne, moins l'espacement entre les mots varie (c'est presque une lapalissade de le dire, mais disons-le quand même).

Une police monospace, moins condensée, à tendance à diminuer le nombre de mot par ligne, et donc à accentuer les effets indésirables de la justification.

Plus la taille de la police est grande, moins il y a de mots par ligne, et donc idem, plus la taille de la police est grande, plus cela accentue les effets de la justification.

Moins la zone de texte est large, moins il y a de mots par ligne.

### Et les avantages ? ###

L'avantage de la justification, outre le caractère plus joli des paragraphes, c'est une identification visuelle plus rapide de la fin d'un paragraphe par rapport à un texte non justifié. Cela peut aider lors de la lecture, et la où c'est le plus flagrant je trouve, c'est la lecture à voix haute.

### C'est bien beau tout ça, mais quid de la césure ? ###
La [césure](https://fr.wikipedia.org/wiki/C%C3%A9sure) est un élément souvent indissociable de la justification... dans les livres, mais beaucoup rarement présent *en ligne*

Prenez n'importe quel roman, il est fort à parier que vous allez avoir des mots en fin de ligne qui sont coupés, avec le début du mot à la fin de la ligne et la fin du mot au début de la ligne suivante.

L'avantage indéniable de la césure est qu'en coupant les mots, on diminue plus ou moins drastiquement l'espace libre à combler sur la droite de la ligne pour obtenir la justification, et donc l'espace à répartir entre les mots. Super ! Cela diminue donc l'inconfort lié à la taille des espaces qui varie ! Oui mais...

### Les inconvénients de la césures ###
La césure n'est elle-même pas sans inconvénients. Tout d'abord, tout comme la justification seule, elle peut poser des problèmes d'accessibilités, notamment à des personnes ayant des troubles de la lecture.

Ensuite, la césure dans les livres est extrêmement travaillées. Simple sur le principe, sa mise en oeuvre est extrêmement compliquée, avec des règles plus ou moins formelles du style : 
- pas de césures sur 2 lignes d'affilées
- pas de coupure sur certains mots (par exemple, on évitera la présence du préfixe `con-` en fin de ligne ou du suffixue `-que` en début de ligne

Bien évidemment, les exemples ci-dessus sont loin d'être exhaustifs (sinon, cela ne serait pas drôle).

A noter également, mais c'est beaucoup moins vrai aujourd'hui, que la césure posait problème au "début" de la démocratisation d'internet, car les dispositifs d'aide à la lecture ne la reconnaissait pas ou très mal. De ce fait, les lecteurs (=retranscripteur audio) avaient tendance à lire explicitement le trait d'union par exemple (on a à peu près le même problème aujourd'hui avec l'usage du point milieu par exemple, mais c'est un autre sujet). 

### Et si on veut activer la césure sur un site internet ? ###
Alors là, il faut savoir que la césure peut être gérée soit automatiquement, soit manuellement.

La gestion manuelle implique de préciser au navigateur où il peut couper les mots, avec le tag [`<wbr>`](https://developer.mozilla.org/fr/docs/Web/HTML/Element/wbr).
Pour des raisons quasi-évidente de [fastidiosité ](https://www.lalanguefrancaise.com/dictionnaire/definition/fastidiosite)(et oui, nul néologisme, ça existe xD), la gestion manuelle est hors de propos, sauf peut être pour des mots qui ne seraient pas présent dans des dictionnaires (nom propre par ex.)

Reste donc la gestion automatique par les navigateurs. Et là, les choses se compliquent. Car autant ils peuvent gérer la césure, autant c'est à eux de se débrouiller pour savoir comment faire, surtout que les règles de gestion des césures dépend de la langue considérée.

La gestion ne respecte pas pleinement les règles typographiques, et on peut donc se retrouver avec des mots coupés bizarrement, ou deux lignes successives qui contiennent une césure.

Quoi qu'il en soit, si on veut activer la césure sur un site internet, il ne suffit pas d'activer la justification, il faut activer la césure également : 
```css 
.justify {
   text-align: justify;
   hyphens: auto
}
```

### et sur Next alors ? ###
Soyons clair : la justification existe déjà sur la v7. Donc activer la justification n'est pas une rupture. Au contraire, c'est l'arrêté qui est une rupture.

Maintenant, étudions un peu les facteurs qui peuvent influencer la perception de la justification: 
- la police a été changée. On est passé d'une police sans empattements avec empattements (autrement dit, d'un sans sérif à un sérif). Un rapide test chez moi montre que la nouvelle police est légèrement plus compacte que la précédente, donc un effet positif sur le nombre de mots par ligne (= augmentation)
- la zone de texte est plus large. Donc effet positif également
- la taille de la police est beaucoup plus importante sur la nouvelle version (passage de 15 à 20px chez moi) => effet négatif

Je pense que les "effets négatifs" sur le nombre de mots par ligne de l'augmentation de la taille de la police surpasse largement les effets positifs des deux autres modifications, pouvant rendre plus pénible la lecture du texte justifié.

A noter également que les tests que j'ai réalisés sont sur ordinateur avec un écran large. Donc sur mobile, je n'ose imaginer ce que cela peut donner.

### A vous de jouer ###

Maintenant vous avez toutes les billes (ou presque) pour décider. A vous de jouer ;)

**Comment by MilesTEG1** [comment]
Merci pour ces explications @francois-dorin .
Je pense qu'il faudra laisser le choix aux utilisateurs d'activer la justification (avec césure ^^) ou non.

**Comment by guillaume-rico** [comment]
Les articles sont bien "non justifié" mais il reste des pages ou ce n'est pas le cas : 

https://beta.next.ink/charte-ethique-et-deontologique-de-next-ink/

https://beta.next.ink/regles-de-la-communaute/

**Comment by AIMAR-S** [comment]
Juste pour remercier @francois-dorin pour son long et très très intéressant commentaire !

**Comment by Alexandre-Gliganic** [comment]
Merci pour vos retours ! Le choix a été fait de justifier le texte pour le moment.
