### ISSUE TITLE
API JSON - Smileys unicode dans les commentaires

### ISSUE THREAD

**Issue by AnaelMobilia** [NextINpact/Next#160]
Hello,

Dans l'API JSON, les smileys sont représentés sous forme de caractère unicode et non plus sous leur forme ":name:".
[Lien d'exemple](https://next.ink/wp-json/wp/v2/comments?post=3616).
![image](https://github.com/NextINpact/Next/assets/6187125/f738a065-682c-4eee-bbf5-820ddc851147)

Sur le site, les smileys sont toujours rendus vers leur image sur le cdn2.nextinpact.com
[Lien d'exemple](https://next.ink/3616/ion-500650-watts-fractal-design-devoile-ses-alimentations-sfx-l-modulaires-et-semi-passives/#comment-73657)
![image](https://github.com/NextINpact/Next/assets/6187125/9fe13085-5d64-4a1f-acd9-8932de7f0dc2)

Bonne journée,
Anael

**Comment by pipoupoip** [comment]
Pour le coup, ça ne m'étonne pas plus que ça, mr green peut être invoqué via `:mr_green:` ou `:D` 
Là ça doit être un `:D`
