### ISSUE TITLE
Abonnement - date de fin d'abonnement en ISO8601

### ISSUE THREAD

**Issue by AnaelMobilia** [NextINpact/Next#161]
Hello,

La date de fin d'abonnement est en format ISO8601 : ```Abonné jusqu'au 2024-06-15T03:58:06.4726897Z```

Suggestion : pour améliorer la lisibilité, la format sur un format plus "user-friendly" :)

Bonne journée,
Anael

**Comment by pipoupoip** [comment]
Oui c'est corrigé ;)
