### ISSUE TITLE
Abonnement - date de fin non prise en compte (pour les voucher ?)

### ISSUE THREAD

**Issue by AnaelMobilia** [NextINpact/Next#162]
Hello,

Lorsque je me suis connecté sur mon compte, il était indiqué que je n'étais pas abonné.

J'ai ouvert la page de souscription à 8€ par mois (affichage du formulaire de paiement), puis suis revenu dans mon compte (retour arrière dans le navigateur, sans avoir touché à la page).

A ce moment là, ma date de fin d'abonnement actuelle est apparue.

A noter que je suis encore sur un voucher d'abonnement lié au magazine.

Idée : regarder s'il n'y aurait pas un cache non mis à jour pour les voucher ?

Bonne journée,
Anael

**Comment by hezirem** [comment]
Salut, Effectivement dans la logique d'affichage il y avait un léger tweak a faire.

On fait une petite maintenance mais je push un changement express, une ligne de code et l'affichage sera bon pour tous les membres qui ont pris un abonnement annuel avant la migration, ET les vouchers.

Désolé du désordre, on a eu pleins d'incendies a gérer dans le process de migration, mais on fait ça avec amour.
