### ISSUE TITLE
Profil - instance Mastodon - input affichant l'ancienne valeur lors de la modification

### ISSUE THREAD

**Issue by AnaelMobilia** [NextINpact/Next#164]
Hello,

Lorsque que l'on ajoute ou modifie une instance Mastodon sur son profil et que l'on enregistre, une pop-up de confirmation apparaît.

Si on clique à nouveau sur le bouton modifier, l'input qui apparaît contient encore l'ancienne valeur.

Si on recharge la page, l'input contiendra la bonne valeur. 

Suggestion : mettre à jour la valeur dans le input de la page au retour de l'appel ajax à admin-ajax.php .

Cordialement,
Anael

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement :smile:
