### ISSUE TITLE
Déontologie et règles - pages pétées sur mobile

### ISSUE THREAD

**Issue by Dadkill** [NextINpact/Next#165]
Comme on dit qu'une image vaut mille mots...

![Screenshot_2023-11-22-01-37-33-48_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/NextINpact/Next/assets/22544947/b716ac3c-aed0-4589-b42c-b2e467f8c645)
![Screenshot_2023-11-22-01-37-58-73_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/NextINpact/Next/assets/22544947/f697530d-e912-4a3e-9aef-14c0758f75d8)

Comme vous pouvez le constater, ni les titres, ni l'affichage n'est correct. Je précise également que la page n'est pas zoomée de mon côté.

Au départ, et après deux semaines de procrastination, je voulais simplement signaler l'erreur CSS de la flèche bleue devant les titres, ainsi que la liste des cookies, qui n'étaient pas du tout bien placées sur mobile, mais je constate que depuis la migration, le problème est plus important.

**Comment by pipoupoip** [comment]
Il ne reste plus que le chevron bleu :) 
On s'y met bientôt

**Comment by Dadkill** [comment]
Il y a également les backslash avant les apostrophes qui sont visibles sur la page "Déontologie".

Ensuite, pour les cookies, ils sont à présent centré, mais se trouvent sur une seule ligne, sans espacement entre le paragraphe précédent et suivant (au point que j'ai eu beaucoup de mal à les retrouver pour prendre un sceen) :

![Screenshot_2023-12-01-09-38-03-78_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/NextINpact/Next/assets/22544947/9bd77002-bcd2-4d39-b724-ed30104ae75d)

Pareil pour le titre : c'est toujours le "nom" de la page, en minuscule avec des traits d'union :

![Screenshot_2023-12-01-09-37-13-42_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/NextINpact/Next/assets/22544947/e71c5399-15db-4ab2-ad98-64a3cbe73cca)

Mais oui, il y a déjà vraiment du mieux, merci beaucoup :) !

**Comment by Dadkill** [comment]
Pour info, les problèmes sont toujours présents

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement 😄
