### ISSUE TITLE
[RSS] Favicon est celle de Wordpress

### ISSUE THREAD

**Issue by maftieu** [NextINpact/Next#166]
La favicon des flux RSS est celle par défaut de Wordpress
![image](https://github.com/NextINpact/Next/assets/6186483/c0e78396-a155-458a-add8-d89ae39b4718)

**Comment by Glandos** [comment]
Dupliqué de #17

**Comment by PocketFR** [comment]
Le problème est que l'appel à https://next.ink/favicon.ico renvoie vers https://next.ink/wp-includes/images/w-logo-blue-white-bg.png au lieu de https://next.ink/wp-content/themes/wordpress-theme/asset/media/favicon.ico
