### ISSUE TITLE
Footer par défaut dans le flux rss

### ISSUE THREAD

**Issue by X-dark** [NextINpact/Next#167]
Le footer de tous les articles est celui par défaut de Wordpress (en anglais) sur le flux RSS.

Exemple:

> The post [Microsoft publie son modèle de langage Orca 2 en open source](https://next.ink/brief_article/microsoft-publie-son-modele-de-langage-orca-2-en-open-source/) appeared first on [Next](https://next.ink/).

**Comment by dragonis41** [comment]
Dupliqué de #1 
Je viens de trouver l'origine du problème, c'est l'extension Yoast qui a mal été reconfiguré
