### ISSUE TITLE
[Bug] Zoom dans le navigateur change l'URL du site

### ISSUE THREAD

**Issue by Meneldor** [NextINpact/Next#168]
Lorsque je suis sur la page d'accueil du site et que je fais un zoom (CTRL + molette) sur firefox pc un filtre s'ajoute automatiquement dans l'URL.
Je passe de https://next.ink à https://next.ink/?begin=2023-11-15&end=2023-11-22
Je ne comprenais pas pourquoi suite au changement de zoom, je perds les articles du jour.

Une fois zoomé, je peu supprimer le filtre dans l'URL et tout va bien, faut juste éviter de changer le niveau de zoom à nouveau, sinon retour du filtre.
Sur une autre page du site, pas de soucis.

**Comment by dragonis41** [comment]
Bug présent également sur Chrome

**Comment by aurelien-reeves-scalingo** [comment]
Sur mobile c'est très fréquent. Je dois corriger l'URL à la main à chaque session de navigation sur Next

Pas d'histoire de zoom. Juste de navigation (click sur le lien "Next", ou retour à la page précédente par exemple)

Je pense que l'issue suivante est la même : https://github.com/NextINpact/Next/issues/187

**Comment by Underground78** [comment]
J'ai le même problème, je n'avais pas réalisé que c'était lié au zoom mais c'est probablement ça. Sinon c'est qu'il y a une autre condition qui déclenche l'ajout du filtre, initialement j'avais plutôt pensé à un raccourci clavier.

**Comment by pipoupoip** [comment]
C'est réparé 👍

**Comment by Underground78** [comment]
Est-ce qu'il y avait d'autres conditions que le zoom qui faisaient
apparaître ce bogue ? Je suis maintenant relativement sûr que le problème
apparaissait aussi sans zoom puisque j'ai retrouvé un onglet ouvert sur
Next avec le filtre alors qu'il n'avait pas été utilisé pendant une longue
période.

**Comment by pipoupoip** [comment]
Oui ce n'était pas la seule condition de déclenchement. 
Cependant le problème n'était pas tant le fait que l'url change que le fait que ses paramètres fussent mal géré
