### ISSUE TITLE
La mise en page sur mobile est parfois cassée

### ISSUE THREAD

**Issue by Dadkill** [NextINpact/Next#169]
Aujourd'hui, le seul article concerné est celui-ci : https://next.ink/brief_article/firefox-120-peut-copier-les-liens-sans-traqueurs/

![Screenshot_2023-11-22-11-44-58-09_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/NextINpact/Next/assets/22544947/2e4a318f-0558-4733-a362-25b1d51da9e7)

Toute la page est décalée à cause de certains commentaires
![Screenshot_2023-11-22-11-46-39-31_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/NextINpact/Next/assets/22544947/344a9cb8-7187-470b-9667-13b92c62b907)

**Comment by Dadkill** [comment]
J'ajoute que le problème se rencontre également avec l'intégration des vidéos. Voici à quoi ressemble la page du Brief du vendredi 24 novembre à cause de l'article suivant : https://next.ink/brief_article/ariane-6-reussi-son-essai-a-feu-long-le-replay-en-bonus/

![Screenshot_2023-11-24-07-44-39-02_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/NextINpact/Next/assets/22544947/32822018-ec0d-48d5-b992-35a5a578c49d)

**Comment by pipoupoip** [comment]
Plus rien ne dépasse ;)

**Comment by Dadkill** [comment]
> Plus rien ne dépasse ;)

C'est vrai pour les commentaires, pas pour l'intégration de la vidéo sur l'article donné en exemple :/

**Comment by pipoupoip** [comment]
Ah mais oui, idiot de moi, j'ai vérifié sur mobile pour les commentaires mais pas pour l'intégration des vidéos :/

**Comment by Dadkill** [comment]
Juste pour documenter l'issue, le problème ne concerne pas que des anciens articles puisqu'il s'est encore produit aujourd'hui avec cette brève : https://next.ink/brief_article/iter-by-drone-une-video-du-reacteur-a-fusion-nucleaire/

**Comment by Dadkill** [comment]
J'alimente également cette issue avec un autre problème lié aux URL longues sur mobile comme on peut le constater sur cette brève : https://next.ink/brief_article/30-ans-de-lespace-economique-europeen/

![IMG_20240102_232143](https://github.com/NextINpact/Next/assets/22544947/f871459e-2c96-4822-b475-2e180fd2b14d)

**Comment by Dadkill** [comment]
![IMG_20240102_232143](https://github.com/NextINpact/Next/assets/22544947/f871459e-2c96-4822-b475-2e180fd2b14d)

**Comment by pipoupoip** [comment]
C'est bon, 
- les images en commentaires
- les iframes dans les articles
- les liens et mots trop longs
ne débordent plus :)
