### ISSUE TITLE
favicon  RSS

### ISSUE THREAD

**Issue by arena94** [NextINpact/Next#17]
le (la ?) favicon ressemble beaucoup à https://www.nextplz.fr/ ou bien x.com

alors je me suis senti inspiré pour le logo ...

![logo](https://github.com/NextINpact/Next/assets/1025411/2dd2d78f-df68-4b3a-a990-b58e85ec9f4a)

et favicon

![fav](https://github.com/NextINpact/Next/assets/1025411/7d224fce-3a66-4dca-9837-39c130ebf22e)

**Comment by arena94** [comment]
Sinon, leet à la rescousse :

 
![n3 t](https://github.com/NextINpact/Next/assets/1025411/a13f054a-fa46-43a3-bf90-90c6abf399d1)

**Comment by pipoupoip** [comment]
Continuez :)

**Comment by arena94** [comment]
variation sur thème

![variation sur thème](https://github.com/NextINpact/Next/assets/1025411/ec7db11d-ff82-4ab3-b7ef-9595762054db)

**Comment by arena94** [comment]
> Sinon, leet à la rescousse :
> 
> ![n3 t](https://user-images.githubusercontent.com/1025411/276349394-a13f054a-fa46-43a3-bf90-90c6abf399d1.png)

J'aime bien le <3 inversé (petit coeur)

**Comment by arena94** [comment]
Sur le tld ... Si next.ink perdure ...

![INK](https://github.com/NextINpact/Next/assets/1025411/a7020ccd-1022-4545-b0fb-0033cade22a3)

next.news est pris 
![Capture d’écran 2023-10-20 à 16 01 30](https://github.com/NextINpact/Next/assets/1025411/ae859eb5-631e-47b0-90b5-c2040d50070b)

**Comment by arena94** [comment]
Bien la dernière version de la favicon, encore un petit effort ... ;-)

Le petit fond grisé devrait être blanc

![favicon2](https://github.com/NextINpact/Next/assets/1025411/7255c65f-1b37-4aea-91a5-77247df1232d)

next step : une favicon spécifique pour le thème sombre  ?

**Comment by arena94** [comment]
onglets chrome ... (favicon wordpress)

le souci du détail !

![onglets chrome](https://github.com/NextINpact/Next/assets/1025411/fa3fc593-a39f-4ae2-95df-621eff7e9438)

**Comment by MosieurClement** [comment]
> onglets chrome ... (favicon wordpress)
> 
> le souci du détail !
> 
> ![onglets chrome](https://user-images.githubusercontent.com/1025411/283180856-fa3fc593-a39f-4ae2-95df-621eff7e9438.png)

je remonte l'info :)
