### ISSUE TITLE
Encart "Tiens, en parlant de ça" à la fin de chaque article

### ISSUE THREAD

**Issue by drissoun** [NextINpact/Next#172]
A la fin de chaque article, il ya un encart "Tiens, en parlant de ça :" proposant divers autres articles plus ou moins liés a ce que l'on vient de lire. 
Sur desktop, l'encart prend 60% de la hauteur de mon écran 2K à 100% de zoom. 
![EnParlantDeCa](https://github.com/NextINpact/Next/assets/61295484/a257372b-4f5c-4d98-896e-9526f2973dab)
Sur mobile c'est un peu moins, mais la photo de profil du journaliste et les liens de réseau sociaux font que sur un écran de 2400px de haut, on ne peut pas voir les commentaires sous l'article sans scroller de 100vh. 
![EnParlantDeCa_Mobile](https://github.com/NextINpact/Next/assets/61295484/593d1c34-20e4-4277-be64-5b3c42994811)

Je propose de soit : 

- Déplacer l'encart après les commentaires 
- le regrouper avec l'encart en continu, pour faire un mix derniers articles / articles liés
- réduire très largement la taille des vignètes et de la photo de profil du journaliste

**Comment by eglyn** [comment]
Je plussoie pour que les commentaires soient avant cet encart :)

Je trouve qu'il y a globalement trop de spam de "regarde ici c'est trop bien" ou "et la aussi y a plein de trucs regarde!" entre le bandeau d'en haut et celui d'en bas.
Ca commence à trop ressembler aux sites de news que je fuis pour l'accès illogique à l'information basée sur des critères qui reposent sur tout sauf sur la chronologie.

Ou alors donner la possibilité de les masquer.

**Comment by pipoupoip** [comment]
L'encart est destiné à bouger pour ne plus repousser les commentaires trop bas.

**Comment by pipoupoip** [comment]
En attendant de bouger définitivement cet encart, nous avons réduit l'encart de deux à une rangée.
Je ferme l'issue étant donné qu'on a mis en place un palliatif :) et parce qu'on a des stats à atteindre quand même (c'est faux)
