### ISSUE TITLE
Navigation dans les commentaires

### ISSUE THREAD

**Issue by francois-dorin** [NextINpact/Next#174]
Pouvoir naviguer facilement d'un commentaire à l'autre est vraiment un plus très agréable à l'usage.

J'ai proposé une fonctionnalité basique pour le faire via l'extension que je développe, mais je pense que cela serait vraiment super que cela soit intégré directement dans le site.

Le code de mon extension est dispo ici : https://github.com/francois-dorin/previnpact-extension/

Et si besoin, je peux fournir une petite aide par rapport à l'implémentation que j'ai réalisé (c'est du JS, et tout est dans le fichier https://github.com/francois-dorin/previnpact-extension/blob/master/modules/content_script/custom-theme.ts

Du 100% fait maison, et licence MIT (donc réutilisable). 

Je mettrai sans doute un peu plus au claire le code quand j'aurai plus de temps (là je suis en déplacement pour la semaine). Mais s'il faut que je l'extrais et fournisse directement un JS, c'est tout à fait envisageable (faudra juste me demander ;) )

**Comment by eglyn** [comment]
Purée j'étais passé à côté de ton extension, c'est super merci, je peux enfin voir les nouveaux commentaires ! (et mes yeux te remercient aussi :D)

**Comment by hezirem** [comment]
Salut,

Comme indiqué dans [cette issue](https://github.com/NextINpact/Next/issues/13)

J'ai déjà la navigation clavier dans les tuyaux, je mets le code en prod très bientôt,

Cependant petite spécificité
J'ai fait le choix d'utiliser HJKL pour la navigation sur deux dimensions
J'ai déjà intégré la réponse rapide au commentaire séléctionné via Shift + R et ESC pour sortir du mode ajout de commentaire
On bosse sur le sorting des commentaires par état (lus, non lus)

Je suis moi même féru de navigation clavier, vous pouvez compter sur une navigation reddit like sous peu (reddit avec la [reddit enhancement suite](https://redditenhancementsuite.com/) hein, on est pas des sauvages)

Dès que j'aurais fini de régler les quelques problème plus urgents :)

Voici les raccourcis que je compte implémenter actuellement

j move down one comment
k move up one comment
g scroll to page top
G scroll to page bottom
R reply to comment in focus

TODO:
h/l move up/down one thread of comments

**Comment by francois-dorin** [comment]
Hello @hezirem 

Super, merci pour le retour. J'étais passé à côté ;)

Après, attention aussi, on n'est pas tous des utilisateurs de VIM. Emacs c'est la vie (bon, je troll, ni l'un ni l'autre en fait :D)

Plus sérieusement, ma proposition c'était surtout que si ça vous va ce que j'ai fais au niveau de l'extension, alors plutôt que de réinventer la roue, je n'ai aucun problème à ce que vous réutilisiez mon code, ni même l'adaptiez ;) C'était histoire de vous faire gagner un peu de temps car je sais que vous ne chômez pas, et que la navigation dans les commentaires c'est quelque chose qui manque cruellement dans la version actuelle du site.

Certains de vos lecteurs ont installé mon extension juste pour ça !

**Comment by hezirem** [comment]
Je comptais justement revoir ton code aujourd'hui, ça me mâche le travail sur la navigation des commentaires non lus, merci :)

A terme, je vous proposerais un menu admin pour set vos propres raccourcis
Et un moyen similaire de naviguer les articles eux même si c'est désiré

**Comment by francois-dorin** [comment]
Mon code est pourri et fait à la va-vite xD

Mais s'il te donne des idées, alors n'hésite pas ;)

**Comment by francois-dorin** [comment]
Je viens de pusher, pour que tu aies bien la dernière version ;)

**Comment by Glandos** [comment]
> Après, attention aussi, on n'est pas tous des utilisateurs de VIM. Emacs c'est la vie (bon, je troll, ni l'un ni l'autre en fait :D)

Si, mais en bépo. Du coup, hjkl, c'est complètement pas pratique.

> A terme, je vous proposerais un menu admin pour set vos propres raccourcis

Yay. Ça c'est de l'INpactitude ! :+1:

**Comment by eglyn** [comment]
> Salut,
> 
> Comme indiqué dans [cette issue](https://github.com/NextINpact/Next/issues/13)
> 
> J'ai déjà la navigation clavier dans les tuyaux, je mets le code en prod très bientôt,
> 
> Cependant petite spécificité J'ai fait le choix d'utiliser HJKL pour la navigation sur deux dimensions J'ai déjà intégré la réponse rapide au commentaire séléctionné via Shift + R et ESC pour sortir du mode ajout de commentaire On bosse sur le sorting des commentaires par état (lus, non lus)
> 
> Je suis moi même féru de navigation clavier, vous pouvez compter sur une navigation reddit like sous peu (reddit avec la [reddit enhancement suite](https://redditenhancementsuite.com/) hein, on est pas des sauvages)
> 
> Dès que j'aurais fini de régler les quelques problème plus urgents :)
> 
> Voici les raccourcis que je compte implémenter actuellement
> 
> j move down one comment k move up one comment g scroll to page top G scroll to page bottom R reply to comment in focus
> 
> TODO: h/l move up/down one thread of comments

Alors juste, si on peut utiliser des touches plus "parlantes" que des lettres qui rappellent de mauvais souvenir de vim (vive nano) ce serait bien :D 

Je trouve l'utilisation des flèches beaucoup plus parlante et simple :)

**Comment by eglyn** [comment]
en // j'espère que tu continueras de pouvoir maintenir ton extension, car les articles condensés + ancienne taille de police c'est super !
[Feature request]: est-ce que tu pourrais faire en sorte que l'Agora soit minimisé par défaut ? :o

**Comment by francois-dorin** [comment]
> en // j'espère que tu continueras de pouvoir maintenir ton extension, car les articles condensés + ancienne taille de police c'est super !

Merci. J'ai prévu de la maintenir oui. Je supprimerai les fonctionnalités qui seront intégrées nativement au site comme le thème sombre.

> [Feature request]: est-ce que tu pourrais faire en sorte que l'Agora soit minimisé par défaut ? :o

Je pense que techniquement, c'est faisable oui ;)

**Comment by francois-dorin** [comment]
@eglyn 

> [Feature request]: est-ce que tu pourrais faire en sorte que l'Agora soit minimisé par défaut ? :o

Fait ;)

**Comment by francois-dorin** [comment]
@hezirem 

J'ai mis le code à jour. J'ai fais un petit refactoring, donc maintenant, le fichier à regarder c'est celui-ci : https://github.com/francois-dorin/previnpact-extension/blob/master/modules/content_script/navigation-commentaires.ts

Bon code ;)

**Comment by francois-dorin** [comment]
J'ai cru comprendre qu'il y avait des évolutions sur le site :)

J'avais un comportement chaotique de mon extension lors de la navigation dans les commentaires via les touches fléchées, et c'est parce que maintenant le site propose en natif une telle navigation ! Je pense que cela va en ravire plus d'un ^^

Du coup, des suggestions d'évolutions : 
- utiliser un comportement "smooth" plutôt que "instant" (visuellement, cela nous donne une indication de où se trouve le commentaire, si on monte ou on descend)
- mettre en surbrillance le commentaire sur lequel on est (pour savoir sur lequel on est effectivement)

Bonne continuation !

**Comment by pamputt** [comment]
J'imagine que les nouvelles évolutions du site répondent à ce ticket. Faut-il le fermer ?

**Comment by francois-dorin** [comment]
@pamputt Pour ma part, il manque la navigation dans les commentaires déjà lu (sauf si cela a été rajouté et que je ne l'ai pas vu).

Et je maintiens ma position sur le "smooth" plutôt que le "instant". Je trouve ça très désagréable de sauter instantanément d'un commentaire à l'autre, sans savoir où on va. 

Par exemple, avec le "instant", si je suis en train de lire un nouveau commentaire (sur lequel je suis arrivé via la navigation) et que je navigue vers le suivant, il me faut quelques secondes pour savoir si le commentaire sur lequel je suis c'est le commentaire qui répond au commentaire que je viens de lire, ou s'il s'agit d'un commentaire dans un autre fil. Je trouve que cela nuit à la navigation.

Avec le "smooth", pas de souci. Qu'on on navigue, on sait très vite dans la direction où on va, ainsi qu'une évaluation de la "distance" parcourue. Cela permet de savoir tout de suite si on continue de lire un même fil ou si on change complètement.

**Comment by Opwi** [comment]
Bonjour,

Nous avons implémenté la navigation dans les commentaires.
Si vous avez d'autres demandes, n'hésitez pas à ouvrir une nouvelle issue (cette issue fait référence à un ancien design pour les commentaires).

Merci du signalement :smile:
