### ISSUE TITLE
[FEATURE REQUEST] Notification des commentaires

### ISSUE THREAD

**Issue by pierreonthenet** [NextINpact/Next#175]
Bonjour,

Lors de la migration de NXi vers Next, j'ai découvert qu'il manquait les notifications des commentaires, qui permettaient de savoir qui avait répondu à un de nos commentaires.
C'était très pratique pour suivre une discussion.
Serait-il possible de réintégrer cette fonctionnalité s'il vous plaît ?
Merci !

**Comment by pipoupoip** [comment]
ça va venir dans un futur proche (une à deux semaines à priori)
