### ISSUE TITLE
[BUG] Mauvaise importation des anciens articles

### ISSUE THREAD

**Issue by pierreonthenet** [NextINpact/Next#176]
Bonjour,

Lorsque je tente d'accéder à https://next.ink/brief_article/7524-facebook-veut-rapprocher-messenger--whatsapp-et-instagram--quid-de-la-vie-privee--/ je tombe sur une 404, alors que je suis tombé sur l'article à partir de la recherche.

**Comment by dragonis41** [comment]
Effectivement il y a un souci avec les anciens formats d'URL sur certains articles de brief, merci d'avoir fait remonter l'info !

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement :smile:.
