### ISSUE TITLE
Middle click sur le lien vers les commentaires - nouvel onglet

### ISSUE THREAD

**Issue by ymeleouet** [NextINpact/Next#178]
Bonjour,

Un point de détail navigation : pouvoir ouvrir les commentaires d'un article dans un nouvel onglet du navigateur par un middle click ou un clic droit > ouvrir dans un nouvel onglet. Actuellement ce n'est pas possible, et ça oblige à faire des aller/retour, notamment sur les briefs

**Comment by dragonis41** [comment]
Dupliqué de #155
