### ISSUE TITLE
[typo] title des flux rss dans le profil

### ISSUE THREAD

**Issue by nfon** [NextINpact/Next#180]
Sur la page: https://next.ink/profile/ au survol du lien flux rss condensé: il y a écrit: `tout les articles` au lieu de `tous les articles`
![image](https://github.com/NextINpact/Next/assets/5113538/b0db1e7f-a758-49b4-bee1-40caf61df92f)

**Comment by dragonis41** [comment]
J'ai fix, ainsi que le fait qu'on soit obligé de refresh à la main pour afficher les boutons, je vois avec mon chef pour mettre en ligne :)
