### ISSUE TITLE
Double liste `<li>` lors d'une liste

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/Next#183]
Dans les articles, il y a parfois des liens vers d'autres articles de Next, entre les paragraphes.  
Exemple dans https://next.ink/117451/silicium-un-materiau-indispensable-et-omnipresent-mais-critique/, juste avant la première image (hors image d'illustration, bien sûr).

Dans le RSS, ça apparaît sour la forme d'un
```html
<ul>
 	<li style="list-style-type: none;">
<ul>
 	<li><a href="http://next.ink/694/effet-photovoltaique-et-panneaux-solaires-comment-ca-marche/" target="_blank" rel="noreferrer noopener">Effet photovoltaïque et panneaux solaires, comment ça marche ?</a></li>
</ul>
</li>
</ul>
```

Non seulement le HTML est cassé, mais c'est rendu dans un lecteur comme une puce, suivi d'une puce avec le lien.

**Comment by Cqoicebordel** [comment]
Il semblerait que ce soit pas juste les liens, mais toutes les listes. Le rendu de https://next.ink/117390/panneaux-solaires-en-autoconsommation-on-decortique-le-kit-play-de-sunology/ avec ses listes n'est pas… optimisé ;)

**Comment by dragonis41** [comment]
Pour le coup ce n'est pas un problème de RSS mais un problème avec l'article ^^

**Comment by Cqoicebordel** [comment]
Ah ouais. Mais le navigateur arrive à le cacher alors que le lecteur RSS le montre. C'est… rigolo :)

**Comment by dragonis41** [comment]
Parmi ceux que j'ai testés, il n'y a que sur FreshRSS qui est pété, tu utilises lequel ?

**Comment by Cqoicebordel** [comment]
Feeder sur Android.

**Comment by dragonis41** [comment]
J'ai créé un article sur notre serveur de dev et je n'arrive pas à reproduire le problème :sweat_smile: 
Je vais regarder avec l'équipe de Next pour voir comment ils font

**Comment by dragonis41** [comment]
Update : J'ai trouvé comment reproduire le problème ! C'est un bug dans l'éditeur WordPress quand on passe du mode édition graphique au mode "code", le passage de l'un à l'autre casse les balises dû à la manière dont WordPress les parse en interne, il n'y a pas vraiment de fix possible sans passer directement par un merge request dans WP.
Mais on va modifier la manière dont les journalistes utilisent le paywall donc ça supprimera le problème du passage éditeur <-> code.
Je ferme cette issue comme ce n'est pas de notre fait et j'alerte les journalistes de la présence de ce bug ^^

**Comment by Cqoicebordel** [comment]
Ok. C'est un poil dommage, parce que c'est gênant pour la lecture.

Mais ok. C'est pas bien grave. J'espère que Wordpress réglera le problème rapidement.
