### ISSUE TITLE
[RSS] Manque de séparation entre le #Brief et le reste

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/Next#184]
Quand on s'abonne à un RSS complet, les articles du Brief sont noyés au milieu des autres articles, sans aucun moyen de les différencier.  
Dans la v7, ils étaient publiés en même temps, permettant de les identifier par l'heure de parution.

Ce n'est plus possible aujourd'hui, ce qui est dommage, car leurs status permet d'avoir un ordre de grandeur de la durée de lecture.

Je propose de faire comme sur Twitter, et de rajouter l'icône café ☕️ dans leurs titres, uniquement pour le RSS.  
D'autres solutions sont probablement possible aussi. Peut-être utiliser la balise <category>, mais je ne connais pas le support de cette balise dans les lecteurs RSS.

**Comment by dragonis41** [comment]
Je suis d'accord, c'est difficile de différencier un article de brief avec un article classique du premier coup d'oeil

**Comment by dragonis41** [comment]
Quid de la compatibilité des emojis avec les agrégateurs par contre :grimacing:

**Comment by Cqoicebordel** [comment]
Ca dépend des fonts installées, et ce qu'elles prennent en charge :)
Ici, il s'agit d'un caractère venant de Unicode 4.0, datant de 2003. Je pense que le support est plutôt correct ;)
https://emojipedia.org/fr/unicode-4.0

Regarde ce qui a été ajouté à Unicode 6.0, en 2010, qui est, je pense, le niveau de base actuel minimal. https://emojipedia.org/fr/unicode-6.0

Mais sinon, je me demande si on peut mettre une image `<img>` dans un titre d'item RSS…

**Comment by dragonis41** [comment]
Je pensais à 🗞️ qui a été ajouté en 2014, ça devrait le faire en vrai ? ^^

**Comment by Cqoicebordel** [comment]
Je pense ouais. Ca faut le coup de faire un test et de voir si y'a des bugs qui remontent.

Sinon, y'a toujours 📰 (journal) qui date de 2010.

**Comment by dragonis41** [comment]
Moins visuel mais ça marche aussi en effet

**Comment by dragonis41** [comment]
Vu avec l'équipe, je vais suivre la ligne éditoriale déjà en place et mettre un café, comme ça c'est cohérent partout :)

**Comment by dragonis41** [comment]
C'est en prod :)
