### ISSUE TITLE
Raccourci Ctrl Entrée pour valider un commentaire

### ISSUE THREAD

**Issue by Th3l5D** [NextINpact/Next#186]
La flemme a encore frappée ! La validation d'un commentaire est d'un compliqué : le bouton de la souris est pas loin de 5cm plus loin que les touches Control et Entrée. Rendez vous compte ! 5 centimètres !  Entiers !
Et EN PLUS, après avoir mis la main sur la souris, il faut bouger le curseur pour le déplacer sur le bouton Répondre PUIS ENSUITE cliquer. C'est bien trop compliqué tout cette histoire ! Ca doit en refouler plus d'un ! C'est quand même inadmissible tout ça !
(On est vendredi, tout est permis :D )

tldr : lorsque le form de commentaire est focus, serait il possible d'utiliser le raccourci Ctrl + Entrée afin de valider ledit commentaire ? (S'il y a besoin d'un exemple, suffit d'essayer de faire ctrl entrée sur un commentaire github :D)

**Comment by pipoupoip** [comment]
C'est ajouté. 
La flemme a gagné ^^
