### ISSUE TITLE
Pas d'affichage des nouvelles news

### ISSUE THREAD

**Issue by eglyn** [NextINpact/Next#187]
Bonjour !

Ce matin, et comme hier matin, lorsque j'actualise la page (F5), aucune news / brief ne pop, je reste bloqué sur le jour d'avant :/

En revanche, si je vais dans une news et que je reviens sur la page principale, toutes les nouvelles news / brief apparaissent, avec comme date "publié il y a une heure" donc, ben avant que je spam mon F5 sans résultat.

Assez bizarre comme comportement :/

**Comment by riitchy** [comment]
Hello, j'ai un comportement similaire ici sur mon iPhone : en fait selon que je clique sur le bouton Next pour revenir à l'accueil, ou que je tire sur la page pour la refresh, il bascule entre aujourd'hui ou à partir de la veille. Je vous joins une screen capture.


https://github.com/NextINpact/Next/assets/101793680/7c963c60-dcc9-426c-8ddc-507378ea8396

**Comment by pipoupoip** [comment]
C'est réparé 👍
