### ISSUE TITLE
Mauvais affichage de l'heure lors des éditions de commentaire

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/Next#188]
Je fais faire court, parce qu'une image vaut mieux, tout ça…

![image](https://github.com/NextINpact/Next/assets/2286246/de167866-53a8-4a2e-8868-4e691c4698da)

Commentaire posté, édité dans la foulée.

**Comment by psychopatt** [comment]
Yep, je confirme, j'allais rapporter le même mais on va éviter les dupliqués.

Si ça a un intérêt, c'est visible [là](https://next.ink/117736/quoi-de-neuf-a-la-redac-9-lebrief-2-0-ligne-edito-dossiers-de-fonds/). Je vous aurais bien mis un lien direct vers le commentaire mais... #219  😄 donc commentaire de *psychopatt*.

**Comment by pipoupoip** [comment]
On a résolu notre souci de fuseaux horaires et on affiche maintenant les heures "absolues" plutôt qu'un temps relatif :)
