### ISSUE TITLE
[Thèmes sombres] Mauvaises couleurs de liens dans les commentaires

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/Next#189]
Dans les themes sombres (les deux), on a la couleur par défaut sur les liens dans les commentaires, qui ne colle pas avec le reste des thèmes. 

![image](https://github.com/NextINpact/Next/assets/2286246/64f908dc-cf34-4212-9424-2f7cefccfe32)

**Comment by pipoupoip** [comment]
C'est corrigé :)
