### ISSUE TITLE
notification de réponse à un commentaire

### ISSUE THREAD

**Issue by Albirew** [NextINpact/Next#190]
Sur NxI, on avait une notification quand quelqu'un nous citait ou répondait à un de nos commentaires.
Est-ce que c'est prévu pour Nx aussi?

**Comment by pamputt** [comment]
Est ce que c'est la même chose que https://github.com/NextINpact/Next/issues/175 ?

**Comment by Albirew** [comment]
oui, je suis aveugle :sweat_smile: 

closed: duplicate of #175
