### ISSUE TITLE
Section Flock : la miniature ouvre l'article au lieu d'afficher l'image

### ISSUE THREAD

**Issue by Wivik** [NextINpact/Next#191]
Je ne me rappelle plus le comportement de l'ancienne version, mais je suis persuadé que cliquer sur la miniature dans le bandeau affichait l'image. Là, elle ouvre le lien vers l'article l'ayant inspiré.

L'ancien comportement me semble plus équilibré : naviguer facilement entre les images et ouvrir la référence via le lien qui se trouvait en dessous.

**Comment by darkweizer** [comment]
+1 !
J'ai un petit écran d'ordi et quand je scrolle, je ne tombe jamais avec les images en entier dans l'écran. Cliquer dessus pour les agrandir me permettait de les avoir centré et en entier. Là il faut que je prenne ma barre de navigation au clique et que je les centre. C'est assez pénible 😇

**Comment by theoldscudo** [comment]
hello, 
pareil sur mobile c'est une cata. 
On a les 4 ou 5 images, avant on cliquait pour afficher l'image en popup (caroussel), là ça ouvre l'article ou la page d'accueil ça dépend.
la taille des 2 flèches n'en parlons pas sur un écran de 300*700px 👎 faut une loupe pour viser.
En plus le zoom à 2 doigts est bloqué, on peut pas zoomer l'article pour voir l'image / le texte en plus grand.
obligé de passer par clic droit / "ouvrir image nouvel onglet" et là on peut voir en grand zoomer etc.... très dommage.

**Comment by Opwi** [comment]
Bug coté éditeur wordpress. En attente de fix de leur part.

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug en ajoutant nous meme une visionneuse d'image.

Merci du signalement 😄
