### ISSUE TITLE
[Galerie] Les deux flèches font avancer dans le même sens

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/Next#193]
Comme on le voit dans le dernière article de Flock, les deux flèches font avancer l'image en grand d'une unité. Oui, y compris la flèche retour qui devrait faire reculer l'image d'une unité.

C'est peut-être dû au changement de "position-list" qui est fait lorsque l'image est changée.

Note : la navigation au clavier ne fonctionne pas. Presser gauche ou droite devrait faire parcourir les images.  
Note 2 : La balise `data-large-src` ne contient pas l'URL des bonnes images.

**Comment by pipoupoip** [comment]
C'est corrigé :)
