### ISSUE TITLE
Les images ne semblent pas utiliser le CDN

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/Next#194]
Les URLs utilisées pour toutes les images d'articles (notamment dans le dernier de Flock) sont toutes de la forme `https://next.ink/wp-content/uploads/2023/11/*`.

Je suis pas sûr si c'est volontaire ou non, mais sachant que ça peut coûter très cher, j'ai préféré jouer la prudence :)

**Comment by Opwi** [comment]
Hello,

Nous sommes au courant et c'est pour le moment voulu. Cela risque de bientôt évoluer pour être directement hébergé sur notre CDN.

Merci pour votre signalement.😁
