### ISSUE TITLE
Image trop grande dans certains commentaires & citations

### ISSUE THREAD

**Issue by francois-dorin** [NextINpact/Next#195]
Si on regarde la page https://next.ink/731/le-poing-dev/#comment/2163043

Notamment le commentaire qui commence par "Et voilà ! Dispo sur le github", on constate que l'image sort légèrement du cadre.

Si on regarde les images ensuite dans les citations, là, c'est catastrophiques (image taille normale)

**Comment by pipoupoip** [comment]
C'est corrigé :)
