### ISSUE TITLE
Mise en page cassée pour certains commentaires

### ISSUE THREAD

**Issue by francois-dorin** [NextINpact/Next#196]
Sur la page https://next.ink/731/le-poing-dev/#comment/2163043, les premiers fils de commentaires ont tous un cadre. A la fin de la page, le cadre à totalement disparu.

**Comment by pipoupoip** [comment]
Le nettoyage du html à l'enregistrement des commentaires devrait avoir résolu le souci. 
Je dirais qu'on ferme et qu'on rouvrira si le cas devait se représenter
