### ISSUE TITLE
Message d’erreur au renouvellement d’abonnement

### ISSUE THREAD

**Issue by Mimoza** [NextINpact/Next#197]
Bonjour,
Je viens de renouveller mon abonnement pour une durée annuel.
Il y a un soucis au niveau du message de confirmation car il met «Le paiement à été refusé» alors que le débit a bien été fait et que dans la gestion de mon compte on constate bien que ça été pris en compte.

**Comment by hezirem** [comment]
Salut !

Merci pour ton feedback, je pense pense savoir quel est le problème

Simple question, avais tu une mauvaise connexion au moment ou tu t'est abonné ?

**Comment by Mimoza** [comment]
Salut,
J'atais en partage de connexion avec mon tel, mais j'ai bien fait la procédure via mon PC de bureau. La qualité de la connexion était bonne.
Pour info :
* FF 119 
* Manjaro Linux

**Comment by pipoupoip** [comment]
@hezirem me confirme que c'est corrigé, ça ne se reproduira plus. 
Je clos :)
