### ISSUE TITLE
[desktop] Avatars des commentaires écrasé en hauteur

### ISSUE THREAD

**Issue by AIMAR-S** [NextINpact/Next#2]
Testé en desktop sur Firefox les avatars sont parfois écrasé, faute au flex shrink.

Piste de solution àjouter `flex-shrink` à `0` :

```
.author-avatar-bloc img {
  border-radius: 50%;
  flex-shrink: 0;
}
```

**Comment by MosieurClement** [comment]
C'est corrigé, merci te ton aide 😉
