### ISSUE TITLE
Thème sombre !

### ISSUE THREAD

**Issue by seboss666** [NextINpact/Next#20]
Oui je sais c'est toujours pénible à lire, mais l'arrivée des thèmes sombre sur NXI m'avait vraiment ravi (enfin surtout mes yeux), je sais pas si c'est déjà sur la roadmap (dans ce cas désolé pour le temps perdu), mais il nous faut au moins un thème sombre.
Surtout que la légèreté de la charte actuelle devrait faciliter un peu le travail :)

**Comment by MosieurClement** [comment]
Le thème sombre est bien prévu, il est en cours de création par notre designer, on tient aux yeux des lecteurs 😆

**Comment by Nightmaster** [comment]
Je sais pas si ça peut aider (votre designer), mais (en attendant pour les autres aussi 😉), un module complémentaire type Dark Reader rend un rendu plus appréciable pour les yeux.
N.B. Un mode noir `#000` peut être une bonne idée pour les écrans OLED 😁

**Comment by xavierforestier** [comment]
Up! Please

**Comment by blackburst67** [comment]
> Up! Please

Ooooh oui, maintenant qu'on est forcé sur la béta, la thème sombre au plus vite merci ;-)

**Comment by dragonis41** [comment]
Il est en cours de dev, surement une version dark pour lundi :eyes:

**Comment by MosieurClement** [comment]
> > Up! Please
> 
> Ooooh oui, maintenant qu'on est forcé sur la béta, la thème sombre au plus vite merci ;-)

![image](https://github.com/NextINpact/Next/assets/143634191/b053ca4c-a570-407c-9768-82e7e892ae13)

🤫🤫🤫🤫🤫

**Comment by MosieurClement** [comment]
![image](https://github.com/NextINpact/Next/assets/143634191/e9420f31-86b6-4068-8ab5-f2d802338603)

Peut-être bien que des petites souris sont passées de vos configurations de compte :eyes: 

https://next.ink/profile/

**Comment by Fabiensk** [comment]
Merci pour les 2 nouveaux thèmes sombres. Avec ceux-ci, les champs texte comme le champ de recherche ou celui de changement de pseudo utilise une couleur de texte noir (au moins avec Firefox/Kubuntu), ce qui rend la lecture de ce qu'on tape difficile.
![sombre](https://github.com/NextINpact/Next/assets/378842/473e485f-a7b3-4670-aa6d-7d31717d763a)
C'est la vision « verre à moitié vide » du cadeau d'avant week-end.

**Comment by pamputt** [comment]
> Merci pour les 2 nouveaux thèmes sombres. Avec ceux-ci, les champs texte comme le champ de recherche ou celui de changement de pseudo utilise une couleur de texte noir (au moins avec Firefox/Kubuntu), ce qui rend la lecture de ce qu'on tape difficile. ![sombre](https://private-user-images.githubusercontent.com/378842/285533108-473e485f-a7b3-4670-aa6d-7d31717d763a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwODk2ODYsIm5iZiI6MTcwMTA4OTM4NiwicGF0aCI6Ii8zNzg4NDIvMjg1NTMzMTA4LTQ3M2U0ODVmLWE3YjMtNDY3MC1hYTZkLTdkMzE3MTdkNzYzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyN1QxMjQ5NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTI2YWI0ODIxODVlMWUyNjRiZDQ0ZDE1NzAyODQ2ZmVhYzU2ZmY4M2UzNzQzMmI0NjQ5NzExMGZlZTlmMTY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WMcHjs9h0oYvjFAAKbHX5ljQ_wdrqQ-W-STSmCQbm0A) C'est la vision « verre à moitié vide » du cadeau d'avant week-end.

Je pense que tu devrais ouvrir un nouveau ticket pour suivre ce problème sépcifique. Car la demande de création d'un thème sombre est satisfaite et donc ce ticket devrait être clos.
