### ISSUE TITLE
Brief: le bouton pour voir les commentaires n'est pas un lien

### ISSUE THREAD

**Issue by oliverpool** [NextINpact/Next#200]
En bas de chaque brief, il y a un bouton pour voir les commentaires:

![image](https://github.com/NextINpact/Next/assets/3864879/e741ac3e-02ca-452d-83ca-59e873e24b67)

Le soucis c'est que ce n'est pas un "vrai" lien, mais du JS avec `onclick="open_comments('https://next.ink/brief_article/...')"`:
- le clic n'est pris en compte que sur la bulle (pas sur le nombre de com')
- les raccourcis pour ouvrir dans un nouvel onglet (ctrl+clic / clic molette) ne fonctionnent pas (donc très pénible à utiliser)

**Comment by oliverpool** [comment]
Un lien `<a href="https://next.ink/brief_article/...#comments` serait idéal d'un point de vue accessibilité et devrait résoudre #118 :)

**Comment by dragonis41** [comment]
Dupliqué de #155
