### ISSUE TITLE
Thème sombre: contraste texte input

### ISSUE THREAD

**Issue by MosieurClement** [NextINpact/Next#201]
Merci pour les 2 nouveaux thèmes sombres. Avec ceux-ci, les champs texte comme le champ de recherche ou celui de changement de pseudo utilise une couleur de texte noir (au moins avec Firefox/Kubuntu), ce qui rend la lecture de ce qu'on tape difficile.
![sombre](https://github.com/NextINpact/Next/assets/378842/473e485f-a7b3-4670-aa6d-7d31717d763a)
C'est la vision « verre à moitié vide » du cadeau d'avant week-end.

_Originally posted by @Fabiensk in https://github.com/NextINpact/Next/issues/20#issuecomment-1826018246_

**Comment by Dadkill** [comment]
J'ajoute que le problème existe aussi sur la page "déontologie" (en plus du fait que le texte des cookies n'est pas du tout aligné, mais ça, ça avait déjà été signalé)

![image](https://github.com/NextINpact/Next/assets/22544947/28e181b2-0b63-4526-9e40-835a0ae25232)

**Comment by pamputt** [comment]
Les deux problèmes de couleurs semblent avoir été corrigés.

**Comment by Dadkill** [comment]
Oui et non, le problème subsiste toujours dans la recherche sur mobile.

![Screenshot_2023-12-05-12-11-04-41_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/NextINpact/Next/assets/22544947/ddca4491-cad3-426f-b9e3-54d6958bc347)

**Comment by Fabiensk** [comment]
À cette heure, sur mes Firefox (Kubuntu, Android), le texte apparaît bien contrasté pour les deux thèmes sombres.

**Comment by Dadkill** [comment]
Petit update car le problème est toujours présent et se trouve être grandement inconfortable durant la navigation de tous les jours.

**Comment by pipoupoip** [comment]
C'est corrigé :) 
Avez-vous noté d'autres problèmes de contraste en mode sombre qui nous auraient échappé ?

**Comment by Dadkill** [comment]
Pour ma part, c'est tout bon ! C'est le seul oubli que j'avais constaté au cours de mon utilisation :) ! Merci beaucoup pour le travail accompli !
