### ISSUE TITLE
[RSS] Gérer les agrégateurs qui ne prennent pas les dates en compte dans le tri des postes

### ISSUE THREAD

**Issue by cchangenot** [NextINpact/Next#202]
Il semble y avoir un problème avec le flux rss "Condensé" (Flux complet, brief réduit) : il récupère uniquement des entrées du brief

**Comment by dragonis41** [comment]
Testé sur 6 agrégateurs différents et aucun problème, tu utilises lequel ?

**Comment by cchangenot** [comment]
J'utilise le plugin livemarks pour firefox

**Comment by cchangenot** [comment]
Voilà ce qu' j'obtiens, on dirait qu'il manque les liens vers les articles 

![Capture d’écran du 2023-11-28 10-54-27](https://github.com/NextINpact/Next/assets/3227265/a7dc2a9c-5569-4dec-aa54-d1528b36e5ed)

**Comment by cchangenot** [comment]
En fait je crois que le flux contient bien les articles non brief, mais ils ne sont pas correctement ordonnés par date : ils apparaissent après tous les articles du brief

**Comment by dragonis41** [comment]
> En fait je crois que le flux contient bien les articles non brief, mais ils ne sont pas correctement ordonnés par date : ils apparaissent après tous les articles du brief

ça c'est normal, c'est difficile de faire autrement, à la limite je pourrais essayer de merge les briefs avec la liste des articles dans un seul tableau pour ensuite faire un sort dessus mais ce n'est pas fou. Tous les agrégateurs que j'ai testés trient les articles par date et non pas par ordre d'apparition dans le feed :/ 
Je vais essayer de voir comment je peux changer le code pour gérer les agrégateurs qui ne prennent pas les dates en compte !

**Comment by cchangenot** [comment]
Merci. En tout cas ça fonctionnait bien sur Next Inpact

**Comment by dragonis41** [comment]
Pourtant ils utilisaient la même technique que moi pour le condensé :sweat_smile: 
J'avais déjà mentionné ce potentiel problème dans une issue en interne mais je n'étais, jusqu'à maintenant, jamais tombé sur quelqu'un qui avait vraiment le souci haha, je vais essayer de fix ça, au moins ça sera fait :)

**Comment by dragonis41** [comment]
C'est en prod ! 
J'ai refactor un peu le code pour mieux gérer ce genre de cas et je trie mes listes de poste avant de les envoyer pour qu'ils soient par ordre chronologique ^^
Je te laisse rouvrir cette issue et me ping si t'as encore le souci à l'avenir :)

**Comment by cchangenot** [comment]
Je confirme, ça fonctionne :+1: 
Merci beaucoup

**Comment by dragonis41** [comment]
Je t'en prie :)
