### ISSUE TITLE
Identifiants nextinpact non reconnus

### ISSUE THREAD

**Issue by mooms06** [NextINpact/Next#203]
Bonjour,

Mes identifiants fonctionnent sur https://www.nextinpact.com et  https://forum.nextinpact.com mais pas sur https://next.ink/login/

J'ai le message _Invalid username or password_

![image](https://github.com/NextINpact/Next/assets/25405517/942df795-4d80-40a2-9b3e-deec9a1e3ee8)

J'ai essayé avec le mail comme identifiant, pareil.
J'ai essayé la procédure mot de passe oublié, je ne reçois pas de mail, j'ai vérifié les spams.

![image png 746f2b529fd611b4dffa2e3d80e32f76](https://github.com/NextINpact/Next/assets/25405517/f335915b-4d60-49ef-bf23-9d0094e3778e)

**Comment by dragonis41** [comment]
Bonjour, as-tu toujours le souci ? Je précise qu'il faut bien utiliser les anciens identifiants de nextinpact.com.
Sinon je peux forcer un envoi de mail pour que tu puisses reset ton mot de passe

**Comment by mooms06** [comment]
Salut,

J'ai reçu les mails de reset de mdp au bout d'un moment (ils étaient dans les spams) et j'ai pu reset le mdp et me connecter 

Merci 👍

**Comment by dragonis41** [comment]
Top, on travaille sur ce souci de mail qui partent dans les spams ^^
