### ISSUE TITLE
Garder la partie "Agora" fermée une fois qu'on l'a fermée

### ISSUE THREAD

**Issue by EricBrunel** [NextINpact/Next#204]
Petite "feature request": la partie "Agora" ne m'intéresse pas plus que ça, et en général, je la ferme avec le bouton qui va bien. Sauf que si ensuite je vais lire un article et que je retourne sur la page d'accueil, l'Agora se réouvre. Je préfèrerais qu'elle reste fermée.
Ca n'est pas critique et encore moins urgent, mais j'ai vu dans les commentaires que d'autres auraient préféré avoir ce comportement aussi, donc je rentre ça ici.

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement :smile:.
