### ISSUE TITLE
Articles avec nouveaux commentaires sur la page d'accueil, mais sans nouveau commentaire une fois sur l'article

### ISSUE THREAD

**Issue by francois-dorin** [NextINpact/Next#205]
Alors ce problème n'est pas présent à chaque fois, je tiens à le souligner.

Mais il m'est arrivé à plusieurs reprises de cliquer sur un article car il y avait de nouveaux commentaires. Et une fois arrivé sur l'article, aucun nouveau commentaire.

Suis-je le seul à expérimenter ce comportement ?

**Comment by eglyn** [comment]
Idem, j'ai constaté ça aujourd'hui sur certains articles du Brief

**Comment by francois-dorin** [comment]
Témoignage de Fred42 sur le problème (https://next.ink/118034/le-poing-dev-round-6/#comments)

> 2) Certaines fois, il y a des commentaires qui sont bien signalés comme non lus, mais quand on veut les lire, il n'y a pas de petit point rouge. C'était par exemple le cas sur l'article "G-PON, XGS-PON et 50G-PON : jusqu’à 50 Gb/s en fibre optique" aujourd'hui pour moi. Il y avait un bon paquet de commentaires non lus mais aucun n'avait de point rouge et l'extension de fdorin ne permettait donc plus de naviguer avec les flèches gauche et droite. Je me suis rabattu sur les touches , mais c'est moins pratique.

**Comment by pipoupoip** [comment]
On a bon espoir d'avoir trouvé la racine du mal :) 
On ferme dans la semaine si on constate que tout roule :)

**Comment by pipoupoip** [comment]
Vous confirmez ne plus avoir rencontré le souci depuis Noël ?

**Comment by francois-dorin** [comment]
Cela fait effectivement plusieurs jours que je n'ai pas eu le souci. Ce qui est plutôt bon signe ^^

**Comment by pipoupoip** [comment]
Ferd me confirme ne plus avoir le souci non plus. Je pense que vous êtes deux lecteurs suffisamment assidus pour qu'avec vous on considère le problème résolu. A la hussarde, peut-être, mais résolu :D
