### ISSUE TITLE
[ancien site] redirection inopérente si cache service worker

### ISSUE THREAD

**Issue by theoldscudo** [NextINpact/Next#206]
hello,

il y a bien une redirection 301 de nextinpact.com vers next.ink, mais du fait du service worker, elle n'opère pas tant qu'on n'a pas été trifouiller dans firefox pour le supprimer et ensuite recharger la page.
il y a moyen éventuellement de faire en sorte que si on a le service worker encore présent, celui-ci soit supprimé lors du chargement de la page ou au moins informé d'aller se faire réviser son 301 ?

**Comment by Opwi** [comment]
Hello,

Malheureusement il ne semble pas y avoir de solutions de notre coté pour modifier le comportement du service worker (nous ne maintenons plus l'ancienne infrastructure). Par conséquent à part supprimer coté client le service worker ou d'aller sur https://next.ink il n'y a pas d'autres options.
