### ISSUE TITLE
Edition d'un commentaire : perte de mise en forme

### ISSUE THREAD

**Issue by francois-dorin** [NextINpact/Next#207]
Lors de l'édition d'un commentaire, j'ai perdu la mise en forme.

En l'occurrence, j'avais un commentaire avec un lien (via la balise `<a>` puisque pour l'instant la syntaxe markdown n'est pas dispo). J'ai édité le commentaire, la balise avait disparu. Le texte cliquable (celui contenu dans la balise donc) était bien là par contre.

**Comment by dragonis41** [comment]
Hello ! J'ai remarqué ce souci aussi, je pense que c'est dû à la serialization du texte par WordPress, on va essayer de fix ça en même temps que l'intégration du Markdown

**Comment by francois-dorin** [comment]
Alors, pour le coup, ce n'est pas Wordpress. Je suis tombé sur l'origine du problème je pense en travaillant sur mon extension.

Dans la fonction javascript `replyOrEdit`, vous faite usage la méthode jQuery `text()` pour initialiser le contenu de l'éditeur. Cette méthode ne renvoie que le texte, pas les tags, d'où la perte de mise en forme.

```javascript
if (edit) {
  $("#comment-send-butt").attr("editid", cid);
  var content = $('#comment-content-' + cid + " .comment-text-content").text(); // <-- ligne qui provoque la perte de mise en forme
  $("#reply-editor").val(content);
  } else {
  $("#comment-send-butt").attr("editid", 0);
  }
```

**Comment by dragonis41** [comment]
Ah yes bien vu ! Je n'avais pas vu ton commentaire

**Comment by dragonis41** [comment]
Bon, finalement on va faire différemment comme on va intégrer le markdown

**Comment by pipoupoip** [comment]
Effectivement. 
Maintenant qu'on gère en markdown (\o/), à l'édition, c'est bien le texte brut enregistré par l'utilisateur dans son commentaire qui apparait :)
