### ISSUE TITLE
Liens des chapitres non cliquables

### ISSUE THREAD

**Issue by Otiel** [NextINpact/Next#21]
Les liens présents sur les chapitre à droite de l'article n'ont pas d'action, il est impossible de se rendre à un chapitre particulier.

![image](https://github.com/NextINpact/Next/assets/3851902/9ea231e4-588b-4876-a807-fffe2fd8dd4d)

**Comment by pipoupoip** [comment]
C'est, évidemment, prévu. 
Le temps nous a manqué pour l'intégrer dans la _beta_

**Comment by Nozalys** [comment]
Sur le même sujet, il serait bien de reprendre le même concept que sur NXI à savoir le highlight du chapitre dans cette bare de navigation, en fonction de la position du scrolling :)

**Comment by c100k** [comment]
Ah j'allais le reporter ☺️ !

S'il vous plait, pas d'usine à gaz, on s'en fiche de voir quel chapitre est actuellement actif.

Utilisez des ancres : simple, accessible, partageable, pas usine à gaz, pas de bugs bizarres 🙏🏽

**Comment by Alexandre-Gliganic** [comment]
Implémenté dans la release [v0.3](https://github.com/NextINpact/Next/releases/tag/v0.3).
