### ISSUE TITLE
Le texte de légende d'image écrase le contenu

### ISSUE THREAD

**Issue by Albirew** [NextINpact/Next#210]
Une image vaux mieux qu'un discours:

Firefox:
![Screenshot 2023-11-28 at 22-04-11 À la Samaritaine des caméras camouflées en détecteurs de fumée - Next](https://github.com/NextINpact/Next/assets/2805161/94ec990b-bf76-4d13-a250-64571815de4a)

Mobile (overpackaging via les commentaires): https://www.site-shot.com/FieiqI4wEe6FOwJCrBEAAg

**Comment by pamputt** [comment]
C'est marrant, mais je n'ai pas ce comportement sur desktop linux, firefox 120. Fournir des informations sur ton système/OS ainsi que le navigateur utilisé pourrait permettre d'essayer de reproduire ce problème plus facilement.

**Comment by dragonis41** [comment]
> C'est marrant, mais je n'ai pas ce comportement sur desktop linux, firefox 120. Fournir des informations sur ton système/OS ainsi que le navigateur utilisé pourrait permettre d'essayer de reproduire ce problème plus facilement.

On a fix assez rapidement ce problème mais c'est possible qu'il y ait encore certains articles de concernés, c'est pour ça qu'on ne ferme pas l'issue tout de suite ^^
