### ISSUE TITLE
Profil - choix du thème - valeur par défaut

### ISSUE THREAD

**Issue by AnaelMobilia** [NextINpact/Next#211]
Hello,

Dans le profil, on peut choisir le thème souhaité dans la partie "Paramètres".

Lorsque l'on a pas effectué de choix (donc que l'on utilise le thème par défaut), aucun bouton radio n'est coché :
![image](https://github.com/NextINpact/Next/assets/6187125/46e0d309-ce12-4e56-b848-f884c205c6bf)

Je m'attendrais à ce que le thème actuel soit sélectionné.

Bonne journée,
Anael

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement 😄
