### ISSUE TITLE
Profil - typo dans le titre

### ISSUE THREAD

**Issue by AnaelMobilia** [NextINpact/Next#212]
Hello,

Lorsque l'on consulte le profil, le title de la page est "profil**e**""
![image](https://github.com/NextINpact/Next/assets/6187125/bb80cce9-6ac8-42d4-9331-c021994f17b6)

C'est l'URL de la page, mais pour le title, ça devrait être sans le "e" :-)

Bonne journée,
Anael

**Comment by dragonis41** [comment]
Fixé :)
