### ISSUE TITLE
MAJ Avatar

### ISSUE THREAD

**Issue by eglyn** [NextINpact/Next#214]
Bonjour :)

Je n'arrive pas à changer d'avatar :/
J'ai supprimé l'ancien, cela fonctionne, mais que je vais chercher le nouveau, je le sélectionne, et une fois validé ben il se passe rien :/
J'ai tenté en jpeg et png pareil... L'avatar fait 1.4Mo en jpg et 1024*1024 et 152Ko en png même dimensions.

j'ai tenté avec un autre navigateur, mais ça fait pareil aussi :(

une idée ?

**Comment by Opwi** [comment]
Hello,

Le problème devrait être réglé ! 
Pour la procédure, appuyez sur `Modifier`, sélectionnez votre image puis sur le bouton `Valider`.

Si vous avez à nouveau le problème, vous pouvez rouvrir cette issue 😁
