### ISSUE TITLE
[RSS] Pas de `src` pour certaines `<img>`

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/Next#216]
Dans le flux RSS, dans l'article "Le poing Dev – round 6", on trouve ce code : 
```html
<img post-id="118034" fifu-featured="1" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" data-src="https://cdn.next.ink/inpactv7/data-next/images/bd/wide-linked-media/12965.jpg" />
```

Notez l'absence de `src`, qui fait que l'image ne s'affiche pas dans les lecteurs RSS.

Il est (plus que) probable qu'il s'agisse d'un problème dû à l'écriture du post, mais je remplis ce bug pour qu'il y est des barrières évitant que ça se reproduise.

**Comment by dragonis41** [comment]
Humm, à priori c'était un souci d'édition sauf que le RSS n'a pas été mis à jour :/
Je remarque que ça ne le fait qu'avec les points dev (depuis que j'ai corrigé le bug des images) je regarderais au prochain point dev si le problème persiste

**Comment by Cqoicebordel** [comment]
Ah bah moi je peux reproduce !
Pour l'article Le poing dev round 8, https://next.ink/119887/le-poing-dev-round-8/, l'image d'en-tête n'apparaît pas dans le flux RSS.  
Et pour cause, puisque la balise en question est : 
```html
<img post-id="119887" fifu-featured="1" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" data-src="https://next.ink/wp-content/uploads/2023/12/12965-1024x496.jpg" />
```
Ici encore, pas de `src`.

**Comment by dragonis41** [comment]
Et on notera que c'est encore un poing dev, je suspecte donc Ferd de ne pas bien mettre les images dans l'article :grimacing:

**Comment by francois-dorin** [comment]
Alors, juste comme ça, j'ai constaté aussi ce comportement au niveau des commentaires au moment où j'ai mis une option de changement de disposition des commentaires dans mon extension.

Pour être plus précis, c'était au niveau des avatars. J'avais besoin de récupérer les images. Et après l'ajout / édition d'un commentaire, je perdais les avatars car les balises img n'avait que l'attribut data-src et pas l'attribut src. Sur le coup, je me suis dis qu'il devait y avoir un javascript quelque part qui initialisait les info. Mais je n'ai pas creusé plus que ça. J'ai fais ma feignasse et me suis rabattu sur l'attribut data-src si src est manquant. Et c'était il y a quelques semaines, lorsque j'ai ajouté cette fonctionnalité.

Voilà, je ne sais pas si ça peut aider...

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement :smile:.
