### ISSUE TITLE
feat: pouvoir filtrer des auteurs de commentaires

### ISSUE THREAD

**Issue by jonathanlermitage** [NextINpact/Next#218]
Pouvoir filtrer certains auteurs de commentaires et, idéalement, importer nos listes de comptes déjà bloqués depuis l'ancien site.  
Cette fonction manque cruellement au nouveau site, et permettrait de ne plus se soucier de certains utilisateurs toxiques.

**Comment by Opwi** [comment]
Bonjour,

Nous avons implémenté le blocage d'utilisateurs !
