### ISSUE TITLE
[FEATURE REQUEST] Hook/lien pour chaque commentaire

### ISSUE THREAD

**Issue by Albirew** [NextINpact/Next#219]
Est-il possible de rajouter un lien vers chaque commentaire avec un hook qui descendrais la page directement sur le commentaire (/nom-de-l-article/#commentaire-12456) ?

Je crée un issue pour ça, mais je pense que dans tout les cas, ce sera plus ou moins nécessaire pour #175

**Comment by psychopatt** [comment]
(duplicata de #145)

**Comment by Albirew** [comment]
fermé: duplicat de #145
