### ISSUE TITLE
Rendre les catégories cliquables pour filtrer les articles

### ISSUE THREAD

**Issue by Otiel** [NextINpact/Next#22]
C'est bien d'avoir des pilules pour les catégories sous chaque article avec couleur associée.

Ca serait top de pouvoir cliquer dessus (et depuis le footer) pour filtrer les articles de la catégorie.

**Comment by pipoupoip** [comment]
C'est tout à fait prévu

**Comment by Cqoicebordel** [comment]
J'imagine que c'est prévu pour les auteurs aussi ? (affiche la liste des articles qu'iels ont écrit)

**Comment by pipoupoip** [comment]
Oui le DA est dessus :)

**Comment by MosieurClement** [comment]
C'est ajouté sur desktop pour l'instant

**Comment by Otiel** [comment]
Top ! Et les rendre cliquables depuis un article, c'est envisageable ?

**Comment by hwti** [comment]
> C'est ajouté sur desktop pour l'instant 😁

Ca ne fonctionne que depuis le bloc au dessus des articles, pas depuis les catégories affichés sous les articles (aussi bien sur la page principale que celle de l'article) malgré l'animation hover, ni pour les briefs (c'est cliquable mais ça mène sur la page du brief).

En plus le filtrage n'affiche que les articles de la semaine dernière (pas ceux du 23/10 donc), et si je l'enlève ça s'arrête au 21/10.

**Comment by bansan85** [comment]
Je profite pour préciser qu'il n'est peut-être pas utile de mettre la liste des catégories en haut ET en bas de la page principale.

Moi qui suis pour alléger la page principale, je serai pour enlever en haut. Mais je pense que c'est plutôt celle en bas qui est en trop.

Et enfin : est-ce que quelqu'un filtre les catégories ? Est-ce que c'est une fonctionnalité utile ? Si on passe à 5 articles par jour avec toutes les brefs regroupés dans un seul article, le filtrage me semble optionel. Surtout que Next étant un site d'actualité, on le consulte dans le pire des cas une fois par semaine. Ca fait environ 20 articles, ce n'est pas la mort.

**Comment by pipoupoip** [comment]
Tout est cliquable et une fois filtré par catégorie, on ne se limite plus à la semaine en cours :)

**Comment by Cqoicebordel** [comment]
C'est coule !

Trois remarques : 
* La page des résultats a une pagination inversée de celle du site (→pour voir les articles plus anciens sur la home, faut faire "page précédente", alors que là, c'est "page suivate). C'est pas rédhibitoire, hein, c'est juste pour être sûr que c'est fait "exprès".
* Y'a un doublon dans les paramètres de l'URL. Par exemple, je peux avoir `category-page/?category=droit&id=12`, et avoir l'image de header "Droit" (par la `category`), avec les articles de Flock. C'est pas idéal. En garder un seul serait nécessaire.
* Surtout pour pouvoir faire des requêtes avec deux catégories `?id=12&id=13` par exemple.
