### ISSUE TITLE
Perte des smilies legacy à l'édition de commentaire

### ISSUE THREAD

**Issue by Wivik** [NextINpact/Next#220]
Si les smilies legacy de l'ancien site sont toujours convertis, ils sont perdus lorsqu'on édite son message.

![image](https://github.com/NextINpact/Next/assets/48727868/0d4ee333-aa62-43af-a11d-16985c938b04)

**Comment by pipoupoip** [comment]
C'est tout bon :) 
On a un nouvel éditeur avec sélecteur de smileys. 
Et on gère le markdown. 
Et maintenant à l'édition, c'est bien le texte entré par l'utilisateur qui est édité :)
