### ISSUE TITLE
Ordre des articles non chronologique

### ISSUE THREAD

**Issue by francois-dorin** [NextINpact/Next#221]
J'ai constaté ce matin que les articles n'étaient pas toujours affichés par ordre chronologique.

L'article de Jean-Marc Manach est avant celui de Martin Clavey, alors qu'il a été publié avant.

![ordre article](https://github.com/NextINpact/Next/assets/36440144/33dcb26e-73bb-4f1a-8878-d73666f98751)

**Comment by dragonis41** [comment]
Non non, c'est l'issue #149 : Le calcul de l'heure relative n'est pas bon, c'est censé être corrigé mais à priori c'est toujours là

**Comment by francois-dorin** [comment]
Arf, ok, désolé pour le doublon !

Là, les minutes vont croissant, mais le premier commentaire est quand même plus vieux que la date de l'article de Jean-Marc Manach.
