### ISSUE TITLE
Affichage des petites images dans les articles

### ISSUE THREAD

**Issue by psychopatt** [NextINpact/Next#223]
Lorsqu'elles sont plus petites, les images des articles sont étirées jusqu'à remplir la largeur de la colonne de l'article. Ce n'est généralement pas utile et prend plus de place que nécessaire, et ça pique les yeux quand la résolution de base est vraiment basse. 
Le centrage serait sans doute une meilleure solution.

Exemple [ici](https://next.ink/719/le-rapport-transparence-twitter-x-confirme-faiblesse-sa-moderation/) avec la première image de l'article.

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement :smile:.

**Comment by psychopatt** [comment]
Euh... non ? 🧐
Le comportement est toujours le même que celui décrit initialement.

**Comment by psychopatt** [comment]
Up ?
