### ISSUE TITLE
"Offrir" ne copie pas le lien dans le presse-papier tel qu'indiqué (Opera)

### ISSUE THREAD

**Issue by aurelien-reeves-scalingo** [NextINpact/Next#224]
J'ai tenté d'offrir un article. Malgré la petite popup "Le lien a été copié dans le presse-papier", ce n'était pas le cas.

J'utilises Opera sous Ubuntu

**Comment by Opwi** [comment]
Hello,

Nous sommes au courant, ca devrait être bientôt fixé 😁
