### ISSUE TITLE
Facture pour abonnement

### ISSUE THREAD

**Issue by Mimoza** [NextINpact/Next#225]
Bonjour,
Ça serait utile de pouvoir génerer une facture pour l’abonnement. En tant qu’indep j’en ai besoin pour ma compta.
J’ai déjà envoyé un mail pour l’obtenir, mais pouvoir l’avoir automatiquement dans son  espace abonné serait un plus.

Merci d’avance

**Comment by Opwi** [comment]
Duplicate to #314
