### ISSUE TITLE
[Feature request] Recherche par auteur

### ISSUE THREAD

**Issue by lcheylus** [NextINpact/Next#227]
Dans l'ancienne version de NextInpact v7, dans le champ de Recherche, il était possible de faire une recherche par auteur.

Très pratique lorsqu'on s'intéresse à un sujet en particulier pour retrouver d'anciens articles. J'utilisais particulièrement cette recherche pour retrouver les articles de Manhack sur le thème "Sécurité" / "Cyber-surveillance".

Merci par avance pour réflexion/prise en compte de ma demande.

**Comment by Opwi** [comment]
Bonjour,

Nous avons implémenté cette fonctionnalité !
