### ISSUE TITLE
Résultats de recherche incomplets

### ISSUE THREAD

**Issue by lcheylus** [NextINpact/Next#228]
Etant donné que la recherche par auteur n'est pas disponible (voir #227), j'utilise le champ de recherche en indiquant un nom d'auteur pour retrouver ses anciens articles.

J'ai remarqué que les résultats retournés sont incomplets. Par exemple, si je cherche les articles de Manhack  https://next.ink/?s=Manach, la **liste d'articles retournée par la recherche est (très) incomplète** => 36 résultats uniquement !

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement :smile:.
