### ISSUE TITLE
URL du Brief avec date

### ISSUE THREAD

**Issue by lcheylus** [NextINpact/Next#229]
Pour faire suite à ma demande d'évolution #226.

Actuellement, **l'adresse/URL du Brief quotidien n'utilise pas la date mais un mix des titres des articles associés**. Il devient alors impossible de retrouver l'adresse/URL de la page d'un ancien Brief que l'on souhaiterait consulter.

Proposition : modifier la génération de l'URL du Brief en utilisant la date de publication.

**Comment by TroudhuK** [comment]
De manière générale c'est pénible de ne pas pouvoir F5 https://next.ink/ (la page d'accueil) parce qu'elle est complétée automatiquement de paramètres figeant les dates des infos présentées (ex : https://next.ink/?begin=2023-12-03&end=2023-12-10). Essayez de mettre le site en marque-page sans l'éditer pour voir...

**Comment by lcheylus** [comment]
Cette demande me semble maintenant disponible. L'URL du Brief quotidien contient bien la date. Par exemple pour celui du 29 juin 2024 => https://next.ink/briefs/le-brief-du-28-juin-2024/
