### ISSUE TITLE
[Migration] SEO

### ISSUE THREAD

**Issue by NiCr42** [NextINpact/Next#23]
Pour une migration réussie, il ne faut pas négliger les opérations SEO pour passer le maximum de jus SEO de l'ancien site dont la réputation est importante auprès des moteurs de recherches alors que le nouveau est pour le moment un petit nouveau dont la réputation reste à faire (mais deviendra grand).
De plus, vous n'avez pas choisi la facilité avec un changement de nom/marque *Next* déjà utilisé dans les domaines du developpement (nextjs), de la mode et les vêtements, de le monde du cinéma et des séries; mais également le fait d'utliser un tld en ".ink" (moins aisé à placer). Le challenge pour hisser la nouvelle marque va être un combat de longue haleine.
Une idée en l'air : éviter l'indexation du site *beta* par les moteurs de recherches pour éviter que le domaine ne parte avec un handicap pour "contenu dupliqué" ou rebasculer "beta.next.ink" vers "(www.)next.ink" (sans le www, c'est plus court aussi :)) mais il faut mettre en place des urls canoniques de "next INpact" vers "next" (d'un point de vue lecteur, le bandeau rouge d'avertissement "en beta" peut suffir et le sous domaine "beta" n'est pas si important).

Bref, la migration SEO est a ne pas négliger et à mettre en place au plus tôt afin de conserver vos lecteurs préférés mais également attirer d'en attirer de nouveaux.

Bon courage et bonne continuation à Next feat. moji.

**Comment by AIMAR-S** [comment]
D'ailleurs les liens étant totalement différents il faudra surement un plan de redirections.

https://www.nextinpact.com/article/72663/too-tixeo-oodrive-et-olvid-ambitions-suite-collaborative-securisee-et-souveraine
https://beta.next.ink/115790/too-tixeo-oodrive-et-olvid-ambitions-de-la-suite-collaborative-securisee-et-souveraine/

**Comment by n1co-dev** [comment]
> Une idée en l'air : éviter l'indexation du site beta par les moteurs de recherches pour éviter que le domaine ne parte avec un handicap pour "contenu dupliqué"

Oups désolé je viens de créer un ticket en [doublon](https://github.com/NextINpact/Next/issues/43) ^^

+1 sur  le changement de domaine - ça va pas être simple :) Même si la stratégie SEO de NXi de l'ère Teuf me paraissait discutable.  Quoi qu'il arrive - Comme le dit @NiCr42 va falloir un plan de redirection robuste. 

Mon ticket  #43  (fermé cause doublon)

> Salut la team,
> 
> Vous risquez de pourrir votre SEO avec du duplicate.
> 
> ca commence à s'indexer sur [GG](https://www.google.com/search?q=site%3Abeta.next.ink&oq=site%3Abeta.next.ink&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIGCAEQRRg60gEINTk1MGowajeoAgCwAgA&sourceid=chrome&ie=UTF-8)
> 
> Dans votre [robots.txt](https://beta.next.ink/robots.txt)
> Indiquez Disallow: / 
> Et non Disallow : Tout court
> 
> Par sécurité je mettrai aussi toutes les pages du domaine beta en noindex,nofollow
> Bon courage pour la migration.

**Comment by dragonis41** [comment]
J'ai corrigé le robot.txt pour `Disallow: /`

**Comment by NiCr42** [comment]
> J'ai corrigé le robot.txt pour `Disallow: /`

Cela risque de ne pas être suffisant. Un header HTTP ajouté directement dans la configuration du vhost du serveur HTTP (Apache/Nginx/Caddy) serait plus efficace `X-Robots-Tag: noindex, nofollow`. Ainsi, ce header sera effectif sur toutes les ressources servies par le serveur HTTP : html, xml (pour le sitemap par exemple), les images, les assets js/css et autres.

Ne pas oublier d'enlever le jour de la mise en production (tout comme la modification du robot.txt).

**Comment by Alexandre-Gliganic** [comment]
> Un header HTTP ajouté directement dans la configuration du vhost du serveur HTTP (Apache/Nginx/Caddy) serait plus efficace `X-Robots-Tag: noindex, nofollow`. 

Merci pour votre retour. Je viens d'ajouter le header dans notre config.

**Comment by Alexandre-Gliganic** [comment]
> D'ailleurs les liens étant totalement différents il faudra surement un plan de redirections.
> 
> https://www.nextinpact.com/article/72663/too-tixeo-oodrive-et-olvid-ambitions-suite-collaborative-securisee-et-souveraine https://beta.next.ink/115790/too-tixeo-oodrive-et-olvid-ambitions-de-la-suite-collaborative-securisee-et-souveraine/

Nous avons déjà des redirections actives 😄
Par exemple, si vous essayez d'aller sur l'endpoint: https://beta.next.ink/article/72663/too-tixeo-oodrive-et-olvid-ambitions-suite-collaborative-securisee-et-souveraine vous serez automatiquement redirigé vers https://beta.next.ink/115821/too-tixeo-oodrive-et-olvid-ambitions-suite-collaborative-securisee-et-souveraine/

**Comment by NiCr42** [comment]
> > D'ailleurs les liens étant totalement différents il faudra surement un plan de redirections.
> > 
> > https://www.nextinpact.com/article/72663/too-tixeo-oodrive-et-olvid-ambitions-suite-collaborative-securisee-et-souveraine https://beta.next.ink/115790/too-tixeo-oodrive-et-olvid-ambitions-de-la-suite-collaborative-securisee-et-souveraine/
> 
> Nous avons déjà des redirections actives 😄
> Par exemple, si vous essayez d'aller sur l'endpoint: 
> https://beta.next.ink/article/72663/too-tixeo-oodrive-et-olvid-ambitions-suite-collaborative-securisee-et-souveraine vous serez automatiquement redirigé vers 
> https://beta.next.ink/115821/too-tixeo-oodrive-et-olvid-ambitions-suite-collaborative-securisee-et-souveraine/

C'est une bonne nouvelle. Attention toutefois : si l'intention est d'utiliser ces chaînes de redirections pour le plan de redirections final, cela n'est pas une bonne pratique et cela va diluer le jus SEO qui va être transmis de l'URL de nextimpact vers next. Par chaîne de redirections, j'entends passer de https://www.nextinpact.com/article/72663/too-tixeo-oodrive-et-olvid-ambitions-suite-collaborative-securisee-et-souveraine
vers https://beta.next.ink/article/72663/too-tixeo-oodrive-et-olvid-ambitions-suite-collaborative-securisee-et-souveraine
vers https://beta.next.ink/115821/too-tixeo-oodrive-et-olvid-ambitions-suite-collaborative-securisee-et-souveraine/.

**Comment by Alexandre-Gliganic** [comment]
Merci des retours!
