### ISSUE TITLE
[FR] Pas de gestion des espaces insécables

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/Next#230]
(je sais pas pourquoi ça a posté le bug avant que j'ai eu le temps d'écrire quoi que ce soit)

C'est un vieux bug/feature request. Il n'y a jamais eu de gestion des espaces insécables sur NXI, quel que soit la version précédente, ou maintenant. Ça mène à ce genre de problèmes : 

![image](https://github.com/NextINpact/Next/assets/2286246/7345268d-3183-4c23-9d9b-e01fec2e7d53)
![image](https://github.com/NextINpact/Next/assets/2286246/bc1ceb36-a2a7-4ce3-b7d4-82f7d50c9c62)

Oui, je sais, ça devrait être géré par les auteurs des articles. Mais ça ne l'est ***jamais***.

Maintenant que l'on passe à Wordpress, j'ose espérer que l'installation d'un plugin dédié pour gérer ça automatiquement est possible, et que, encore mieux, ce sera fait…

**Comment by pamputt** [comment]
Il est déjà question de ce sujet dans https://github.com/NextINpact/Next/issues/60
