### ISSUE TITLE
Masquer la barre d'adresse sur mobile

### ISSUE THREAD

**Issue by JSteunou** [NextINpact/Next#231]
Quand on scroll vers le bas la barre d'adresse disparait bien sur une page d'article, mais pas sur la home. Ça fonctionnait bien partout en v7 (et c'était bien pratique !)

Toujours une histoire de mobile => gain de place :)

Android 14 / Firefox

**Comment by Opwi** [comment]
Hello,

De part le design actuel il n'est pas possible de masquer la barre d'adresse sur le mobile.

**Comment by JSteunou** [comment]
C'est bien triste :(
