### ISSUE TITLE
[Commentaire] Pas de citation pour les sous-commentaires de niveau 1

### ISSUE THREAD

**Issue by francois-dorin** [NextINpact/Next#232]
Lorsqu'on répond au premier commentaire d'un fil de discussion, le commentaire du fil n'est pas repris.

Par contre, si on répond à une réponse, on a bien le commentaire auquel on répond qui est cité.

Je ne sais pas si c'est un bogue ou si c'est le comportement voulu, mais je pense qu'il serait bien que le commentaire soit cité dans tous les cas. En effet, le mode fil de discussion étant limité à 2 niveaux, on se retrouve vite à ne pas pouvoir faire la différence.

Exemple sur la capture ci-dessous : 
- 2 est une réponse à 1
- 3 est une réponse à 2
- 4 est une réponse à 1
- 5 est une réponse à 1

Mais 2, 3, 4 et 5 sont sur le même niveau. Du coup, quand on arrive plus bas dans le fil de discussion, on ne sait pas à quel message on répond (sauf à savoir qu'il n'y a pas de citation pour les réponses de niveau 1 au commentaire à l'origine du fil de discussion)

![Commentaire](https://github.com/NextINpact/Next/assets/36440144/cc25d0bb-9058-48da-8990-29bb49545c92)

**Comment by francois-dorin** [comment]
Pour info, vu sur https://github.com/francois-dorin/previnpact-extension/issues/8. Merci à SebGF.

**Comment by Opwi** [comment]
Bonjour,

Le problème n'est plus d'actualité avec la version actuelle des commentaires.
