### ISSUE TITLE
Impossible de commenter si on n'est pas abonné.

### ISSUE THREAD

**Issue by Fafaille** [NextINpact/Next#233]
Bonjour,
Quand on commente alors que l'on n'est pas abonné mais inscrit (personnellement depuis 9ans), on ne peut pas commenter. Au clic sur répondre, il ne se passe rien.
L'appel réseau renvoi "Vous n'avez pas les droits", mais rien ne s'affiche pour l'utilisateur.
Bonne journée.

**Comment by theoldscudo** [comment]
à rapprocher de 
https://github.com/NextINpact/Next/issues/139

**Comment by dragonis41** [comment]
Hello @Fafaille désolé pour le temps d'attente, peux-tu réessayer et me dire si tu peux maintenant commenter ? :)

**Comment by Fafaille** [comment]
Bonjour,Il a fallu quelques clics (3 ou 4), mais c'est passé.Le 12 déc. 2023 12:35, Guillaume Pinon ***@***.***> a écrit :
Hello @Fafaille désolé pour le temps d'attente, peux-tu réessayer et me dire si tu peux maintenant commenter ? :)

**Comment by hezirem** [comment]
PS: [Nous observons](https://forum.nextinpact.com/topic/190228-impossible-de-commenter-en-non-abonn%C3%A9/?do=findComment&comment=2943907) (Mais on peut pas s'inscrire donc impossible de répondre)

**Comment by dragonis41** [comment]
A priori il n'y a pas l'air d'y avoir encore des soucis, je ferme donc cette issue. N'hésitez pas à la rouvrir si le problème est toujours présent
