### ISSUE TITLE
[RSS] Mettre le lien des articles du brief sur leur titre dans le flux RSS

### ISSUE THREAD

**Issue by ldidry** [NextINpact/Next#234]
Quand on utilise le flux RSS avec brief condensé, il n’y a pas de lien vers chaque article du brief, ce qui, pour partager un article, oblige à aller sur le brief puis de récupérer le lien.

Il faudrait mettre le lien vers chaque article du brief sur leur titre (ou éventuellement à la fin de l’article), siouplaît :pray:

**Comment by dragonis41** [comment]
J'intègre le lien dans le titre :)

**Comment by ldidry** [comment]
:kissing_heart:

**Comment by dragonis41** [comment]
C'est en prod ;)
