### ISSUE TITLE
[BUG] Lors d'une recherche, les résultats sont parfois dans un ordre aléatoire

### ISSUE THREAD

**Issue by dragonis41** [NextINpact/Next#235]
Par exemple : https://next.ink/?s=AMII 
L'article "Orange sanctionnée sur la fibre : l’argumentaire de l'opérateur démonté par l’Arcep" est en bas de la liste et il y a des articles de 2014 devant, et si on va sur la deuxième page, on retrouve une nouvelle fois cet article ainsi que des articles plus récents que ceux de la page précédente.

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement :smile:.
