### ISSUE TITLE
[Bug] Problème de sommaire partiellement vide

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/Next#236]
Sur l'article https://next.ink/118993/orange-sanctionnee-sur-la-fibre-largumentaire-de-loperateur-demonte-par-larcep/, il y a des erreurs sur le sommaire, notamment, des espaces vides, la zone sélectionné quand on est dans les commentaires est au milieu de l'article.

![image](https://github.com/NextINpact/Next/assets/2286246/0f887f22-80c4-4e6a-8492-bd72b4568428)

**Comment by dragonis41** [comment]
Hello ! C'est l'un des journalistes qui a mis une balise h3 vide et ça cassait la mise en page, il l'a corrigé dès qu'il l'a vu :)
