### ISSUE TITLE
Adresse mail DPO

### ISSUE THREAD

**Issue by Zulgrib** [NextINpact/Next#239]
Ce qui empêche d'accéder aux informations pour contacter le DPO.

**Comment by Zulgrib** [comment]
Ou comme indiqué dans un commentaire sur le site, où envoyer les requêtes si pas de DPO

**Comment by Dadkill** [comment]
Certes, c'est un problème qui se doit d'être corrigé pour la page des mentions légales, mais pour info, les informations du DPO se trouvent dans la page "Déontologie" qui, elle, est bien accessible.

D'ailleurs, pour l'équipe : l'adresse du DPO est toujours [dpo@nextinpact.com](mailto:dpo@nextinpact.com). Peux-être faudrait-il la changer en dpo@next.ink ?

**Comment by dragonis41** [comment]
Alors, il y a maintenant la page sur mobile. Par contre, j'ignore s'il y a une adresse dpo, pour l'instant on renvoyait tout le monde sur dev@next.ink ou support@next.ink.
Je vais voir avec l'équipe pour la création de l'adresse (qui dans tous les cas finira sur la même boite mail)

**Comment by Opwi** [comment]
Hello,

Le mail dpo a bien été ajouté au site.
