### ISSUE TITLE
Option pour réduire le bandeau du haut

### ISSUE THREAD

**Issue by Wivik** [NextINpact/Next#24]
Hello,

Sera-t-il possible d'ajouter une option pour que le bandeau du haut soit masqué par défaut ?

J'ai une préférence pour avoir la vue directe sur les deux colonnes d'actu avec le moins de distraction possible.

Merci par avance :)

(wow, ça doit être la troisième fois de ma vie que j'écris en français sur GitHub...)

**Comment by Opwi** [comment]
#159
