### ISSUE TITLE
Débordement du sous titre des vignettes sur le brief

### ISSUE THREAD

**Issue by Wivik** [NextINpact/Next#241]
La hauteur de ce `div` fixée provoque un débordement sur le corps de l'article : 

![image](https://github.com/NextINpact/Next/assets/48727868/50511d32-a78a-4b14-a392-b6507dd14f78)

![image](https://github.com/NextINpact/Next/assets/48727868/39175e19-21c6-4448-9eef-edf421740664)

Il faudrait peut-être imposer une limitation de longueur de saisie ou alors rendre la hauteur plus dynamique qu'elle ne l'est actuellement (`min-height` ?).

**Comment by dragonis41** [comment]
Dupliqué de #210
