### ISSUE TITLE
Commentaires lus

### ISSUE THREAD

**Issue by atchisson** [NextINpact/Next#242]
Actuellement, il n'y a pas de distinction entre un article où on a lu tous les commentaires, et un article où on en a lu aucun.

Sur la V7, il y avait un petit `42 · 0` lorsqu'on était à jour, est ce que ça serait possible de prévoir un équivalent ?

J'en profite pour un deuxième problème : 
Le nombre de commentaires non lus ne s'affiche pas en haut de l'article

liste sur l'accueil OK : 
![image](https://github.com/NextINpact/Next/assets/41149397/7c8fdfab-beff-487a-a0f9-d9b9d83b16fa)

et quand on clique sur l'article, ça ne s'affiche plus : 
![image](https://github.com/NextINpact/Next/assets/41149397/518f5723-776d-4c97-9d73-29ed69d93714)

**Comment by atchisson** [comment]
Je viens de remarquer sur mes screenshots que le tag "Web" s'affiche comme "Internet" ou "Web" en fonction de la page, je sais pas si c'est voulu 😄

**Comment by pipoupoip** [comment]
> Je viens de remarquer sur mes screenshots que le tag "Web" s'affiche comme "Internet" ou "Web" en fonction de la page, je sais pas si c'est voulu 😄

Hello,
C'est voulu, on a mis des noms de catégories plus courts quand l'espace est limité :)
