### ISSUE TITLE
Couleur des liens des commentaires en mode sombre sur mobile

### ISSUE THREAD

**Issue by piwi82** [NextINpact/Next#243]
Les liens des commentaires en mode sombre sur mobile (DuckDuckGo sur iOS dans mon cas) s'affichent d'un vilain bleu tout moche (`#0000FF`) sur un fond sombre, ce qui les rends très peu lisibles comme le montre l'image ci-dessous.
Y a des devs dans l'coing pour sauver le mode sombre ? 🤓

![image](https://github.com/NextINpact/Next/assets/1122383/89383f0e-32e4-4233-8083-2adbba8ca1e4)

**Comment by pipoupoip** [comment]
On va s'en occuper :) 
Mais je ferme ici. C'est le doublon de #189
