### ISSUE TITLE
Le lien "copier le lien" dans les articles du Brief copie le mauvais lien

### ISSUE THREAD

**Issue by pymaldebaran** [NextINpact/Next#244]
Lorsque l'on est sur l'interface du Brief (par exemple https://next.ink/briefs/lebrief-cloud-europeen-osiris-rex-a-frolee-la-catastrophe-cpu-amd-ryzen-8040/ ) sur chaque news figure en haut et en bas de la news un lien "copier le lien" avec la petite icone "maillon de chaine". Ce lien permet quand on clique dessus d'avoir dans le presse-papier le lien de la news.

**Problème** : il copie le lien de la page du brief, pas celle de la news elle-même.

**Note** : si on va sur la page de la news elle-même (par exemple https://next.ink/brief_article/echantillons-dosiris-rex-la-nasa-nest-pas-passee-loin-de-la-catastrophe/ ) il y a aussi ces liens mais cette fois-ci ils fonctionnent bien. Mon hypothèse (je n'ai pas été voir le code) c'est que ces lien se contente de mettre dans le presse-papier l'url de la page courante... ce qui ne marche pas lorqu'on est sur la page du Brief du jour ou chaque news devrait avoir son propre lien vers sa page propre.

**Comment by pipoupoip** [comment]
J'ajoute un second problème pour référence de notre côté : les mails de remontée d'erreurs (type orthographe) présentent également le mauvais lien.

**Comment by pipoupoip** [comment]
Et je rajoute les partages également qui sont mauvais. 
Le correctif sort bientôt :)

**Comment by pipoupoip** [comment]
Les trois soucis sont bien corrigés :)
