### ISSUE TITLE
impossible de se connecter au site et impossible de changer de mot de passe

### ISSUE THREAD

**Issue by JohnJohn45** [NextINpact/Next#245]
Bonjour,

quand j'essaie de changer mon mot de passe j’obtiens l'erreur suivante :

![Capture d'écran 2023-12-09 181044](https://github.com/NextINpact/Next/assets/26327298/208c8139-ffcf-4401-be90-cd72a2e8959f)

**Comment by hezirel** [comment]
Salut,

C'est réglé, tu peut faire ta demande de reset

**Comment by hezirem** [comment]
Salut,

C'est réglé, tu peut refaire ta demande

**Comment by JohnJohn45** [comment]
> Salut,
> 
> C'est réglé, tu peut refaire ta demande

Désolé de revenir sur le sujet mais effectivement si la changement de mot de passe est maintenant effectué "avec succès" , une fois le mot de passe changé il n'est toujours impossible de me connecter. J'ai le message d'erreur : 
 "Le nom d'utilisateur / l'email ou le mot de passe saisis sont incorrects.".

**Comment by hezirem** [comment]
> > Salut,
> > C'est réglé, tu peut refaire ta demande
> 
> Désolé de revenir sur le sujet mais effectivement si la changement de mot de passe est maintenant effectué "avec succès" , une fois le mot de passe changé il n'est toujours impossible de me connecter. J'ai le message d'erreur : "Le nom d'utilisateur / l'email ou le mot de passe saisis sont incorrects.".

Re,

Navré de ces va et viens, on a quelques soucis avec la userbase qu'on a importé depuis l'ancienne stack (charactères non ascii, doublons, etc, ...)

J'ai push de nouveau changements, peut tu réessayer ?
Et le cas échéant je t'enverrais un identifiant discord pour qu'on pinpoint le problème

**Comment by JohnJohn45** [comment]
> > > Salut,
> > > C'est réglé, tu peut refaire ta demande
> > 
> > 
> > Désolé de revenir sur le sujet mais effectivement si la changement de mot de passe est maintenant effectué "avec succès" , une fois le mot de passe changé il n'est toujours impossible de me connecter. J'ai le message d'erreur : "Le nom d'utilisateur / l'email ou le mot de passe saisis sont incorrects.".
> 
> Re,
> 
> Navré de ces va et viens, on a quelques soucis avec la userbase qu'on a importé depuis l'ancienne stack (charactères non ascii, doublons, etc, ...)
> 
> J'ai push de nouveau changements, peut tu réessayer ? Et le cas échéant je t'enverrais un identifiant discord pour qu'on pinpoint le problème

J'ai fini par trouvé le problème, et j'ai ouvert une nouvelle issue correspondant au bug ici :
https://github.com/NextINpact/Next/issues/248

**Comment by JohnJohn45** [comment]
C'est bon avec les modifs la connexion fonctionne avec pseudo ou email. Merci !

edit : j'ai clôturé l'autre issue.
