### ISSUE TITLE
Impossible de commenter ?

### ISSUE THREAD

**Issue by Wivik** [NextINpact/Next#25]
Hello, 

La saisie de commentaire est-elle désactivée ? Car la section "quelque chose à dire" ne réagit pas.

Question également : quelles seront les options de mise à forme ? Markdown sera-t-il toujours disponible ?

Merci par avance :)

**Comment by Cqoicebordel** [comment]
Confirmé. Mais ça fonctionnait y'a quelques heures (ou hier), donc ça doit juste être temporaire, ils doivent bosser dessus.

**Comment by MosieurClement** [comment]
On a un petit souci avec JS (maudit soit-il 😝) suite à la dernière mise à jour, on va remettre ça au plus vite

**Comment by Jenssaibe** [comment]
Idem ici sur FF 118.0.2
