### ISSUE TITLE
UI : bouton réagir mal aligné verticalement

### ISSUE THREAD

**Issue by francois-dorin** [NextINpact/Next#250]
Le bouton réagir au niveau des commentaires est mal aligné avec le bouton répondre et le bouton éditer. Le texte est plus bas
![réagir](https://github.com/NextINpact/Next/assets/36440144/8e7accc9-775b-4717-bb3e-feca37b4ec9d)

**Comment by pipoupoip** [comment]
Il est maintenant parfaitement aligné :)
