### ISSUE TITLE
Commenter depuis la fediverse

### ISSUE THREAD

**Issue by tclavier** [NextINpact/Next#251]
Le rêve serait de voir les files de discussions directement dans mon client mastodon. Et de pouvoir y repondre depuis mon client préféré.

La première itération de cette feature de rêve, c'est que next ai un compte masto avec au moins un poste par article.

**Comment by Zulgrib** [comment]
Comment tu limite aux abonnés si ils ouvrent ça ?

**Comment by tclavier** [comment]
Pourquoi limiter les échanges aux abonnés ? Si en plus ça pouvait donner envie aux non abonnés de payer pour soutenir le projet ce serait un plus ;-)

Pour ne publier sur le site que les commentaires des abonnés j'imagine que rajouter son compte masto dans son profile doit suffire à filtrer les commentaires qui ne viennent que des abonnés.

Pour garantir la modération, là il faut un truc en plus soit une liste blanche soit une liste noir des messages à afficher.

**Comment by francois-dorin** [comment]
> Pourquoi limiter les échanges aux abonnés ? Si en plus ça pouvait donner envie aux non abonnés de payer pour soutenir le projet ce serait un plus ;-)

Parce que c'est la direction que souhaite prendre Next. Entre autre, une manière de faciliter la modération et de limiter le spam. Pour pouvoir commenter il faut, au choix :
- être abonné
- avoir un compte depuis au moins 3 ans.

> Pour ne publier sur le site que les commentaires des abonnés j'imagine que rajouter son compte masto dans son profile doit suffire à filtrer les commentaires qui ne viennent que des abonnés.

Difficile à mettre en place. Que se passe-t-il si un abonné répond à un non-abonné ? La réponse de l'abonné "remonte" sur Next, mais pas le message auquel il répond ? 

De plus, d'un point de vue légal, Next est responsable des commentaires sous ses articles. Le fait d'ouvrir les commentaires à d'autres source ne ferait que compliquer (et même rendre impossible), la modération.

**Comment by tclavier** [comment]
Ok, très bien, les échanges sont réservés aux abonnés.

Pour continuer à creuser l'option, et si Next avait son propre serveur Masto avec sa modération ? chaque compte aurait un compte masto automatique ou un compte perso.

**Comment by Dadkill** [comment]
Un peu de réalisme : l'idée demande un temps de développement énorme pour une utilisation à la marge de 2-3 de nos lecteurs barbus.

C'est clairement quelque chose qui ne verra pas le jour.

**Comment by tclavier** [comment]
Je comprends ta conviction, j'en ai une autre.

Si un dev veut clore avec le label "never be done", go.

**Comment by Dadkill** [comment]
Pour le coup, c'est pas une conviction, c'est du bon sens. Il y a des choses que j'aimerais aussi voir sur Next, mais dont je sais que l'utilisation ne dépasserait pas les 1% des utilisateurs. J'ai beau en avoir envie, je sais que ce ne sera pas fait.

M'enfin, j'imagine que les devs se poseront en neutralité pour ne froisser personne, à grand coup de "il ne faut jamais dire jamais", laissant cette demande ouverte ad vitam eternam. Wait & see.
