### ISSUE TITLE
Perte des réactions après avoir posté un commentaire

### ISSUE THREAD

**Issue by francois-dorin** [NextINpact/Next#253]
Rien de bien méchant, mais quand on écrit un commentaire, toutes les réactions aux commentaires existants disparaissent. Il faut recharger la page pour les voir à nouveau.

**Comment by psychopatt** [comment]
De même - et probablement lié donc je n'ouvre pas une autre issue - on ne peut plus non plus ajouter de réaction après avoir posté un commentaire : le bouton "réagir"... ne réagit plus.

**Comment by pipoupoip** [comment]
Effectivement à l'envoi d'un commentaire on recharge la partie commentaires de la page. Mais pas mal de boutons étaient "configurés" uniquement au chargement de la page complète. 
C'est corrigé :)
