### ISSUE TITLE
Le centre de notifications reste non lu

### ISSUE THREAD

**Issue by Wivik** [NextINpact/Next#255]
J'ai beau le rouvrir et cliquer les liens, les notifications restent en non lues.

![image](https://github.com/NextINpact/Next/assets/48727868/55caaf42-4bff-4fc2-9164-6e93f7fa0cba)

**Comment by Wivik** [comment]
J'ajoute un autre point, l'ordre devrait être inversé pour afficher les plus récentes d'abord.

**Comment by gnomelibre** [comment]
Pareil de mon côté. J'ai beau cliquer, ça fait plus d'une semaine que ça me sort qu'on a répondu à l'un de mes commentaires. Par contre, ça ne me le fait que pour le dernier commentaire, les précédents ont bien été considérés comme ayant été lus.

**Comment by AIMAR-S** [comment]
Bonjour,
Après quelques tests je pense avoir trouvé pourquoi.

Le code JS suivant associé au click pour faire disparaître la notification :
```
    $('.mark-as-read').click(function() {
        var notification_id = $(this).data('id'); 
        $.ajax({
            url: 'https://next.ink/wp-admin/admin-ajax.php',
            type: 'POST',
            data: {
                'action': 'mark_as_read',
                'notification_id': notification_id
            },
            success: function(data) {
                closeNotificationDrawer();
                /* TODO: update notification count and reload*/
            },
            error: function(errorThrown) {
            }
        });
    });
```
Est joué au moment du click, hors il est sur une balise `<a>` qui renvois aussi sur la page du commentaire.

Ici je pense que la navigation est déclenchée avant l'évènement de click ( besoin d'un stopPropagation ? ) ce qui fait que le JS d'au dessus n'a pas le temps d'être joué ? L'ajax est coupé par le nav ? Faudrait que je regarde comment se comporte l'inspecteur réseau.

Par contre si l'on se trouve sur la page du commentaire comme le lien est interprété comme une ancre dans la page il n'y a pas navigation et le JS s’exécute et donc le message est marqué comme lu.

Après l'autre soucis c'est qu'il faudrait que cela nettoie la zone de notification ( décrémenter le compteur, modifier la class du commentaire pour desactiver visuellement et ne plus déclencher le JS )

Voilà mon analyse :)

**Comment by Albirew** [comment]
exact!
après test en virant le href, en cliquant sur le lien, puis en rafraîchissant la page, ça enlève bien la notification =)

**Comment by xavierforestier** [comment]
Pourriez-vous prioriser ce point, ça rend inutilisable les notifications de commentaires...

**Comment by mickaelperrier** [comment]
Même problème, qui commence à durer, ça enlève presque tout l'intérêt des notifs ...

**Comment by Albirew** [comment]
vous pouvez toujours enlever chaque notification en cliquant sur une notification, puis en re-cliquant dessus une fois sur la page...

**Comment by Wivik** [comment]
Pour ma part j'ai observé qu'elles ne se mettent pas comme lu lorsqu'on ouvre le lien avec le clic milieu dans un nouvel onglet.

Suggestion : mettre un bouton "marquer tout comme lu"

**Comment by AIMAR-S** [comment]
Vu le bug pour l'instant elles ne se mettrons comme lues que  lorsque l'on click sur la notif quand on est sur la page concernée par le nouveau commentaire.

Donc comme le conseille @Albirew il faut cliquer une 2ème fois sur la notif quand on est arrivé sur la page concernée.

**Comment by darkweizer** [comment]
Merci de l'astuce ! Je n'en pouvais plus d'avoir ce compteur qui ne représenté plus rien. En attendant une correction 🙂

**Comment by Nozalys** [comment]
Pour ma part, l'astuce ne fonctionne qu'une fois après avoir en + rechargé tous les onglets ouverts de Next.

**Comment by darkweizer** [comment]
> Pour ma part, l'astuce ne fonctionne qu'une fois après avoir en + rechargé tous les onglets ouverts de Next.

Elle reste active après le refresh oui. Mais si vous allez ensuite sur une autre page (la page d'accueil par exemple), là la notif non lu disparait 🙂

**Comment by tonyriviere88** [comment]
Je plussoie l'ajout d'un "Marquer tout comme lu".

**Comment by AIMAR-S** [comment]
Bonjour,

Il me semble que c'est réctifié non ?

**Comment by darkweizer** [comment]
Je confirme ! Je viens de tester et j'ai bien la notif qui disparait (même si je ne suis pas sur la page correspondant à la notif)
👍

**Comment by remip74** [comment]
idem on a plusieurs retour sur le forum confirmant que c'est résolu.

**Comment by Nozalys** [comment]
Je confirme pour moi aussi, c'est résolu.

**Comment by tonyriviere88** [comment]
Est ce que le fix ne concerne que les utilisateurs de Chrome et dérivés ?
Je ne constate pas d'amélioration sous Firefox Android. Je dois appuyer une deuxième fois sur la notification quand je suis sur la page pointée par la notif pour qu'elle passe en lue.

**Comment by darkweizer** [comment]
> Est ce que le fix ne concerne que les utilisateurs de Chrome et dérivés ? Je ne constate pas d'amélioration sous Firefox Android. Je dois appuyer une deuxième fois sur la notification quand je suis sur la page pointée par la notif pour qu'elle passe en lue.

Sous Firefox desktop, le correctif fonctionne ! Je n'utilise pas Firefox Android pour ma part
