### ISSUE TITLE
[Réaction] Limiter le nombre de requêtes

### ISSUE THREAD

**Issue by francois-dorin** [NextINpact/Next#259]
Actuellement, il y a 1 requête par commentaire pour déterminer les réactions à ce commentaire.

Pour des articles avec de nombreux commentaires (comme les poings dev), ça fait énormément de requêtes, et allonge la durée de chargement de la page.

Je pense qu'il serait bien que les réactions soient chargées en même temps que les commentaires côté serveur. Ou alors faire une requête qui permette de récupérer l'ensemble des réactions de tous les commentaires pour un article donné.

**Comment by pipoupoip** [comment]
Et hop, une requête pour toutes les réactions :)
