### ISSUE TITLE
[Bug] Jour en double quand on fait "semaine précédente/suivante"

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/Next#26]
Actuellement sur la page d'accueil, il y a les articles du 19 au 12 inclus. Si on clique sur "semaine précédente", ça affiche les articles du 12 au 5 inclus.

Il y a donc deux fois le 12, ce qui peut être troublant quand on remonte son historique pour rattraper les articles loupés (et qui ne correspond a _aucun_ autre exemple de fonctionnement de page précédente/suivante).

**Comment by matsala** [comment]
Idem sur tel. Journées affichées en double lors du chargement des anciens articles en bas de page.
La plupart du temps, mais pas tout le temps ...
![Screenshot_2023-12-01-09-18-58-892_com android chrome](https://github.com/NextINpact/Next/assets/10086789/d34caf54-4cc7-4e78-ae14-87bed48e9873)

**Comment by pipoupoip** [comment]
Hey mais c'est corrigé, ça.
on devrait passer plus souvent sur les anciennes issues github ^^'

**Comment by matsala** [comment]
Bof ... c'est toujours pareille :p
![Screenshot_2023-12-12-18-24-06-541_org mozilla firefox](https://github.com/NextINpact/Next/assets/10086789/97402a30-de2a-42b6-8abe-86940749b65f)

**Comment by matsala** [comment]
Moi j'ai toujours le même comportement ... :p
![Screenshot_2023-12-12-18-27-51-100_org mozilla firefox](https://github.com/NextINpact/Next/assets/10086789/c5621d39-1cc8-493c-8341-f60f71c08fee)

**Comment by Dadkill** [comment]
Je confirme, le problème est toujours présent @pipoupoip

![Screenshot_2023-12-12-18-54-32-73_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/NextINpact/Next/assets/22544947/5b34141b-7f29-479f-b523-2f6016f7324e)
