### ISSUE TITLE
les flêches de navigation entre les commentaires sont toutes cassées

### ISSUE THREAD

**Issue by Albirew** [NextINpact/Next#261]
les pauvres...
Quand on clique sur les flêches, une erreur s'affiche dans la console:
```
Uncaught TypeError: unreadComments[unreadIndex] is undefined
    handleNavigationLess https://next.ink/brief_article/meteo-data-gouv-ouvre-en-beta/:5689
    onclick https://next.ink/brief_article/meteo-data-gouv-ouvre-en-beta/:1
```
Certainement lié au fait que le compteur qui est avec affiche 0 (malgré qu'il y ait plus de 7 commentaires)

*Firefox 120 sur LMDE et sur windows10, cache vidé, mais je pense pas que ce soit un souci coté client*

**Comment by francois-dorin** [comment]
Peut être lié à #205

**Comment by pipoupoip** [comment]
Les boutons cliquables mêmes quand ils n'avaient aucun effet ne sont plus. 
Ils sont maintenant désactivés s'il n'y a pas de nouveaux commentaires à lire.
Reste à voir si dans ce cas on les laisse sur la page, désactivés, ou pas.
