### ISSUE TITLE
La liste de commentaires se fait déborder par une balise a (spécifique à un seul brief?)

### ISSUE THREAD

**Issue by Albirew** [NextINpact/Next#262]
Sur la page du brief concernant météo data gouv, la mise en page des commentaire part en couille.
En regardant de plus près, il semble qu'une balise `a` sauvage est apparue, mais qu'aucun maitre pokémon n'a réussi à l'attraper =)

![Sans titre](https://github.com/NextINpact/Next/assets/2805161/e804c99c-bfa4-4806-9ca6-6cd0d6ea4531)

*Firefox 120 sur LMDE et sur windows10, cache vidé, mais je pense pas que ce soit un souci coté client*

**Comment by pipoupoip** [comment]
C'est corrigé. 
On avait des ptits soucis avec le sanitize.
