### ISSUE TITLE
Balise étrange dans un article dans le flux RSS

### ISSUE THREAD

**Issue by earendilfr** [NextINpact/Next#263]
Sur cette news: https://next.ink/117036/les-abus-sur-les-noms-de-domaine-toujours-plus-nombreux-et-sophistiques/
- on a des balises étranges qui apparaisse dans le flux RSS (du genre `[caption...`)
- dans la news sur le site web, quand on regarde sur mobile, les images font n'importe quoi avec la mise en page...

**Comment by Opwi** [comment]
Hello,

Pouvez-vous nous donner plus de détails? Et avez vous eu le problème sur d'autres articles?

**Comment by earendilfr** [comment]
> Hello,
> 
> Pouvez-vous nous donner plus de détails? Et avez vous eu le problème sur d'autres articles?

Malheureusement, je n'ai plus le flux dans mon cache...
Et je n'ai pas rencontré ce problème sur un autre article.

Si je vois de nouveau ce bug, j'essayerai de rouvrir avec un screenshot du bug et, éventuellement, la source...
