### ISSUE TITLE
Réaction à ses propres commentaires

### ISSUE THREAD

**Issue by francois-dorin** [NextINpact/Next#265]
Pas un gros bogue, mais on peut "réagir" à ses propres commentaires.

"Je m'aime" ❤️

**Comment by pipoupoip** [comment]
Alors une fois n'est pas coutume, ce n'est vraiment pas un bug, c'est une feature. 
Déjà parce que les gens ont bien le droit de s'aimer :) 

Et puis ça peut aider à donner le ton d'un commentaire s'il y a déjà une réaction en dessous.

**Comment by francois-dorin** [comment]
Bon ben je m'aime alors :) Si c'est une feature, faut en profiter !!!
