### ISSUE TITLE
Page renouvellement abonnement inaccessible

### ISSUE THREAD

**Issue by higoodtogo** [NextINpact/Next#269]
ERR_FAILED lorsque l'on tente d'accéder à la page pour renouveler l'abonnement depuis son profil.
https://next.ink/pay/?package=monthly

Testé depuis Android sur Brave et Chrome:

Ce site est inaccessible

Il se peut que la page Web à l'adresse https://next.ink/pay/?package=monthly soit temporairement inaccessible ou qu'elle ait été déplacée de façon permanente à une autre adresse Web.

ERR_FAILED

**Comment by hezirem** [comment]
Bonjour,

Nous empêchons les gens de se réabonner si une commande existe déjà pour eux, il semble que ton abonnement précédent résilié récemment était encore présent dans la DB, ce qui provoquait une erreur du formulaire de paiement

J'ai corrigé ton entrée en db tu devrais pouvoir t'abonner,

Merci de nous avoir fait remonter cette erreur

**Comment by higoodtogo** [comment]
Parfait. Le formulaire de renouvellement est de nouveau accessible pour moi mtn.
Merci.
