### ISSUE TITLE
[Feat] URL unique pour chaque page possible sur la home

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/Next#27]
Sur la page d'accueil, quand on clique sur "semaine précédente/suivante", l'URL ne change pas, ce qui fait que si y'a un F5 qui passe par hasard (ou si le navigateur "endors" la page, au réveil, la page ne sera pas la même que celle qu'on aura laissé (on se retrouve avec la page d'accueil neuve, comme si on venait d'arriver).

Il faut que l'état de la page subsiste après un reboot de l'ordi. Et soit même bookmarkable.

Je propose donc que chaque clic sur "semaine précédente/suivante" modifie l'URL pour ajouter/modifier un paramètre du style "?vue=2023w42" (semaine n°42 de l'année 2023).  
Ça pourrait aussi potentiellement être ajouté pour le datePicker du #Brief, pour être sûr de retrouver _exactement_ la même page, mais le #Brief étant dans un sous-bloc à part, ça peut se discuter.

(Perso, je considère ça comme un bug, mais je l'ai mis en feature parce que je sais que je suis un extrémiste ;) )

**Comment by pipoupoip** [comment]
et c'est tout à fait fait :)

**Comment by Cqoicebordel** [comment]
Ca fonctionne, pour le brief aussi, et c'est éditable à la main, et ça prend des valeurs plus larges que prévues, c'est parfait !  
(j'ai chargé une année d'articles en test rapide. Ma machine a eu plus de mal que les serveurs. Chapo ! Par contre, pourrait être une source de DoS, un F5 rapide et régulier sur une page contenant tous les articles… Bref, à surveiller :) )
