### ISSUE TITLE
Etendre la taille du champ de saisie d'un commentaire

### ISSUE THREAD

**Issue by Wivik** [NextINpact/Next#271]
Le champ de saisie des commentaires a très bien évolué, mais pouvez-vous éviter de bloquer l'affichage de la poignée permettant d'étendre la taille du champ svp ? Il fait la taille d'un timbre poste ce qui est désagréable pour la relecture.

![image](https://github.com/NextINpact/Next/assets/48727868/3e34755f-91e6-4717-9081-8938ce0b1622)

![image](https://github.com/NextINpact/Next/assets/48727868/0e7a653b-a378-4f19-b073-c0b53c486bb9)

Attendu : 

![image](https://github.com/NextINpact/Next/assets/48727868/f59e5441-9907-49df-9e0e-edeaab177732)

**Comment by pipoupoip** [comment]
Hello, 

Je voulais râler et dire que "oui mais c'est pas beau" puis j'ai vu que dans le champ de texte où j'écris actuellement, il y a une poignée, je vais donc me taire et rétablir la poignée sur Next ^^

**Comment by Wivik** [comment]
Pour moi, la praticité doit primer sur l'esthétique. Un beau site inutilisable ne sert à rien ;) 

D'une manière générale, je suis souvent agacé par le fait que les champs de saisie texte soient de la taille d'un timbre poste. Si la saisie était limitée en caractères cela aurait du sens (comme sur Mastodon). A défaut, non, il faut laisser cette possibilité d'étendre le champ de saisie.

**Comment by AIMAR-S** [comment]
La solution parfois c'est que le champ change automatiquement de hauteur /row au fur et à mesure qu'on y ajoute des lignes

Cela permet de ne pas avoir à faire apparaître la poignée.

Après, la poignée c'est natif, le décompte des sauts de ligne c'est du JS ( puis différents OS différents sauts de ligne... )

**Comment by Wivik** [comment]
> Après, la poignée c'est natif, le décompte des sauts de ligne c'est du JS ( puis différents OS différents sauts de ligne... )

Pour moi, tout ce qui peut éviter ceci est une bonne chose :grin: 

![image](https://github.com/NextINpact/Next/assets/48727868/3eb52123-d1b6-494e-bbe9-c2b9fb0621fb)

**Comment by AIMAR-S** [comment]
Ah bien tiens je viens de découvrir cela : https://codepen.io/flesler/pen/kdJmbw

je ne savait pas que c'était possible, après biensur faudra du JS pour envoyer ce qui est dans ce div dans la textarea, mais on ne peut pas tout avoir en full CSS !

Edit: cette version est pas mal avec peu de JS https://codepen.io/chriscoyier/pen/XWKEVLy

**Comment by Wivik** [comment]
Sans pour autant vouloir lancer un débat d'experts sans fin, surtout que me concernant je ne le suis pas sur le JS, j'ai toujours une préférence pour un usage restreint de cette techno quand des fonctionnalités natives peuvent y répondre (pour le pratiquer, on peut de nos jours faire des trucs très fonctionnels et interactifs avec du simple HTML/CSS). Ici, la poignée est native et permet de répondre au use-case d'agrandir la taille du `textarea`.

Une fonction qui étend ensuite automatiquement le champ (comme ici présent sur GitHub) est un plus intéressant également et j'y vois la valeur ajoutée, mais cela peut se faire dans un second temps je pense (surtout qu'il faut concilier desktop et mobile).

M'enfin, dans tous les cas c'est l'équipe de dev qui tranchera :dagger: 

Edit : d'ailleurs sur GitHub lorsqu'on édite, le champ reste à la taille standard et la poignée permet de l'agrandir de nouveau. Les deux sont bien complémentaires en fait :grin:

**Comment by pipoupoip** [comment]
Pour l'instant, on a remis la poignée mais j'aime bien la proposition trouvée par @AIMAR-S
