### ISSUE TITLE
[UI] La cloche du bouton de notification n'est pas centrée

### ISSUE THREAD

**Issue by Dadkill** [NextINpact/Next#273]
Puisque je n'ai vu encore aucune issue d'ouverte pour ce problème, je me permets d'initier le mouvement :

![Screenshot_2023-12-24-10-24-16-61_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/NextINpact/Next/assets/22544947/7aac4aca-37ae-460f-9dd1-8b2cfa8c6c0a)

**Comment by pipoupoip** [comment]
Elle est maintenant parfaitement alignée :)
