### ISSUE TITLE
Placer le nom du site à la fin du title plutôt qu'au début

### ISSUE THREAD

**Issue by fcalvet** [NextINpact/Next#275]
Avec plusieurs onglets ouvert sur Next réduits par le navigateur, on ne peut lire que Next, on ne peut donc pas différencier les articles.

Proposition: placer le nom du site à la fin du title permettrait d'avoir le début du titre de l'article et donc de l'identifier. 
Ça me semble standard sur les sites d'information quand ceux-ci inclut leur nom en title, de plus la favicon permet déjà d'identifier Next.

**Comment by pipoupoip** [comment]
C'est modifié. Effectivement c'est plus logique dans ce sens, même si on ne verra que rarement le " - next" à la fin vu la longueur des titres d'articles ^^
