### ISSUE TITLE
bouton "signaler une erreur" non présent sur Android

### ISSUE THREAD

**Issue by Refhi** [NextINpact/Next#277]
Dans Chrome pour Android ou Firefox, la selection d'un texte d'article ne fait pas apparaître le bouton "signaler une erreur" 

(plus ou moins lié à #274 )

**Comment by Dadkill** [comment]
Je peux me tromper, mais je pense que c'est volontaire... cette fonctionnalité lors de la sélection n'était pas disponible sur NextINpact non plus avec un mobile.

Par contre, pour info, tu peux toujours signaler une erreur depuis les trois petits points > Signaler une erreur !

**Comment by Opwi** [comment]
Bonjour,

En effet la réponse de @Dadkill est la bonne. Si vous êtes connecté (et bientôt plus besoin d'être abonné) vous pouvez signaler une erreur via les trois petits points > Signaler une erreur !

Merci du signalement :smile:.
