### ISSUE TITLE
Numérotation des commentaires non pérenne

### ISSUE THREAD

**Issue by francois-dorin** [NextINpact/Next#278]
La numérotation des commentaires peut changer dans le temps.

Je lisais l'article suivant https://next.ink/brief_article/aux-etats-unis-amazon-introduira-de-la-publicite-dans-prime-video-des-le-29-janvier/#comments quand je m'en suis aperçu : le commentaire de Wagaf (id = 2117048) est à numéro 9.5 au moment où j'écris ces lignes et a été publié à 15h16. Pourtant, un autre commentaire de Wagaf (id = 2116978) , qui apparait en dessous, publié à 6h00 du matin (donc avant) est numéroté 9.6.

Si la numérotation change, cela pose problème lorsqu'on fait référence à un commentaire précis, car le commentaire peut alors changer dans le temps !

**Comment by francois-dorin** [comment]
Comme je viens de faire un exemple sur le #145, je le colle ici

Exemple : ce lien https://next.ink/121483/zorin-os-17-toujours-aussi-soignee-la-distribution-affine-ses-performances/#comm-7.3 référence le commentaire 7.3. Commentaire de lexii.

J'ai publié un commentaire sous le 7.1 (qui est un commentaire à moi)

Le commentaire de lexii est devenu le 7.4. Le lien d'avant pointe donc vers le commentaire de max6

**Comment by Albirew** [comment]
+1
une solution serais soit de ne pas changer l'ordre des commentaires, soit d'utiliser leur ID (unique) dans la base de données (si wp le permet)...

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement :smile:.

**Comment by francois-dorin** [comment]
Merci pour la correction :D
