### ISSUE TITLE
Abonnement impossible: "Il y a eu une erreur critique sur ce site."

### ISSUE THREAD

**Issue by nicofrand** [NextINpact/Next#279]
Bonjour,

mon abonnement a expiré (je n'ai a priori pas reçu d'alertes…) et lorsque je tente de me ré-abonner, en cliquant sur "Continuer" sur la page de profil :

![image](https://github.com/NextINpact/Next/assets/3419050/a4ba792e-fb82-4a99-aa20-b4bd6719cca1)

Une erreur s'affiche :

« Il y a eu une erreur critique sur ce site. »

![image](https://github.com/NextINpact/Next/assets/3419050/3cb854fa-384d-4d8f-909c-12e0774d7722)

J'ai tenté un email à actu@next-inpact mais sans réponse depuis 15 jours.

Si jamais c'est lié au compte : « Vous êtes avec nous depuis le 6 octobre 2018 à 10h46 et 27 secondes précises ❤️  », mon email est news @ nicofrand.eu.

**Comment by hezirem** [comment]
Salut !

J'ai réglé ton problème, je t'envoie un mail pour t'expliquer :)

Tu peut te réabonner normalement

**Comment by nicofrand** [comment]
Merci !
Est-ce que je ferme le ticket ou il y a un souci sous-jacent ?

**Comment by slaffbear** [comment]
Bonjour l'équipe,

Je suis rassuré de voir que je ne suis pas le seul dans cette situation. Il me semblait être encore abonné mais que nenni. Au départ je m'étais dit que c'était un de mes extensions qui déconnait ou le réseau du boulot. Mais même en nav privée ou depuis le tel j'ai le même message d'erreur que nicorfrand.

Mail du compte concerné : arkh.fr 'at' gmail . com

Merci pour votre aide.

**Comment by hezirem** [comment]
Salut slaffbear :)

Effectivement tu es sujet à un problème similaire, lié aux abonnements précédents que vous aviez qui disposent d'un moyen de paiement approchant ou étant expiré.

Tu devras cependant légèrement prendre ton mal en patience car ces feignasses de devs ne comptent pas régler le problème avant AU MOINS le début de l'année prochaine (Y'en a qui manquent pas d'air 😡  )

/s je règle ton souci au plus vite, on connaît le problème et on s'affaire à le résoudre, Bonnes fêtes de fin d'année ❤️

**Comment by slaffbear** [comment]
> Salut slaffbear :)
> 
> Effectivement tu es sujet à un problème similaire, lié aux abonnements précédents que vous aviez qui disposent d'un moyen de paiement approchant ou étant expiré.
> 
> Tu devras cependant légèrement prendre ton mal en patience car ces feignasses de devs ne comptent pas régler le problème avant AU MOINS le début de l'année prochaine (Y'en a qui manquent pas d'air 😡 )
> 
> /s je règle ton souci au plus vite, on connaît le problème et on s'affaire à le résoudre, Bonnes fêtes de fin d'année ❤️

Top merci. En espérant que vous ayez pu profiter des fêtes aussi <3

**Comment by hezirem** [comment]
@slaffbear j'ai fix ton souci manuellement, 

Un process pour intervenir sur vos anciens abonnements sera déployé la semaine prochaine

**Comment by slaffbear** [comment]
Hello,

Tout est OK pour merci pour ton retour et tes actions.

Bon courage à toi et à l'équipe.

**Comment by n1coh** [comment]
Bonjour @hezirem , j'ai ce même souci.
Est ce que le process pour intervenir sur nos anciens abonnements a été déployé ?

**Comment by jellium** [comment]
Bonjour,
Le problème subsiste et pour ma part impossible non plus de m'abonner.
cc @hezirem

**Comment by adminlinuxfr** [comment]
Bonjour,

Pareil ici.

**Comment by webflo-dev** [comment]
Je confirme, le problème persiste.

**Comment by adminlinuxfr** [comment]
Bonjour,

J'ai pu me réabonner. Je sais pas si vous avez corrigé quelque chose mais ça a remarché pour moi.

**Comment by hezirem** [comment]
Bonjour messieurs,

Navré pour ce temps de réponse trop long, j'ai du passer un bon moment a maîtriser Pandas pour faire une correction sur les abonnements legacy

Vous devriez tous pouvoir vous abonner sans problèmes,

Je laisse ce ticket ouvert au cas ou

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement :smile:.
