### ISSUE TITLE
Liens très peu lisibles en mode sombre, voir P.J.

### ISSUE THREAD

**Issue by elsawalker** [NextINpact/Next#280]
Liens très peu lisibles en mode sombre, voir P.J.

![Screenshot 2023-12-28 at 18-42-05 ITER by drone une vidéo du réacteur à fusion nucléaire - Next](https://github.com/NextINpact/Next/assets/32288544/d44fd0c0-6697-4ee6-8e0e-964c1df83c22)

**Comment by Dadkill** [comment]
Dupliqué de #243, lui-même dupliqué de #189 😄 !

**Comment by pipoupoip** [comment]
C'est effectivement un triplon. Je ferme 
(c'est bientôt corrigé ;))
