### ISSUE TITLE
L'onglet Brief dans la sidebar n'est plus cliquable quand on est sur un article/brief

### ISSUE THREAD

**Issue by manhack** [NextINpact/Next#281]
et ce, alors que l'onglet était bien cliquable jusqu'à récemment, et que la liste des Briefs du jour figure bien dans le code source de la page, cf le  class="block-brief" juste après le <div id="test">.

La console javascript indique, quand on clique, ce message d'erreur FYI : 
Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at navTab (mobile-nav-bar.js:24:20)
    at HTMLLIElement.onclick (VM2161 :1:1)
navTab	@	mobile-nav-bar.js:24
onclick	@	VM2161 :1

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement :smile:.
