### ISSUE TITLE
Impossible de changer d'email

### ISSUE THREAD

**Issue by aurmil** [NextINpact/Next#283]
hello,

dans le profil, je modifie mon email
message de confirmation "on vous a envoyé un mail"
mail reçu
clic sur le lien
affichage du site, sans aucun message quel qu'il soit
dans le profil j'ai tjs l'ancien email

**Comment by pipoupoip** [comment]
Hello 

Je ferme car c'est un doublon de #238 
Mais on résout ça très bienôt :)

**Comment by aurmil** [comment]
OK 
En effet je n'étais pas tombé dessus car j'ai cherché "email"
