### ISSUE TITLE
Profil, page abonnement vide

### ISSUE THREAD

**Issue by aurmil** [NextINpact/Next#284]
hello,

voilà ce que j'ai d'affiché : 

![image](https://github.com/NextINpact/Next/assets/1309545/c39fb289-dbef-4ab4-97c6-2fc630c8de55)

pas d'erreur JS, ni réseau (à part matomo bloqué)

**Comment by pipoupoip** [comment]
Merci de ton retour. On est conscients du bug, il devrait être corrigé dans la semaine :)

**Comment by pipoupoip** [comment]
C'est corrigé. 
Tu me confirmes ?

**Comment by aurmil** [comment]
je confirme, merci
