### ISSUE TITLE
Casse incohérente sur les tooltips

### ISSUE THREAD

**Issue by Dadkill** [NextINpact/Next#287]
Suite à la résolution de #29, si je peux être (extrêmement) tatillon, la casse n'est pas la même sur tous les tooltips :D !

Sur les deux icônes en haut à droite des articles, on a respectivement (avec respect de la casse) : 

- "Copier le lien de l'article"
- "Plus d'options"

Pour le coup, tout est parfait !

Tandis qu'en bas, on a (avec respect de la casse) :

- "copier le lien de l'article" -> "**C**opier le lien de l'article"
- "partager sur Linkedin" -> "**P**artager sur Linked**I**n" (avec le i majuscule de LinkedIn, je le précise car pas très visible)
- "partager sur X (anciennement twitter)" -> "**P**artager sur X (anciennement **T**witter)" (pareil, t majuscule à Twitter)
- "partager sur Mastodon" -> "**P**artager sur Mastodon"
- "partager sur Facebook" -> "**P**artager sur Facebook"
- "Plus d'options" -> Niquel !

Je me suis permis de mettre en gras tous les caractères qui, à mon humble avis, devraient être en majuscule.

Je suis d'accord que ceci n'est qu'un problème de syntaxe mineur, mais qui, je trouve, a tout de même son importance sur un site journalistique :) !

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ces incohérences.

Merci du signalement :smile:.
