### ISSUE TITLE
Pas de redirection vers les articles pour les liens beta.next.ink

### ISSUE THREAD

**Issue by Dadkill** [NextINpact/Next#289]
J'ai constaté que dans les cas où on souhaiterait naviguer sur l'URL d'un article en beta.next.ink, le site redirige vers la page d'accueil https://next.ink/ et non pas sur la page de l'article, contrairement aux liens nextinpact.com qui eux, sont parfaitement fonctionnels.

Voici un exemple : 

https://beta.next.ink/117164/mozilla-propose-depot-debian-pour-firefox-nightly-changement-plus-important-quil-ny-parait/ redirige uniquement vers https://next.ink/

https://www.nextinpact.com/article/72793/mozilla-propose-depot-debian-pour-firefox-nightly-changement-plus-important-quil-ny-parait redirige bien vers https://next.ink/728/mozilla-propose-depot-debian-pour-firefox-nightly-changement-plus-important-quil-ny-parait/

Au départ, je pensais que le problème venait du fait que l'ID de l'article avait changé entre l'environnement beta et l'environnement de prod, mais ce n'est pas le cas car https://next.ink/117164/mozilla-propose-depot-debian-pour-firefox-nightly-changement-plus-important-quil-ny-parait/ redirige bien vers https://next.ink/728/mozilla-propose-depot-debian-pour-firefox-nightly-changement-plus-important-quil-ny-parait/

**Comment by dragonis41** [comment]
beta.next.ink était une beta et pas destiné à être utilisée comme adresse principale.

**Comment by Dadkill** [comment]
C'est votre choix, que je comprends difficilement car c'est une simple redirection permettant d'éviter de se retrouver sur une mauvaise page à chaque fois qu'on regarde d'anciennes issues ici ou des commentaires sur des articles pendant la période octobre/novembre.
