### ISSUE TITLE
Des libellés sur les divers boutons

### ISSUE THREAD

**Issue by Wivik** [NextINpact/Next#29]
Il serait appréciable d'avoir des libellés qui apparaissent sur ces boutons pour connaître leur signification. Je pense que ça aidera aussi à l'accessibilité du site.

![image](https://github.com/NextINpact/Next/assets/48727868/6c135cea-394d-4f58-aac3-54e96e2d9270)

**Comment by Cqoicebordel** [comment]
(et des tooltips)

**Comment by pipoupoip** [comment]
On n'a pas ça dans le figma. On va voir ce que nous propose notre DA pour que ça soit propre.

**Comment by pipoupoip** [comment]
Il y a des tooltips partout dans les partages :)
