### ISSUE TITLE
Bug affichage latéral du Brief

### ISSUE THREAD

**Issue by mazlo37** [NextINpact/Next#290]
Bonjour

je voulais vous signaler un bug d'affichage du Brief (voir ci-dessous). Il n'y a pas de séparateur blanc entre les deux derniers éléments. Il apparaît sous le dernier élément. Bug présent sous Firefox et Chrome.

![Capture d’écran du 2024-01-04 11-56-47](https://github.com/NextINpact/Next/assets/155632731/7361932a-9530-4c9c-accc-fa7ce0fa6e79)

**Comment by pipoupoip** [comment]
C'est corrigé :)
