### ISSUE TITLE
Je suis abonné mais je ne lis plus Next, voilà pourquoi

### ISSUE THREAD

**Issue by Tbaut** [NextINpact/Next#292]
Je sais que vous aviez dit que ca allait venir, mais si ce feedback peut aider à prioriser la feature... Je suis abonné depuis de nombreuses année et member depuis plus de 10 (sinon 15) ans. Je n'allais sur Nextinpact que depuis les newsletters depuis quelques années il semble. J'ai un onglet Next ouvert, mais ca n'aide pas. Je viens de me rendre compte que depuis plus de 2 mois, j'ai dû passer sur Next moins d'une dizaine de fois, quand je venais tous les jours ou presque. La raison: 
- plus de brief dans mes mails
- plus de recap des articles dans mes mails

Résultat, je ne visite plus le site :|

**Comment by dragonis41** [comment]
Dupliqué de #213

**Comment by Tbaut** [comment]
Désolé, j'avais oublié avoir ouvert une issue pour ça 😅

**Comment by dragonis41** [comment]
Pas de soucis ^^
On ne t'oublie pas, c'est toujours prévu d'intégrer la newsletter :)

**Comment by mfaure** [comment]
Merci @Tbaut pour cette issue, Je suis exactement dans le même cas d'usage. Je ne lis plus Next car je ne le reçois plus, alors qu'abonné depuis 2016. 

J'ai bien configuré les Flux RSS, mais ça ne correspond pas à ma manière de m'informer sur l'aspect pro. J'ai bien patienté depuis la migration du site. Mais j'ai la sensation de payer pour un site qui "n'arrive pas à moi". 

Je suis triste et en colère @dragonis41  Je trouve particulièrement dommage d'avoir dépriorisé le mail, outil de communication interopérable par nature. En l'état je suis au regret de dire que je ne renouvellerai pas mon abonnement.

**Comment by Tbaut** [comment]
Yes pareil, ça fait des mois que je n'ai pas été voir le site. J'y allais parfois quand j'y pensais, quand j'ai écrit cette issue, mais avec le temps je n'y vais même plus de moi même. Je ne renouvellerai pas mon abonnement non plus.

**Comment by MosieurClement** [comment]
On est en train de bosser dessus, elle devrait revenir dans le courant du mois d'avril, on a peut-être un peu sous-estimé l'attachement à newsletter, je vous présente nos excuses pour ça.

**Comment by MosieurClement** [comment]
Elles sont enfin sorties, vous pouvez vérifier si vous y êtes inscrit via votre profil ;)
