### ISSUE TITLE
Articles du brief dupliqués

### ISSUE THREAD

**Issue by bixou** [NextINpact/Next#293]
Salut l'équipe 👋 

Sur le brief d'aujourd'hui, j'ai des articles qui sont dupliqués sur la version mobile et lors du redimensionnement de la fenêtre en mode desktop.

J'ai testé sur Safari + Chrome. 

Vidéo desktop : https://github.com/NextINpact/Next/assets/4839646/902c101b-6064-4137-976a-f1b7f351f877
Capture mobile : https://github.com/NextINpact/Next/assets/4839646/c321c5f2-e651-4bd9-ac78-1f8762b2ea48

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement :smile:.
