### ISSUE TITLE
Le clic molette sur l'icône des commentaires ne fonctionne pas

### ISSUE THREAD

**Issue by Nozalys** [NextINpact/Next#294]
Sur la page d’accueil ou sur une page de Brief, lorsqu'on fait un clic molette (équivalent au ctrl+clic) sur l'icône des commentaires :

![image](https://github.com/NextINpact/Next/assets/15943230/1559a677-ea64-4ede-991a-1cc0bcc8840d)

L'action ne permet pas d'ouvrir la page de l’article vers la section des commentaires dans un nouvel onglet.
A la place, le navigateur affiche l'action par défaut :

![image](https://github.com/NextINpact/Next/assets/15943230/f3db7077-0194-4307-8517-d88178aba988)

**Comment by AIMAR-S** [comment]
Effectivement ce n'est pas un lien mais une action en javascript donc le click molette ou autre ne fait rien.

**Comment by darkweizer** [comment]
C'est ce que le ticket #155 demandé. Il a été clôturé en disant que c'était corrigé. J'ai répondu que non mais le ticket est resté clôturé 😌

**Comment by dragonis41** [comment]
Je rouvre l'autre issue :ok_hand:
