### ISSUE TITLE
Le Centre de notification ne se ferme pas automatiquement quand on clique sur le menu Profil

### ISSUE THREAD

**Issue by pamputt** [NextINpact/Next#295]
En haut à droite, si on clique sur le menu profil, puis sur le centre de notification (symbole de cloche), les notifications se superposent au menu Profil.

À l'inverse, si on clique sur la cloche en premier, ça ouvre les notifications. Puis si on clique sur le menu Profil, les notifications se ferment avant que le menu Profil ne s'ouvre.

Ce comportement n'est pas cohérent. Je m'attends à ce que le menu déjà ouvert se ferme automatiquement quand je clique sur un autre menu.

Une vidéo sera peut-être plus parlante.
[Capture vidéo du 15-01-2024 13:31:06.webm](https://github.com/NextINpact/Next/assets/11018649/4a1514bf-5393-42aa-b203-bde11ceda123)

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement 😄
