### ISSUE TITLE
Taille des images en commentaire

### ISSUE THREAD

**Issue by Zebulon-84** [NextINpact/Next#296]
Des images peuvent être insérées en commentaire avec la syntaxe Markdown, mais elles sont systématiquement affichées en pleine largeur. C'est compréhensible pour une grande image de la redimensionner pour qu'elle s'insère bien dans la page, mais les petites images deviennent très floues et bien trop grandes.

J'ai pu tricher en ajoutant un attribut HTML en jouant sur les guillemets : 
`![alt](https://url.com/pic.jpg" style="width:200px)`

Mais le plus simple serait sans doute de remplacer dans le CSS (`.comment-content img:not(.emoji-comment)`) `width:100%` par `max-width:100%`.

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement 😄
