### ISSUE TITLE
caption qui déborde sur le texte en mode mobile

### ISSUE THREAD

**Issue by tclavier** [NextINpact/Next#297]
![Screenshot_20240116-064436_Firefox](https://github.com/NextINpact/Next/assets/357257/dad1c9a4-0f4c-4b3a-a3f7-09738159e9de)

**Comment by zqysurj** [comment]
Valable aussi pour l'image en tête d'article

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement :smile:.
