### ISSUE TITLE
Le brief : indicateur non lu absent pour les jours précédents sur affichage desktop

### ISSUE THREAD

**Issue by Fafaille** [NextINpact/Next#298]
Bonjour,
En version desktop (firefox 102.8.0esr sur linux, mais je crois aussi sur windows, pas d'extension active), dans le brief, si on accède aux anciens brief (hier par exemple), il n'y a pas d'indicateur de commentaires "non lu".
Il est pourtant bien présent  sur le brief du jour, sur mobile pour tous les briefs (d'ailleurs cool de pouvoir tout voir 👍) ou pour les articles.

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement :smile:.
