### ISSUE TITLE
Politique de confidentialité

### ISSUE THREAD

**Issue by Wivik** [NextINpact/Next#30]
La politique de confidentialité et de traitement des données à caractère personnelles est absente dans le footer.

D'ailleurs je trouve le bandeau des mentions légales trop petit, quasi illisible lorsqu'on a pas des yeux bioniques.

**Comment by pipoupoip** [comment]
Effectivement, cette partie avait disparu de la page déontologie (les deux étaient rassemblés sur nextinpact.com)
Je ne sais pas encore comment ça sera présenté dans le version définitive (un bouton "déontologie et traitement des données personnelles" ou deux boutons différents)

En ce qui concerne le bandeau des mentions légales, il est prévu ainsi pour ne pas agresser l'oeil. Peut-être ne l'agresse-t-il pas assez. Je remonte ça pour voir ce qu'on en fait.

**Comment by Wivik** [comment]
> En ce qui concerne le bandeau des mentions légales, il est prévu ainsi pour ne pas agresser l'oeil. Peut-être ne l'agresse-t-il pas assez. Je remonte ça pour voir ce qu'on en fait.

J'ai passé à 12px la police et perso je trouve ça un peu plus lisible sans être trop gros.

![Peek 2023-10-20 13-37](https://github.com/NextINpact/Next/assets/48727868/f7d4d3e7-6d20-4e75-97e2-057f3f589a3c)

**Comment by pipoupoip** [comment]
Le lien pour les mentions légales est maintenant souligné pour le faire ressortir du reste du texte du footer :)
