### ISSUE TITLE
Longueur des titres sur Android en page d'accueil 

### ISSUE THREAD

**Issue by zqysurj** [NextINpact/Next#300]
Il faudrait permettre l'affichage complet des titres sur la page d'accueil Android
![Screenshot_20240121-125948_Firefox Beta](https://github.com/NextINpact/Next/assets/70756492/ce926766-2afe-4832-b503-a1a88ed57d57)
![Screenshot_20240121-130033_Firefox Beta](https://github.com/NextINpact/Next/assets/70756492/83c38491-dd9b-48c7-8f74-9de578b7b8fe)

Rajouter une troisième/quatrième ligne et/ou introduire un nombre de caractères maximum pour les titres et/ou faire disparaître le sous titre au profit du titre pourraient être de bonnes solutions

**Comment by Opwi** [comment]
Bonjour,

La décision a été prise d'avoir au maximum trois lignes pour le titre et nous avons enlevé les sous-titres sur mobile.

Merci de votre signalement.
