### ISSUE TITLE
Cliquer sur Offrir l’article ne copie pas le lien

### ISSUE THREAD

**Issue by julienlusson** [NextINpact/Next#301]
Sur iOS (à minima) cliquer sur le lien offrir l’article ne copie pas le lien.

En complément, est-ce qu’il serait possible de ne pas utiliser de javascript pour cette fonctionnalité ? (Afficher le lien et permettre de faire un copier coller du lien via les fonctions natives du navigateur)

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement 😄
