### ISSUE TITLE
Pas de date dans la liste des articles par catégorie

### ISSUE THREAD

**Issue by lcheylus** [NextINpact/Next#302]
Lorsqu'on affiche la liste des articles pour une catégorie donnée, **aucune date n'est indiquée pour chaque article**, uniquement une heure de publication.

Ce n'est pas pratique lorsqu'on parcourt une liste d'articles pour un thème donné => pas de date de publication.

Exemple pour la catégorie "Sécurité" https://next.ink/category-page/?category=s%C3%A9curit%C3%A9&id=12

**Comment by pipoupoip** [comment]
Mais si, il y a les dates sur les articles ;)
