### ISSUE TITLE
Confirmation de mail non fonctionnelle

### ISSUE THREAD

**Issue by Malizor** [NextINpact/Next#304]
Je ne sais pas si seul mon compte est affecté ou pas, mais mon email apparait comme non confirmé dans mon profil (pseudo Malizor, id=122100), alors que je l'utilise sur le site depuis des années.

Si j'envoie le mail de confirmation et que je clique sur le lien que je reçois, il n'y a pas d'erreur ni rien mais pourtant le mail apparait toujours comme non confirmé dans le profil.

**Comment by francois-dorin** [comment]
Idem pour le mail "non confirmé". Mon compte existe pourtant depuis 2017. Je subodore que c'est un effet secondaire du passage à Wordpress, et je ne trouve pas cela gênant en soi.

Par contre, je n'ai eu aucun problème de mon côté quand j'ai fais la confirmation, à 8h57 aujourd'hui (le 01/02/2024) (je ne peux pas être plus précis ^^)

**Comment by Malizor** [comment]
J'ai encore refait la procédure à l'instant et le lien de confirmation ne fait toujours rien de mon côté :(

**Comment by theoldscudo** [comment]
Constaté de mon côté et confirmé par les Dev, il faut cliquer le lien dans le même navigateur que celui sur lequel on est connecté à Next, car ils utilient la session faire le token mail
https://next.ink/126242/le-poing-dev-round-10/#comm-27.6

**Comment by pipoupoip** [comment]
On a utilisé un nonce lié à la session comme token pour valider l'adresse email. 
Du coup ça doit fonctionner si vous confirmez l'adresse depuis le même device que pour faire la demande (pendant la même session) 
Ce n'est pas un bon comportement, nous avons été un peu légers. On corrige ça aujourd'hui ou lundi. 

Edit : ah bah bien, je me fais doubler par une citation de mon propre commentaire sur Next ^^'

**Comment by theoldscudo** [comment]
après c'est peut-être pas le seul souci, les 2 autres commentaires remontent qu'il n'y a pas d'erreur affichée... moi j'avais un "session expirée"

**Comment by Malizor** [comment]
J'ai réussi à valider mon adresse mail en refaisant la procédure à l'instant.
Par contre hier je cliquais bien sur le lien depuis le même navigateur où se trouve ma session.

**Comment by GannonTdW** [comment]
Je passais par là ...
Effectivement mon adresse était aussi indiquée comme non validée, mais j'ai suivis à l'instant la procédure (clic et mail) qui fondtionne sans problème.
