### ISSUE TITLE
Liens persistants vers inpact-hardware.com

### ISSUE THREAD

**Issue by pokemaster974** [NextINpact/Next#306]
1. Aller sur un article contenant des liens (exemple : https://next.ink/3023/certification-80-plus-alimentations-pc-ce-quil-faut-savoir/)
2. Regardez si présence de légende d'image sans image (exemple : https://cdnx.inpact-hardware.com/data-prod/image/bd/2479.png)
3. Constater l'erreur

**Comment by Opwi** [comment]
Hello,

Merci du signalement! Nous venons de réparer les urls en `cdnx.inpact-hardware.com/*`.

Bonne journée à vous 😁
