### ISSUE TITLE
[RSS] Paragraphes non respectés

### ISSUE THREAD

**Issue by Otiel** [NextINpact/Next#307]
Pas sûr si c'est juste mon agrégateur de flux (Inoreader) qui pose souci ou pas, mais je n'avais pas ce problème sur la v7 et je n'ai pas ce problème pour tous mes autres flux.

Les paragraphes ne sont pas correctement affichés : à moins d'un tag de heading (`<h3>` par exemple), il n'y a aucun saut de ligne sur l'article affiché par l'agrégateur, alors que le site en affiche.

Un exemple avec [cet article](https://next.ink/127134/edito-la-securite-numerique-est-un-enjeu-deducation-populaire/) :

* Sur mon agrégateur :
![image](https://github.com/NextINpact/Next/assets/3851902/a61702ec-0244-4979-8608-818841daa6fb)
* Sur next.ink :
![image](https://github.com/NextINpact/Next/assets/3851902/c806be7d-70d5-4715-967d-60bee4950fdd)

**Comment by LeoColomb** [comment]
Je confirme, et ce n'est pas propre à Inoreader. Le problème est le même sur Feedly (et ailleurs).

![image](https://github.com/NextINpact/Next/assets/846943/258b1d12-d2ae-4348-8a8c-6229bdf19410)

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement 😄
