### ISSUE TITLE
Liste Le Brief sur la page d'accueille : problemes sur les jours / dates

### ISSUE THREAD

**Issue by matsala** [NextINpact/Next#308]
Hello,

Nous somme le mercredi 14/02.

Sur tel : sur la page d'accueille, saut dans le temps, la plupart du temps, ca passe de aujourd'hui au 7/02, ou 24/01
![Screenshot_2024-02-14-11-14-02-630_org mozilla firefox](https://github.com/NextINpact/Next/assets/10086789/ac6b1e7f-7367-4aad-9f2b-cbc2d6d3988e)
![Screenshot_2024-02-14-11-05-03-909_org mozilla firefox](https://github.com/NextINpact/Next/assets/10086789/a58b6faa-9ee9-4bfa-b3ed-add4ed869655)

sur Ordi / Ou Tel version Ordi : pas de saut

Sur les deux, les jours suivants de Aujourd'hui et Hier sont tous des Mercredis :
![Screenshot_2024-02-14-11-08-57-186_org mozilla firefox](https://github.com/NextINpact/Next/assets/10086789/93e0a942-2aa4-4dd1-85cd-0c5e7cb2f1f2)

Si : next.ink/?begin= "n'importe quelle date"
Le 1er jour de la liste reste Aujourd'huit dans la liste "Le brief"

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement 😄.
