### ISSUE TITLE
Beaucoup trop de place perdue et manque de contenu sur mobile

### ISSUE THREAD

**Issue by ndx1905-github** [NextINpact/Next#31]
Bonjour 
Visuellement c’est joli mais c’est pas le point. 
on veut du contenu !
Sur mobile on voyait plus d’ articles  sur une même page et on avait le sous titre et pas que le titre. 
ca dessert le site de montrer aussi peu de contenu. Et il y a de la marge pour en mettre plus. Regardez hacker news qui en met un max (trop) sur une seule page. 
en tout cas en l’état ça donne l’impression qu’il n’y a pas grand chose à lire et on passe son chemin. 
Captures d’écran sur iPhone 

![IMG_0083](https://github.com/NextINpact/Next/assets/64833823/cdb33de3-b314-47e1-9900-39032a6665ce)
![IMG_0082](https://github.com/NextINpact/Next/assets/64833823/ca3433c4-be42-4e1e-b997-af75100206a1)
![IMG_0081](https://github.com/NextINpact/Next/assets/64833823/ec945f01-388a-4ba8-83c1-8d00a1ce078f)
![IMG_0080](https://github.com/NextINpact/Next/assets/64833823/e454fc7b-a9fd-4db5-bd23-4d08c8e5bc36)

**Comment by floviolleau** [comment]
Bonjour,

je me permet de dire idem sur desktop ! On a a peine 2 articles au dessus de la ligne de flotaison et 6 sur l'ancien site (en comptant le meilleur de l'actu)
![image](https://github.com/NextINpact/Next/assets/5442973/9fc39cc5-92ae-4cb1-b4ca-36766c46bef9)
![2023-10-19_20-44](https://github.com/NextINpact/Next/assets/5442973/403b7096-9926-48de-ad5c-7beb03b6a327)

**Comment by Nozalys** [comment]
Hello, j'abonde également, de mon côté, sur desktop, NXI me permet de voir 4 titres d'articles et 5 Brief sur la page d'acceuil, là où Next affiche zéro articles, zéro brief (même s'ils étaient actifs) et 3 "au coeur des débats".

J'ajoute la quantité de place perdue sur les côtés.

**Comment by bansan85** [comment]
Un petit +1 rapide. Sur mon téléphone, cela fait comme la 2eme capture d'écran : l'en-tête de la page prend plus de la moitié de l'écran. C'est une très grosse perte de place.

**Comment by dragonis41** [comment]
Merci pour vos retours :) Notre équipe travail dessus pour réduire le plus possible l'espace au-dessus des articles

**Comment by eglyn** [comment]
Un mode compact serait le bienvenue, très pratique pour avoir toutes les news et update des commentaires sous les yeux :)

![image](https://github.com/NextINpact/Next/assets/24936778/f7a2ebb6-b8ba-42f0-8f31-b9b46a7ab7c3)

**Comment by Viguro79** [comment]
Je rajoute de mon côté que, sur la version desktop, la nouvelle taille de police n'est pas du tout adaptée. Ce qu'on veut, c'est du contenu. En 20px, on a beaucoup de texte sous les yeux.

**Comment by xavierforestier** [comment]
En UHD ça donne ça : 
![Screenshot_20231101_100826](https://github.com/NextINpact/Next/assets/23277701/36e73a5e-2e4f-4060-afbc-2e1737397c11)

il faudrait au moins agrandir le menu à droite (j'ai redimensionné ma fenêtre, ça semble +/- responsive :)  ): 
```
/* aside.css | https://beta.next.ink/wp-content/themes/wordpress-theme/asset/css/aside.css */
#aside {
  /* min-width: 294px; */
  min-width: 15vw;
}
/* article.css | https://beta.next.ink/wp-content/themes/wordpress-theme/asset/css/article.css */
#article-single .article-contenu {
  min-width: 25vw;
}
#article-single {
  min-width: 41vw; /* ou peut-être 42vw; */
}
```
C'est selon moi nettement mieux : 
![Screenshot_20231101_102226](https://github.com/NextINpact/Next/assets/23277701/ff272c75-53c3-4eca-82e8-e9c175800dca)
