### ISSUE TITLE
Ajouter un bouton "tout marquer comme lu" dans le centre de notification

### ISSUE THREAD

**Issue by brunof0d2** [NextINpact/Next#310]
Bonjour,

est-il possible d'ajouter un bouton pour marquer comme lues toutes les notifications d'un coup ? Devoir cliquer dessus une par une est un peu fastidieux.

Merci.

**Comment by Opwi** [comment]
Hello,

Nous venons d'implémenter cette feature et est disponible sur next.ink !

Bonne journée.

**Comment by brunof0d2** [comment]
Super merci beaucoup !
