### ISSUE TITLE
Problème d'abonnement

### ISSUE THREAD

**Issue by Wavee7** [NextINpact/Next#311]
Bonjour,
 
J'ai essayé de vous contacter par e-Mail à 2 reprises, la première datant déjà de plusieurs mois et jusqu'à présent je n'ai toujours aucune réponse.

J'ai constaté que sur plusieurs mois, j'ai été facturé 2x le prix de l'abonnement mensuel (5€), généralement le 6 et le 12 de chaque mois concernés.

N'ayant jamais reçu de réponse de votre part, j'ai décidé d'annuler mon abonnement. Malgré cela, mon abonnement a été renouvelé.

Merci de me contacter.

**Comment by pipoupoip** [comment]
Bonjour, 

A quelle adresse avez-vous essayé de nous contacter ? 
Vous pouvez nous envoyer un mail à support@next.ink avec les informations relatives à votre compte next (nom d'utilisateur et/ou adresse email liée au compte)

**Comment by Wavee7** [comment]
Bonjour,

La première fois à l'adresse support@nextinpact.com et la deuxième fois à l'adresse actu@nextinpact.com.

Je vais vous écrire à l'adresse indiquée, merci.

**Comment by pipoupoip** [comment]
Nous avons bien reçu votre email. Nous traitons votre demande cet après-midi.
