### ISSUE TITLE
Les réactions disparaissent lorsque les commentaires sont fermés

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/Next#313]
Les commentaires ayant eu des réactions (thumbsUp, lol, etc.) ne sont pas visible lorsque les commentaires sont fermés.

Exemple : https://next.ink/127466/moderation-critiquee-ulule-cesse-de-promouvoir-le-projet-de-bertrand-cantat/
Le premier commentaire (entre autres) avait des réactions. Maintenant, y'a juste une zone de vide.

**Comment by pipoupoip** [comment]
Meuh non pas du tout, je ne vous pas de quoi vous voulez parler ;)
