### ISSUE TITLE
Contacter le support technique : lien erroné

### ISSUE THREAD

**Issue by Jipem** [NextINpact/Next#315]
https://next.ink/profile/
"Contacter le support technique"
Le lien est : "mailto: mailto:support@next.ink" (mailto: en double)

```
<a href="mailto: mailto:support@next.ink">
<button class="profile_button profile_update_button" spellcheck="false">Contacter</button>
</a>
```

**Comment by Opwi** [comment]
Hello,

Nous venons de corriger le lien.

Merci du signalement 😁
