### ISSUE TITLE
Problème d'affichage : recouvrement légende / chapeau

### ISSUE THREAD

**Issue by Underground78** [NextINpact/Next#316]
Bonjour,

Tout est dans le titre, j'ai un bogue d'affichage dans l'article : https://next.ink/129173/une-cicatrice-metallique-sur-une-etoile-cannibale/. J'utilise Firefox 123 sous Linux. Je joins une capture qui sera plus parlante que tout le reste.

![bug](https://github.com/NextINpact/Next/assets/371636/981f2273-565a-4f2f-9304-b5c5a5f829b4)

U78

**Comment by Opwi** [comment]
Hello,

Nous avons corrigé le problème.

Merci du signalement.
