### ISSUE TITLE
Injection de code dans sur la page de profil.

### ISSUE THREAD

**Issue by Passific** [NextINpact/Next#318]
Comme vous pourrez facilement le constater sur la page de [mon profil](https://next.ink/public-profile/?id=25754), il est facile d'injecter du code dans la page de profil, et celui-ci va s'exécuter sans problème (2x même) quand une personne visite le profil.

Le code est bénin, mais il est facile de faire plus... enfin moins sympa quoi :
`<a href="https://passific.fr">https://next.ink</a><script>alert("Salut NEXT!")</script>`

Je n'ai pas testé, mais cela doit peut-être aussi marcher avec la bio.

Bien à vous,

**Comment by MosieurClement** [comment]
C'est maintenant corrigé, merci pour le retour
