### ISSUE TITLE
accès aux liens "signaler / bloquer" masqué en cas de nouveau commentaire

### ISSUE THREAD

**Issue by francois-dorin** [NextINpact/Next#320]
Les nouveaux commentaires sont marqués d'une pastille rouge. Cette pastille rouge est au-dessus du tout récent menu pour signaler / bloquer un commentaire.

Au passage, on peut s'auto-signaler / s'auto-bloquer ^^

**Comment by Opwi** [comment]
Hello,

Pour la petite pastille rouge c'est maintenant réglé.
Concernant l'auto-signalement / auto-bloquage je vais ouvrir une nouvelle issue.
