### ISSUE TITLE
RSS - Liens des boutons flux RSS mal formatés

### ISSUE THREAD

**Issue by Jipem** [NextINpact/Next#322]
Sur https://next.ink/profile/
Quand on clic sur les différents boutons des flux RSS
Les liens copiés sont mal formatés
Un grand espace se met avant et après la rsskey=
Créant ainsi un lien du style : https://next.ink/feed/full?rsskey=%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2020xxxxxxxxxxxxxxxxxxxx89

![image](https://github.com/NextINpact/Next/assets/2027318/86a14cae-3d70-4689-b377-84f62db4ec65)

**Comment by Opwi** [comment]
Bonsoir,

Merci du signalement ! Un correctif est prévu pour demain. 
Je fermerai l'issue une fois que le patch est déployé en production.

**Comment by Opwi** [comment]
Le correctif est maintenant déployé 😁.
