### ISSUE TITLE
Les lecteurs au pseudo trop long cassent la mise en page sur mobile

### ISSUE THREAD

**Issue by Dadkill** [NextINpact/Next#325]
Bonjour,

J'ouvre cette issue pour signaler que les pseudos trop longs ont tendance à faire déborder la mise en page sur mobile, avec tout l'inconfort que cela entraîne lors du scroll sur l'article, qui parfois déplace celui-ci vers la droite.

Et comme une image vaut mille mots, voici une illustration du problème :

![Screenshot_2024-03-17-01-17-36-87_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/NextINpact/Next/assets/22544947/7a44f61e-8b22-4d27-93f7-52ee35318e29)

Le lien vers l'article en question, même s'il y en a beaucoup d'autres concernés : https://next.ink/131246/comment-la-reforme-du-bac-a-encore-eloigne-les-filles-des-maths-et-des-sciences/

Merci d'avance pour la prise en compte du problème ! Je croise les doigts pour que celui-ci puisse être corrigé rapidement car il altère largement le confort de lecture sur ce support ! 😅

**Comment by Opwi** [comment]
Hello,

Un correctif a été déployé 😁.

Merci pour le signalement.
