### ISSUE TITLE
Erreur lors de l'ajout aux signets

### ISSUE THREAD

**Issue by avoidwebid** [NextINpact/Next#328]
Bonjour à toute l'équipe,

Je suis utilisateur connecté sous Firefox 124
Lorsque je consulte le dernier debrief
Et que je clique sur le bouton "Ajouter aux signets"
Alors j'ai l'erreur suivante dans la console navigateur et le signet n'est pas ajouté à mon compte.

```
Uncaught ReferenceError: addSignet is not defined
    onclick https://next.ink/briefs/lebrief-12-ans-de-support-pour-ubuntu-lts-bilan-de-la-cjue-la-provence-reorganisation-chez-microsoft/:1
12 [lebrief-12-ans-de-support-pour-ubuntu-lts-bilan-de-la-cjue-la-provence-reorganisation-chez-microsoft:1:1](https://next.ink/briefs/lebrief-12-ans-de-support-pour-ubuntu-lts-bilan-de-la-cjue-la-provence-reorganisation-chez-microsoft/)
    onclick https://next.ink/briefs/lebrief-12-ans-de-support-pour-ubuntu-lts-bilan-de-la-cjue-la-provence-reorganisation-chez-microsoft/:1
```

**Comment by MosieurClement** [comment]
Bonjour,

Humm c'est étrange, ce problème se produit uniquement sur cet article sur le dernier brief à chaque fois où s'il est présent sur tous les articles ?

**Comment by avoidwebid** [comment]
Hello @MosieurClement,

j'ai l'erreur lorsque j'ajoute des signets depuis une page de debrief, j'ai testé avec les suivantes :

- https://next.ink/briefs/lebrief-12-ans-de-support-pour-ubuntu-lts-bilan-de-la-cjue-la-provence-reorganisation-chez-microsoft/
- https://next.ink/briefs/lebrief-jurisprudences-hallucinees-brave-et-son-vpn-logiciels-espion-strategie-cloud-jesuisla/
- https://next.ink/briefs/lebrief-services-de-renseignement-prix-abel-2024-ile-de-france-et-lia-cni-et-empreintes/

En revanche je n'ai pas l'erreur si je clique sur l'un des articles de debrief et que j'utilise le bouton "ajouter aux signets", exemple d'article : https://next.ink/brief_article/ubuntu-lts-peut-avoir-jusqua-12-ans-de-support-avec-une-option-payante/

**Comment by MosieurClement** [comment]
Ah oui effectivement, on va déployer un correctif dans la semaine, merci pour le retour :smile:

**Comment by Opwi** [comment]
Hello,

Le correctif vient d'être déployé !

Merci pour votre signalement.
