### ISSUE TITLE
«Offrir l’article» n’affiche pas la pop-up

### ISSUE THREAD

**Issue by Mimoza** [NextINpact/Next#330]
Bonjour,
Quand je clic que le lien «offrir l’article» rien ne se passe à l’écran :( mais le lien est bien copié dans le presse papier.
Dans la console du navigateur j’ai ça :

> Uncaught (in promise) DOMException: Node.insertBefore: Child to insert before is not a child of this node
    messageCopyLink https://next.ink/wp-content/themes/next-theme/asset/js/share.js:1
    success https://next.ink/wp-content/themes/next-theme/asset/js/share.js:1
    promise callback*success https://next.ink/wp-content/themes/next-theme/asset/js/share.js:1
    jQuery 6
        c
        fireWith
        l
        o
        send
        ajax
    giftArticle https://next.ink/wp-content/themes/next-theme/asset/js/share.js:1
    onclick https://next.ink/132706/emissions-reelles-de-co₂-en-europe-le-poker-menteur-des-vehicules-hybrides/:1
share.js:1
    messageCopyLink https://next.ink/wp-content/themes/next-theme/asset/js/share.js:1
    success https://next.ink/wp-content/themes/next-theme/asset/js/share.js:1
    (Asynchrone : promise callback)
    success https://next.ink/wp-content/themes/next-theme/asset/js/share.js:1
    jQuery 6
        c
        fireWith
        l
        o
    (Asynchrone : EventHandlerNonNull)
        send
        ajax
    giftArticle https://next.ink/wp-content/themes/next-theme/asset/js/share.js:1
    onclick https://next.ink/132706/emissions-reelles-de-co₂-en-europe-le-poker-menteur-des-vehicules-hybrides/:1

Je ne sais pas si c’est en lien avec le ticket [301](https://github.com/NextINpact/Next/issues/301) qui remonte un soucis avec cette fonctionnalité aussi.

Pour info mon navigateur est FF en version 124.0.1 avec uBlock origin & Privacy badger. Mais même désactivé je n’ai rien :-1:

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement 😄
