### ISSUE TITLE
Mise en page cassée sur mobile à cause des nouveaux commentaires

### ISSUE THREAD

**Issue by Dadkill** [NextINpact/Next#333]
Bonjour !

Tout d'abord merci beaucoup pour la correction de la mise en page cassée à cause de certains pseudos trop long ! C'est vraiment génial pour le confort de lecture !

Cependant, j'ai constaté qu'un problème similaire pouvait se produire à cause des nouveaux commentaires sur un article, comme vous pouvez le voir sur la capture d'écran.

![IMG_20240405_131812](https://github.com/NextINpact/Next/assets/22544947/8c64635b-ec16-4c3a-b4cd-e8ecbf3c31f7)

Merci d'avance pour la correction et continuez le super boulot accompli sur Next ! ❤️

**Comment by MosieurClement** [comment]
Ah oui effectivement, vous pouvez me donner votre résolution d'écran et modèle de téléphone ?

**Comment by Dadkill** [comment]
Hello !

Mon téléphone est un OnePlus 12 sur Android 14, avec une résolution de 3168*1440.

**Comment by Dadkill** [comment]
Update : ça se produit également sur la liste des articles

![IMG_20240409_140525](https://github.com/NextINpact/Next/assets/22544947/91360b81-d38f-428d-b353-89637a410f05)

**Comment by MosieurClement** [comment]
C'est depuis qu'on a rajouté le bouton pour copier le lien directement dans la barre du bas, on va fixer ça soon ;)

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement 😄
