### ISSUE TITLE
[Brief][RSS] Ajouter les images en-têtes d’article du Brief dans le flux RSS condensé

### ISSUE THREAD

**Issue by ldidry** [NextINpact/Next#334]
Parce que des fois, y a de jolis dessins de Flock en tête des articles du brief et que c’est dommage de les louper…

Merci ! :pray:

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement 😄

**Comment by ldidry** [comment]
Merci !
