### ISSUE TITLE
Incohérence du header et du footer selon les articles à cause de StatCounter

### ISSUE THREAD

**Issue by Dadkill** [NextINpact/Next#336]
Bonjour,

Pour cette issue, plutôt que 1000 mots, je préfère illustrer le problème avec Le Brief du 11 avril 2024.

Quand je me trouve sur la page répertoriant l'ensemble des brèves de la journée, le header ne comporte pas de menu hamburger en haut à droite : 

![IMG_20240411_224041](https://github.com/NextINpact/Next/assets/22544947/90068c3b-f89f-4334-9f27-2840d993dfb3)

Il en est de même d'ailleurs avec l'article sur Linux. D'ailleurs, le concernant, le footer ne s'affiche jamais ou pratiquement jamais, et le header disparaît également, contrairement à d'habitude où leur affichage reste fixe :

![IMG_20240411_224052](https://github.com/NextINpact/Next/assets/22544947/b1602623-8cf1-46df-b503-c5d8441bd616)

Ce qui est étrange, c'est qu'une autre brève tirée du 11 avril comporte bien l'affichage sans bug :

![IMG_20240411_224102](https://github.com/NextINpact/Next/assets/22544947/57cdb34c-0e3c-478a-ae99-3a96114f52f3)

Après vérification, il semblerait que le problème provienne, une nouvelle fois (cf : #335), de StatCounter, car le problème ne se produit que sur l'article l'intégrant et sur la page global du brief, puisqu'il apparaît également.

**Comment by Dadkill** [comment]
Hello, même souci avec le Brief du 24 avril, qui ne contient pas de graphiques StatCounter. Apparemment, la vidéo de l'article Hubble (vidéo YouTube qui casse la mise en page aussi depuis plusieurs mois par ailleurs UNIQUEMENT sur la page recensant toutes les brèves du jour et pas sur la brève en elle-même), semble être la responsable : https://next.ink/briefs/lebrief-fedora-40-anniversaire-hubble-videosurveillance-algorithmique-a-cannes-voyager-1-android-15-beta-1-1/

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement 😄
