### ISSUE TITLE
[UI] Icone de NEXT

### ISSUE THREAD

**Issue by Nozalys** [NextINpact/Next#34]
Bonjour,

Je trouve que l'icône du site (le favicon qui apparait dans l'onglet de navigation) n'est pas un choix terrible. Un "X", c'est déjà pris par Twitter et ça fait aussi un peu XXX. Je suis pas certain d'avoir envie qu'un "X" soit épinglé en permanence sur mon PC pro...

L'icone actuel de NXI était reconnaissance parmi tous, le nouveau "X" n'aidera pas.

Je laisse d'autres lecteurs commenter mon avis.

**Comment by dragonis41** [comment]
Je ferme l'issue comme le favicon "x" n'existe maintenant plus :)
