### ISSUE TITLE
Profile annonyme a spammé les commentaires d'un ancien article

### ISSUE THREAD

**Issue by DuchkPy** [NextINpact/Next#346]
Le profil annonyme `id=0` a spammé un ancien article, à partir d'[ici](https://next.ink/4779/lassociation-interhop-demande-au-gouvernement-prouver-lefficacite-tousanticovid/#comment-archor-2121903).

Puis, c'est l'équipe qui s'est amusé à faire des tests... [à la fin](https://next.ink/4779/lassociation-interhop-demande-au-gouvernement-prouver-lefficacite-tousanticovid/#comment-archor-2129580)

Bon, si ce n'était que des essais, et que Ness_01 a bien fait le job, il reste tous les liens dans le pseudo. Qui eux, renvoient bien vers des pages assez troublantes !

**Comment by MosieurClement** [comment]
Merci pour le retour c'est normalement réglé
