### ISSUE TITLE
Nouvelle interface: il manque un repère visuel sur la page principale pour 

### ISSUE THREAD

**Issue by JohnXLivingston** [NextINpact/Next#347]
Bonjour,

Avec l'ancienne mise en forme (jusqu'au 28 avril), on avait un repère visuel à chaque changement de jour. De plus, en général chaque journée commençait par un brief.
Donc quand on se connectait, il était très simple visuellement de savoir où on avait arrêté la lecture la veille, et de reprendre les nouveaux articles.

Avec la mise en forme mise en place le 29 avril, tous les articles s'enchainent, et on n'a plus aucun repère visuel pour savoir où on s'était arrêté. Il est alors assez pénible pour le cerveau de reprendre le fil: on doit remonter la liste des articles, et se rappeler si on les as déjà lu ou non.
Le fait que le brief n'existe plus, et que tout ça soit éclaté en N lignes complique encore la tâche: au lieu d'avoir 4 ou 5 lignes par jour, on en a une dizaine (cf ce jeudi par ex).

Il serait bon de rétablir quelque chose, au niveau du trait rouge sur cette capture :

![image](https://github.com/NextINpact/Next/assets/38844060/a752c338-4202-4db4-a489-9dc595d5f52e)

En plus de cela, ce serait utile d'avoir une indicateur visuel sur les articles lus. Du genre: changer la couleur de fond.

On pourrait aussi imaginer une ligne horizontale "depuis la dernière visite", comme on trouve dans  certains clients de messagerie.

**Comment by AIMAR-S** [comment]
Et hop ils ont ajouté la date :)

**Comment by JohnXLivingston** [comment]
C'est beaucoup mieux ! Merci !

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement 😄
