### ISSUE TITLE
Title sur bouton signet

### ISSUE THREAD

**Issue by darkweizer** [NextINpact/Next#348]
Bonjour,

Arrêtez tout ! J'ai trouvé le bug le plus critique du site :

Le title sur un signet d'article quand il n'est pas présent est aussi `Retirer des signets` au lieu d'`Ajouter aux signets`
![image](https://github.com/NextINpact/Next/assets/15857329/12165a01-d358-4cf1-bb23-f3b798f17d02)

Un hotfix dans les plus brefs délais, même un vendredi de pont, me semble essentiel... 😬

Cordialement.

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement 😄
