### ISSUE TITLE
Cache au post des commentaires ?

### ISSUE THREAD

**Issue by Wivik** [NextINpact/Next#349]
Depuis mardi 7/05 je dois faire ctrl+F5 pour voir les messages postés. Je pense que vous avez du activer une mise en cache qui ne semble pas s'invalider à ce moment-là.

**Comment by Wivik** [comment]
Complément : pareil sur le marquage comme lu des notifs. En gros, ça doit toucher tous les éléments dynamiques.

Sauf l'édition de message.

**Comment by Opwi** [comment]
Hello,

Normalement, ça devrait être corrigé. On a en effet fait des modifications sur la gestion du cache hier. 
Je laisse l'issue ouverte au cas où.

Bonne journée !

**Comment by Wivik** [comment]
Ca marche sur mon poste™
