### ISSUE TITLE
Connexion impossible sur version mobile

### ISSUE THREAD

**Issue by mathieumainchain** [NextINpact/Next#35]
La connexion au compte utilisateur fonctionne depuis la vue bureau, mais pas depuis un mobile.
Testé avec brave et safari sur mobile.

**Comment by xdelatour** [comment]
Avec Brave sur mobile, après avoir saisi son pseudo et son mot de passe, il semble qu'il ne se passe rien, il n'est indiqué nulle part que l'utilisateur est connecté.

Par contre, quand on va sur les commentaires d'un article (à condition qu'il y ait des commentaires), il y a bien un champ de saisie avec son pseudo. Quand on clique dedans, ça fait apparaître un rectangle qui déborde de l'écran sur la droite et le bouton de validation est presque entièrement en dehors de l'écran.
