### ISSUE TITLE
Faute syntaxique dans les dates d'article

### ISSUE THREAD

**Issue by Dadkill** [NextINpact/Next#353]
Hello tout le monde !

Je viens faire mon pointilleux aujourd'hui, mais cela fait plusieurs fois que je constate cette petite erreur dans le formatage des dates de publication des articles, dans lequel le mois est affiché avec une majuscule.

Cela est correct dans la langue de Shakespeare, mais pas chez nous : https://www.academie-francaise.fr/majuscules-aux-noms-de-jours-et-de-mois

Merci encore pour tout le travail accompli ! :)

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement 😄
