### ISSUE TITLE
PWA: Impossible de zoomer une image

### ISSUE THREAD

**Issue by loiklo** [NextINpact/Next#354]
Il est parfois nécessaire d'agrandir les images incluses dans les news pour voir ce qui est écrit, comme des screenshots par exemple.

En version mobile via un navigateur, on peut "ouvrir l'image dans un nouvel onglet", puis zoomer.

Dans la PWA, il n'y a pas ce notion d'onglet, donc c'est impossible d'agrandir l'image.

Je pense que c'est une option dans le css qui force ca. Si c'est le cas, serait-il possible d'ajuster ce paramètre pour pouvoir agrandir les images?

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement 😄
