### ISSUE TITLE
Le bouton "Offrir l'article" ne fonctionne pas

### ISSUE THREAD

**Issue by Ozwel** [NextINpact/Next#355]
Bonjour,

Le bouton "Offrir l'article" ne répond pas chez moi sur Firefox (uBO désactivé je précise).

J'ai testé sur Edge pour avoir un moteur chromium, premier constat : le bouton "Partager l'article" n'existe pas par rapport à l'affichage sous Firefox. Deuxième constat : quand je clique sur "Offrir l'article" ça a le comportement de "Partager l'article".

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement 😄
