### ISSUE TITLE
Typo dans les utilisateurs suivi (Bloqué au lieu de Suivi)

### ISSUE THREAD

**Issue by Passific** [NextINpact/Next#359]
La page https://next.ink/profile/?tab=suivi affiche les liste des utilisateurs suivi, avec la date de début du suivi marqué comme suit :
![image](https://github.com/NextINpact/Next/assets/2100205/425c7934-9c21-4fbe-8ed5-75748426d36e)

On peut lire `Bloqué le: 26/06/2024` à la place de `Suivi depuis le: 26/06/2024`

Nota : il est d'ailleurs possible de se suivre soi-même mais je ne sais pas ce que cela donne niveau notification.

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement 😄
