### ISSUE TITLE
[NI] Reçu un mail incorrect annonçant la fin de mon abonnement

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/Next#36]
Je sais que c'est légèrement hors sujet, mais puisque vous travaillez sur l'ensemble, c'est l'endroit qui me semblait le plus approprié.

J'ai reçu un mail m'indiquant que mon abonnement NI prenait fin dans 7 jours. Je sais que ce n'est pas le cas, puisque mon renouvellement est entre Noël et le jour de l'an.  
⇒ 1er problème : mail faux.

Je vais donc sur mon compte NextInpact (https://compte.nextinpact.com/gestion-util),  pour voir ce qu'il en est vraiment, m'identifie, et tombe sur une erreur 500.  
⇒ 2e problème : pas d'accès à la gestion du compte abonné.

Je me doute que vous faites des bidules dessus en ce moment, et je me fais pas trop de soucis. Mais au cas où les conséquences (surtout le mail qui fait "peur") vous étiez inconnues, j'ai préféré remplir ce bug.

**Comment by Trit34** [comment]
Bah, c’est connu, mais avec l’avancement du nouveau site, ils hésitent à consacrer du temps à essayer de réparer ça…

Perso, mon abonnement est renouvelé le 1<sup>er</sup> du mois, donc si ce bug doit provoquer un blocage du renouvellement, ça sera embêtant. :/

**Comment by dragonis41** [comment]
Dupliqué de [cette issue](https://github.com/NextINpact/nextinpactv7/issues/269)
On va essayer de trouver un peu de temps pour fixer ça rapidement, on avait déjà essayé de corriger le problème mais sans succès 🫤

**Comment by dragonis41** [comment]
Je renomme l'issue comme l'erreur 500 est maintenant corrigée, on enquête sur la raison de ce mail qui n'est effectivement pas normal

**Comment by pipoupoip** [comment]
Hello,

Peux-tu nous dire ici ou par mail à dev@next.ink quel moyen de paiement tu as utilisé pour payer (PAS le numéro de cb hein ;), juste paypal/cb via payzen/autre ?)

**Comment by Cqoicebordel** [comment]
Mail envoyé :)

**Comment by pipoupoip** [comment]
Bien reçu, merci
On regarde ça

**Comment by pipoupoip** [comment]
Après vérification, nous avons bien reçu le paiement à la date indiquée. On a corrigé ton abonnement spécifiquement. 

Malheureusement comme c'est sur l'*ancien* site, et les abonnements annuels n'étant pas si communs, on verra s'il y a d'autres cas qui se présentent à nous pour gérer au cas par cas (ça n'a pas l'air généralisé, on voit bien des abonnements annuels dont l'expiration est bien un an après le paiement). 

Je clos donc

**Comment by Cqoicebordel** [comment]
Ah cool, et fait chier.

Cool parce que mon problème perso est réglé (merci à vous !)

Et fait chier parce que je vous ai embêté avec un problème perso et pas un vrai bug. Désolé.

Mais effectivement, si c'est un problème unique, clore et attendre et voir me semblent de bons choix :)

**Comment by Trit34** [comment]
> Je renomme l'issue comme l'erreur 500 est maintenant corrigée, on enquête sur la raison de ce mail qui n'est effectivement pas normal

Je confirme que https://compte.nextinpact.com/gestion-util refonctionne.

Merci, les gars ! :+1:
