### ISSUE TITLE
Vignettes en taille originale sur articles suggérés

### ISSUE THREAD

**Issue by MisterDams** [NextINpact/Next#360]
Bonjour,

J'ai noté sur une actu du brief que les bloc des contenus suggérés semblent charger l'image originale, plutôt qu'une miniature.

Un bel exemple ici : https://next.ink/brief_article/iter-by-drone-une-video-du-reacteur-a-fusion-nucleaire/

L'image chargée pour "Fission et fusion nucléaire : de quoi...." fait plus de 8Mo pour une surface d'affichage microscopique : beaucoup de data consommées pour le visiteur nomade et beaucoup de ressources pour l'Infra !

**Comment by MisterDams** [comment]
Il semble que les articles liés n'affichent plus de vignettes, je ne sais pas si je dois faire évoluer le ticket pour les récupérer ou clore le point ?

**Comment by MosieurClement** [comment]
Bonjour, merci pour le retour et désolé pour le délai de réponse. Étant donné que les articles liés n'affichent plus les images, je pense que nous pouvons clore ce point. Cependant, nous resterons attentifs si jamais des miniatures devaient réapparaître.
