### ISSUE TITLE
les emotes sont générées même entre les balises de code

### ISSUE THREAD

**Issue by Albirew** [NextINpact/Next#361]
CF: https://next.ink/brief_article/wikipedia-a-enfin-son-mode-sombre/#comment-2142935

Les emotes sont générées même entre 2 balises de code \`code\`

**Comment by Albirew** [comment]
aussi, mettre une url contenant :D casse la génération d'URL `[texte](httpx://wiki.tld/user:Didier)`
CF https://next.ink/brief_article/wikipedia-a-enfin-son-mode-sombre/#comment-2142769
`https://meta.wikimedia.org/wiki/User:DavidL/DarkTheme` par exemple deviens en lien `https://meta.wikimedia.org/wiki/User<img data-src=`

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement 😄
