### ISSUE TITLE
[RSS flux complet] Trocaturage d’article comme si pas abonné

### ISSUE THREAD

**Issue by Mimoza** [NextINpact/Next#362]
Bonjour,
Dans mon flux RSS j’ai eu la surprise de voir que le dernier article ([Apple soulève un peu le capot de ses modèles utilisés par Apple Intelligence](https://next.ink/145305/apple-souleve-un-peu-le-capot-de-ses-modeles-utilises-par-apple-intelligence/)) était tronqué comme si je n’était pas abonné, alors que c’est bien le cas et que mon abonement est encore valable jusqu’a fin novembre.

>Il reste 89% de l'article à découvrir. Abonnez-vous pour ne rien manquer.
>Déjà abonné ? Se connecter
>[Abonnez-vous](https://next.ink/subs/)

**Comment by dragonis41** [comment]
Bonjour, on a changé notre manière de gérer le paywall et effectivement ça a eu comme effet de bord de casser le flux RSS, on travaille dessus pour que ça revienne au plus vite

**Comment by Opwi** [comment]
Hello, 

Nous venons de déployer un correctif. Si jamais vous relevez à nouveau des soucis avec le flux RSS ou que le problème a été partiellement réglé, n'hésitez pas à rouvrir cette issue.

Merci pour la remontée de bugs.
