### ISSUE TITLE
[BUG] [Paywall] Même derrière le paywall, les images sont accessibles via caroussel

### ISSUE THREAD

**Issue by theoldscudo** [NextINpact/Next#364]
Hello,
J'ai remarqué en regardant la publication hebdo de Flock du 14/09.
Mon compte Next était déconnecté, donc j'ai eu le paywall "il reste 36% de cert article...", masquant les images après la première image.
Sauf qu'en cliquant, on ouvre le caroussel et là on peut parcourir toutes les images, même celles normalement "bloquées".

Effectivement, on a la liste dans un **div id="list_image"** dispo avant le paywall

**Comment by MosieurClement** [comment]
Merci pour le retour c'est maintenant réglé ;)
