### ISSUE TITLE
Mise en page des articles cassée sur mobile

### ISSUE THREAD

**Issue by Dadkill** [NextINpact/Next#365]
Bonjour l'équipe !

Le problème apparaît sur l'article suivant suite à l'insertion d'une URL : https://next.ink/brief_article/la-russie-bloque-la-base-de-donnees-sur-la-censure-ooni/

![Screenshot_2024-09-27-02-41-40-85_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/d740cca9-ce96-4402-8d86-956dc3f09db8)

Il me semblait que ce problème avait été résolu, mais a dû être réintégré suite à une mise à jour !

**Comment by MosieurClement** [comment]
C'est effectivement normalement réglé, merci pour le retour :)
