### ISSUE TITLE
Page d'accueil : le div de la section Brief a un comportement "bizarre"

### ISSUE THREAD

**Issue by NdjPoye** [NextINpact/Next#37]
Bonjour.

Sous Edge Version 119.0.2151.12.

Quand on fait défilé, le div de la section Brief laisse beaucoup de blanc 
![image](https://github.com/NextINpact/Next/assets/39985945/115e780e-b7f3-45b9-bb8e-608a81a96467)

Et quand on arrive en bas de page, le div est pareillement mangé par le bandeau du bas.
![image](https://github.com/NextINpact/Next/assets/39985945/83a91f66-269c-446d-ad9a-07c89578235a)

**Comment by AIMAR-S** [comment]
Ici il y a une méprise dans la façon de faire pour avoir cet effet, on utilise pas `fixed` mais `sticky`

https://developer.mozilla.org/fr/docs/Web/CSS/position

Normalement **le contenu de la colonne** dois être `sticky` et sa colonne doit faire, grâce à flex, 100% de la même hauteur que sa colonne de gauche.

On met directement la class `sticky` dans le sous container ( ici main ) qui lui dit à combien de px s'arrêter en haut et dès que le contenu rencontrera le bas il s'arrêtera et remontera avec la fin de la page.

Ici c'est la colonne qui à été mis en fixed directement et en plus avec du JS ! Ce qui fait qu'elle sors complètement du flux HTML/CSS et donc continue derrière le footer.

Vous pouvez donc économiser au navigateur un coûteux "on resize" ou "on scroll" d'ailleurs je n'ai pas bien capté pourquoi la recherche de la taille... faudrait que je regarde mieux pour comprendre.

**Comment by AIMAR-S** [comment]
Alors je confirme, a part raisons particulère en Desktop le calcul de right ne sers à rien quand on retire fixed sur `.fixed-brief` 

En gros ( et sans aucune idée des autres besoins responsive et autres blocks ... donc surement des infos pas terriblement précises )

Rajouter ceci sur les classes suivantes ( en SASS style ):
```
.list-brief {
  height: auto;
  flex: 1;
  & > main {
     position: sticky;
     top: 10px;
  }
}
```
Après il faudra biensur reporter le style du brief appliqué à `.list-brief` à `main` car c'est lui qui vas "glisser" le long de la colonne.

Pour l'écartement de 70px en desktop, vous pouvez jouer sur le parent qui est flex et utiliser gap qui fait bien le même taff, à voir.

Je pense que comme ça vous pouvez virer les fonctions JS on `scroll` qui s'occupaient de positionner cet élément dans la colonne.

Voilà en gros !

**Comment by dragonis41** [comment]
En principe ça a été fix, n'hésitez pas à rouvrir l'issue si vous avez toujours le problème, même après avoir clear le cache :)

**Comment by AIMAR-S** [comment]
> En principe ça a été fix, n'hésitez pas à rouvrir l'issue si vous avez toujours le problème, même après avoir clear le cache :)

Sincèrement, même après un Ctrl Shift F5, ça ne semble pas réglé chez moi :
![image](https://github.com/NextINpact/Next/assets/13015224/4daacff6-e605-4d5a-89c2-5382f89cf938)

Il faut refaire une nouvelle issue ?

**Comment by dragonis41** [comment]
My bad je croyais que c'était une autre issue où le sommaire était crop en plein milieu de page, je vois ça avec l'équipe

**Comment by Opwi** [comment]
Bonjour,

Suite à un changement de design l'issue n'est plus d'actualité.

Merci du signalement 😄
