### ISSUE TITLE
Articles vides !

### ISSUE THREAD

**Issue by darkweizer** [NextINpact/Next#375]
Bonjour,

Je me suis connecté sur un nouvel ordinateur, qui avait uBlock Origin d'activé (et pas désactivé sur next donc). Et je me retrouve avec des articles vides comme [celui-la](https://next.ink/brief_article/sur-x-le-nouveau-bouton-bloquer-fait-de-la-figuration/) ou [celui-ci](https://next.ink/brief_article/e-enfance-devient-le-premier-signaleur-de-confiance-en-france/). Je ne pense pas que ce soit volontaire de votre part et surtout ce n'est que sur quelques articles ! 
Je n'ai pas poussé à chercher plus l'explication que ça, désolé.
![image](https://github.com/user-attachments/assets/982faf0b-28b5-4f6d-ba50-dc71670b2186)
![image](https://github.com/user-attachments/assets/14e794cf-5b5f-4942-a67c-2e8b3d099510)

Firefox 132.0.1, uBlock Origin 1.60.0 (filtres à jour), W10 22H2 19045.5073

Cordialement.

**Comment by Nightmaster** [comment]
J’ai récemment remarqué les mêmes soucis, sur les mêmes articles, du Brief principalement, et toujours sur FF.
Je précise aussi (pour aider), j’ai uBlock et d’autre plugins du même acabit, mais tous sont coupés sur Next, et même le fait de désactiver la "protection renforcée contre le pistage" de FF ne change rien, et je ne vois pas de requêtes passer en erreur dans la la section réseau de la console…

En espérant que ces détails peuvent aider 😐

**Comment by MosieurClement** [comment]
Bonjour, rencontrez vous toujours le soucis ?

**Comment by Nightmaster** [comment]
> Bonjour, rencontrez vous toujours le soucis ?

De mon côté, j’arrive maintenant à voir les articles mentionnés. Je reteste sur l’ordinateur "fautif" initialement (ce n’est pas celui avec lequel j’écris actuellement, même si configuré exactement pareil), et je valide "définitivement" ma réponse 👍

**Comment by Nightmaster** [comment]
> > Bonjour, rencontrez vous toujours le soucis ?
> 
> De mon côté, j’arrive maintenant à voir les articles mentionnés. Je reteste sur l’ordinateur "fautif" initialement (ce n’est pas celui avec lequel j’écris actuellement, même si configuré exactement pareil), et je valide "définitivement" ma réponse 👍

Je confirme, le PC sur lequel j’avais aussi le problème affiche bien les articles "incriminés" maintenant, et pas de nouveaux rebelles depuis quelque jours 😁

**Comment by MosieurClement** [comment]
Super :)
