### ISSUE TITLE
Plus d'images dans les flux RSS

### ISSUE THREAD

**Issue by fmunch** [NextINpact/Next#377]
Les images (sauf l'image d'en-tête) n'apparaissent plus dans les [flux RSS](https://next.ink/feed/full?rsskey=...).

On retrouve à chaque fois cet attribut (sans guillemets d'ailleurs) :

```
src=image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==
```

Par exemple dans le brief sur Fedora 42 :

```
<figure class="wp-block-image size-large"><img class="wp-image-158038" src=image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw== alt="" loading="lazy"></figure>
```

J'ai l'impression que tout fonctionnait jusqu'à hier.

**Comment by thican** [comment]
Bonjour,
Je confirme aussi rencontrer cette anomalie depuis quelques jours.

**Comment by MosieurClement** [comment]
Est ce que vous avez toujours le problème ?

**Comment by fmunch** [comment]
Ça a l'air réglé maintenant, merci beaucoup

**Comment by thican** [comment]
Ça semble mieux, merci.
