### ISSUE TITLE
Avoir les images des articles dans le flux RSS

### ISSUE THREAD

**Issue by nicolas-maker** [NextINpact/Next#38]
C’est cool d’avoir plus d'images de Flock, mais quand on consomme les infos du site presque exclusivement en utilisant le flux RSS abonné, on passe à côté 
Ce serait possible d’ajouter les images d’illustration des articles dedans aussi ?

**Comment by Viguro79** [comment]
Oh oui ! J'ai l'habitude de consulter le site via le flux rss. Il faut absolument conserver les images dedans pour simplifier la lecture

**Comment by dragonis41** [comment]
Bonjour, je vous invite à suivre la discussion dans l'issue #1
