### ISSUE TITLE
[BUG] Bandeau bêta occulte la fermeture du menu latéral 

### ISSUE THREAD

**Issue by Dadkill** [NextINpact/Next#4]
Sur smartphone, il m'est impossible de fermer le menu latéral autrement qu'en rafraîchissant la page car le bandeau occulte les éléments de celui-ci au lieu de se placer au-dessus.

Par ailleurs, vous pourrez remarquer que celui-ci est également tronqué. Cela ne se produit qu'à l'ouverture du menu. Autrement, il est entier !

![Screenshot_2023-10-16-21-48-09-69_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/NextINpact/Next/assets/22544947/b8ae46d3-1159-4ad4-b73b-cb414fe90a17)

Smartphone : Oneplus 8 Pro sous Android 13
Navigateur : dernière version de Chrome

**Comment by MosieurClement** [comment]
C'est corrigé, merci pour ton retour
