### ISSUE TITLE
Résolution des images

### ISSUE THREAD

**Issue by hwti** [NextINpact/Next#41]
https://cdn.next.ink/inpactv7/data-next/images/bd/wide-linked-media/12902.jpg (3572x1730) est utilisée pour la page d'accueil (280x200) et l'article (850x410).
Même pour les écrans HiDPI c'est beaucoup trop.

En comparaison le site actuel a :
 - 89x67 ou 144x108 pour la miniature de 144x108 en page d'accueil
 - 374x181, 850x412 ou 1023x495 pour 851x400 sur l'article

Pire, https://cdn.next.ink/inpactv7/data-next/images/bd/wide-linked-media/12886.jpg (6016x2918, 2,1Mo).

De même, les photos des auteurs affichées en 20x20, 45x45 ou 100x100 font 260x260, 569x530, 489x492, et même 2048x1536 (Jean-Marc) !
Sur le site actuel il y a le même problème, mais c'est limité aux pages des articles.

Au passage, la Firefox charge deux fois la favicon (probablement car référencée par `apple-touch-icon` et `icon`), et même si elle est compressée pour le transfert, c'est étrange que ce soit un *.ico de 156x156 non compressé.

**Comment by Alexandre-Gliganic** [comment]
Issue dupliquée #32. Vous pouvez suivre l'évolution là-bas.
