### ISSUE TITLE
Bouton de commentaire caché par les filtres types "Annoyances"

### ISSUE THREAD

**Issue by hwti** [NextINpact/Next#42]
La classe `top-share` est dans EasyList – Social Widgets, donc le bloc peut être caché pour certains utilisateurs.
Il faudrait peut-être séparer le bouton commentaires, ou nommer la classe autrement puisque les fonctions de partages sont très discrètes et sans contenu externe.

**Comment by pipoupoip** [comment]
C'est corrigé :)
