### ISSUE TITLE
Améliorer "Copier le lien"

### ISSUE THREAD

**Issue by PierreLetter** [NextINpact/Next#44]
Sur une news, lorsque l'on clique sur "copier le lien" il n'y a aucune réaction. Je me suis interrogé si le lien avait bien été copié.
Un petit feedback visuel (changement de couleur de l'icône, petit rectangle disant "copié", autre) serait sympa. En prio basse bien entendu.

**Comment by MosieurClement** [comment]
Merci pour le retour, on va rajouter quelques retours visuels

**Comment by pipoupoip** [comment]
Je ferme pour doublon de la #18
