### ISSUE TITLE
"Semaine précédente" manquant sur PC avec fenêtre de petite taille

### ISSUE THREAD

**Issue by bansan85** [NextINpact/Next#45]
Quand mon Firefox est en plein écran, j'arrive bien à naviguer de page en page.

![image](https://github.com/NextINpact/Next/assets/9248729/78bdc5e6-0864-4e79-b098-44a6c6e5eec1)

![image](https://github.com/NextINpact/Next/assets/9248729/775cf4c2-df91-47f7-902f-b9d471347606)

Par contre, si je mets mon navigateur en moitié écran, impossible de naviguer dans les articles précédents :

![image](https://github.com/NextINpact/Next/assets/9248729/bf927739-36d1-4222-b4f2-d7b341b30c9d)

**Comment by bansan85** [comment]
Il n'y a toujours pas le bouton "semaine précédente" mais il y a la présence d'un défilement infini maintenant. On peut probablement fermer ce ticket.

Par contre, faites attention, sur PC, quand on laisse la touche du clavier "FIN" appuyée, ça va vous spammer de requêtes. La plupart des sites font apparaître un bouton à cliquer quand on est assez loin dans l'historique (genre 5 requêtes).

**Comment by pipoupoip** [comment]
Hello 

Merci pour l'avertissement. Je pense que ça ne devrait pas poser de souci. Au pire on fera un post mortem sur le ddos le plus nul de l'histoire ^^(si ça arrive un jour, rappelle-nous que tu nous l'avais bien dit, ça méritera qu'on te rende cet hommage)
