### ISSUE TITLE
Naviguer dans l'historique des articles ne change pas l'url

### ISSUE THREAD

**Issue by bansan85** [NextINpact/Next#46]
Quand je clique sur "Semaine Précédente" ou "Semaine Suivante" ne change pas l'url (https://beta.next.ink/).

Problème : quand je clique sur "actualiser la page", je retourne sur la page principale.
Problème bis : ça se passera bien pour le web scraping ?

**Comment by MosieurClement** [comment]
Il y a une issue ouverte pour ce problème #27 😉

**Comment by bansan85** [comment]
Bien vu :blush: Sur les 4 problèmes que j'ai trouvés, c'est le seul où j'ai pas vérifié s'il avait déjà été rapporté... :sweat_smile:
