### ISSUE TITLE
List-style manquant pour les listes dans les articles

### ISSUE THREAD

**Issue by sherblot** [NextINpact/Next#47]
Bonjour,

Dans les articles, les listes n'ont aucun symbole les précédant, ce qui fait qu'on ne distingue pas les éléments des listes d'un retour à la ligne normal. 

Par exemple sur cet article : https://beta.next.ink/115952/reduire-son-empreinte-environnementale-numerique-cest-comme-tri-selectif-il-faut-faire-point-barre/

![next beta link-style](https://github.com/NextINpact/Next/assets/448192/b427eb19-4fa6-4422-9743-bc5ba92f87e0)

Cause : style.css:58
`ol, ul {
    list-style: none;
}`

Les listes ont également trop de marge entre les éléments. Actuellement il a un margin-bottom: 25px; pour les li. Je pense qu'une entreligne identique à celle dans un paragraphe serait plus agréable à la lecture (en gros pas de margin bottom pour les li mais l'appliquer aux ul/ol).

**Comment by MosieurClement** [comment]
Effectivement ça ne rend pas très bien, on va améliorer ça 😁

**Comment by pipoupoip** [comment]
C'est bon (enfin ^^)
