### ISSUE TITLE
[BUG] Connexion infructueuse

### ISSUE THREAD

**Issue by Dadkill** [NextINpact/Next#5]
Lorsque je tente de me connecter, le site me redirige vers la page d'accueil, mais continue de m'afficher "Connexion" et me propose de me connecter à nouveau.

Cela se produit aussi bien sur mon desktop (Windows 10, Chrome 118 à jour) que sur mon smartphone (Oneplus 8 Pro, Android 13, Chrome à jour).

J'ai également pu constater que d'autres personnes sur le live Twitch souffraient du même problème.

Je précise que cela n'a rien à voir avec des identifiants erronés, sans quoi le site me précise bien "Invalid username or password" quand c'est le cas (d'ailleurs, il faudrait penser à la franciser à l'occasion 😝) !

EDIT : Vider le cache n'y change rien, par contre, après avoir redémarré l'intégralité de mon navigateur comme le conseillait quelqu'un sur le stream, le problème ne se produit plus.

**Comment by dragonis41** [comment]
Hello, j'ai remarqué ce bug aussi qui est assez aléatoire, je suspecte un souci de cache mais j'ignore si c'est de notre côté ou côté navigateur :thinking: 
Je bosse dessus, merci pour ton retour !

**Comment by pipoupoip** [comment]
Nous avons modifié la redirection de la connexion. 
est-ce que vous pouvez tester ? 

Si ça n'a pas d'effet, une autre piste serait un adblocker un poil tatillon. 

@Nozalys et @Dadkill je vous laisse nous tenir au courant :)

**Comment by Nozalys** [comment]
Merci, de mon côté c'est résolu !

**Comment by Dadkill** [comment]
Bonjour,

Ca me semble corrigé également de mon côté après moults tests sur plusieurs navigateurs !

Merci beaucoup pour votre réactivité ! 😊

**Comment by dragonis41** [comment]
Je ferme cette issue car il n'y a plus l'air d'avoir de bug, n'hésitez pas à la rouvrir si le problème est de nouveau présent ! :)
