### ISSUE TITLE
Afficher le sommaire complet, même quand on n'est pas abonné⋅e

### ISSUE THREAD

**Issue by manhack** [NextINpact/Next#50]
& ça doit être un bug : le sommaire s'affichait bien la semaine passée...

**Comment by MosieurClement** [comment]
Merci du retour, on va réparer ça

**Comment by Alexandre-Gliganic** [comment]
Corrigé dans la release v0.3

**Comment by manhack** [comment]
Le pb a certes été corrigé quand on est loggué, mais il continue à n'afficher que les 2 1ers intertitres quand on ne l'est pas ; or, l'un des vertus du sommaire est aussi de donner envie aux non-abonnés de s'abonner pour pouvoir lire l'intégralité de ce que les intertitres du sommaire résument...

**Comment by pipoupoip** [comment]
C'est corrigé, pour le style en revanche, je ne suis pas convaincu. On va voir comment mettre ça en forme proprement :)

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement :smile:.
