### ISSUE TITLE
Dropdown-button, bandeau ne disparait pas si clic ailleurs sur la page

### ISSUE THREAD

**Issue by Sangfeust** [NextINpact/Next#52]
Bonjour,
Lorsque l'on ouvre le bandeau Dropdown, avec le bouton (...). Pour le faire disparaitre il faut de nouveau cliquer sur le dit bouton.
Un clic n'importe où sur la page n'a aucun impact.
Un brin déroutant.
`<button class="dropdown-button" onclick="toggleDropdown(this)"><svg width="19" height="5" viewBox="0 0 19 5" fill="none" xmlns="http://www.w3.org/2000/svg">`

**Comment by MosieurClement** [comment]
Sur quel navigateur ?

**Comment by Sangfeust** [comment]
Microsoft Edge
Version 116.0.1938.98 (Version officielle) (64 bits)
NB : site bloqué en direct par parefeu McAfee.

**Comment by pipoupoip** [comment]
On l'a testé sur tous les navigateurs principaux de notre côté, Edge compris, et nous n'avons pas le problème. Est-il toujours présent ?
