### ISSUE TITLE
Sommaire : Liens inactifs

### ISSUE THREAD

**Issue by guillaume-rico** [NextINpact/Next#54]
En dessous de "Sommaire", on retrouve des liens pour naviguer directement au chapitre indiqué. La souris change bien de forme au passage sur le lien mais lorsque on clique, rien ne se passe : 
![image](https://github.com/NextINpact/Next/assets/11467059/30a46794-7859-4528-8437-2583b67c302f)

**Comment by dragonis41** [comment]
Dupliqué de #22

**Comment by dragonis41** [comment]
Dupliqué de #21
