### ISSUE TITLE
[Feature Request] Faire une visionneuse d'images

### ISSUE THREAD

**Issue by Julkikod** [NextINpact/Next#55]
Salut,
comme dit, quand on agrandit une image, je ne trouve pas de bouton pour revenir à l'article, donc pour réduire l'image.
Par exemple sur les limites planétaires (planete boundaries) dans l'article suivant: https://beta.next.ink/115952/reduire-son-empreinte-environnementale-numerique-cest-comme-tri-selectif-il-faut-faire-point-barre/
En cliquant sur l'image représentant le dépassement des limites entre 2003 et 2023, l'image s'ouvre bien, mais seul un retour en arrière sur le navigateur permet de retrouver l'article.
Peut-être un nouveau clic pour refermer l'image ?
Merci de votre boulot et bon courage,
Julien

**Comment by MosieurClement** [comment]
La visionneuse d'images est enfin sortie :) !

**Comment by Julkikod** [comment]
Merci MosieurClement !
