### ISSUE TITLE
Impossible de commenter: "Vous n'avez pas les droits" 

### ISSUE THREAD

**Issue by Tbaut** [NextINpact/Next#56]
Je veux commenter, je suis connecté (premium), je commente et clique sur le bouton, et mon commentaire n'est pas posté
La requete vers https://beta.next.ink/wp-admin/admin-ajax.php part bien mais la réponse n'est pas celle escomptée
```
{ success: false, data: "Vous n'avez pas les droits" }
```

**Comment by dragonis41** [comment]
Bonjour, à terme il faudra un abonnement actif pour pouvoir commenter, est-ce le cas actuellement ?

**Comment by Tbaut** [comment]
J'ai un abonnement actif actuellement
> Statut
INpactien abonné

> Date d'expiration
07/04/2024

**Comment by dragonis41** [comment]
Humm, je regarde ça, ce n'est pas normal :thinking:

**Comment by dragonis41** [comment]
Tu peux me donner ton pseudo NXI ? Soit ici, soit sur l'adresse mail dev@beta.ink en mentionnant cette issue si tu ne souhaite pas qu'il soit affiché ici :)

**Comment by Tbaut** [comment]
Ce mail ne semble pas être bon, j'ai recu un bounce du serveur
> Your message could not be delivered for more than 2 hour(s).

**Comment by dragonis41** [comment]
> Ce mail ne semble pas être bon, j'ai recu un bounce du serveur
> 
> > Your message could not be delivered for more than 2 hour(s).

Sorry, petite erreur de ma part, j'ai corrigé le message avec la bonne adresse

**Comment by pipoupoip** [comment]
Hello @Tbaut 

Les commentaires ont pas mal bougé cette semaine. As-tu toujours le souci ?

**Comment by Tbaut** [comment]
Ah nice, ca marche mtn. Merci!
