### ISSUE TITLE
[V7] Prix des abonnements incohérent : 1an vs 2an, & remise 1 an

### ISSUE THREAD

**Issue by Nightmaster** [NextINpact/Next#57]
Quelqu’un de sage a dit un jour :
> Une image vaut mieux que 10 000 mots

![image](https://github.com/NextINpact/Next/assets/4302581/1c384929-3189-4bea-bfdc-06404e5b099a)
![image](https://github.com/NextINpact/Next/assets/4302581/69dbcbce-12d2-490d-8365-2b690b3eaaa2)
![image](https://github.com/NextINpact/Next/assets/4302581/1a66803d-1820-468f-ae3a-8a21d43bc209)

1. L'abonnement 2ans et à plus du double de celui de 1 an, même si l’on prend en compte la hausse de tarif qui est prévu.
2. Le total des 1 ans devrait être de 67,2 €, pas 83.2€ (`96 - 8 - 20,8`)

Indice possible : Sur les images 2&3, les remises sur les 12 mois / 1 mois semblent être "doublement négative".

N.B. Si besoin je peux fermer l’anomalie et la rouvrir sur la v7, mais je me suis permis de l’ouvrir ici pour plus de visibilité. 😅

**Comment by dchatelain** [comment]
Hello, c'est voulu. Ferd a expliqué qu'ils vont arrêter les abos de 2 ans et à terme, les abos d'un an. Donc pour décourager les gens il a augmenté massivement les prix (faute de pouvoir désactiver les options sur l'ancien site).
C'est donc plus rentable de prendre mois par mois.
