### ISSUE TITLE
[BUG] Liens "À propos" invalides

### ISSUE THREAD

**Issue by Dadkill** [NextINpact/Next#6]
Les menus "Déontologie" et "Règles de modération" renvoient respectivement vers les adresses https://next.dev.petit.ninja/charte-ethique-et-deontologique-de-next-ink/ et https://next.dev.petit.ninja/regles-de-la-communaute/ qui sont toujours dans l'environnement de dev et donc, inaccessibles.

Edit : même souci pour les mentions légales en pied de page : https://next.dev.petit.ninja/mentions-legales-et-contact/

**Comment by dragonis41** [comment]
Corrigé ! Merci pour ton retour :)
