### ISSUE TITLE
Illustration tronquée dans le corps de l'article

### ISSUE THREAD

**Issue by jj-mm** [NextINpact/Next#61]
![Next](https://github.com/NextINpact/Next/assets/25002000/fa1429c6-63e0-4e4a-92c4-eba081f2922c)
(Firefox 118.02,  écran 1920x1200, zoom 'taille réelle')

**Comment by xavierforestier** [comment]
Ici, le prb est bien visible : https://beta.next.ink/116805/chatcontrol-commissaire-europeenne-visee-par-plusieurs-plaintes-et-enquetes/
![Screenshot_20231101_111624](https://github.com/NextINpact/Next/assets/23277701/695c126f-fcb2-468e-8b99-8d3bd399001d)

**Comment by pipoupoip** [comment]
Oui réduire la height du figure et/ou mettre l'image en object-fit: contain; devrait résoudre le souci :)

**Comment by pipoupoip** [comment]
C'est corrigé, je ferme :)
