### ISSUE TITLE
Tous les écrans ne sont pas verticaux

### ISSUE THREAD

**Issue by jj-mm** [NextINpact/Next#62]
Sur un écran large, la place de lecture est trop fortement réduite par des colonnes droites et gauches vides. Je sais que c'est la mode, mais c'est pour moi très gênant. 
Certes, un zoom permet de régler le problème, mais alors le contenu vertical utile (liste des articles) n'existe plus sur la page de garde !
Joint: sans zoom et avec zoom

 
![Next3-normal](https://github.com/NextINpact/Next/assets/25002000/409a94be-ba93-4f7f-9971-2bc24264822a)

![Next3-zoom](https://github.com/NextINpact/Next/assets/25002000/4e869038-4001-4549-bfea-318e26aed744)

**Comment by dragonis41** [comment]
Bonjour, je t'invite à suivre la discussion sur l'issue #31
