### ISSUE TITLE
Pas d'affichage de certaines vignettes

### ISSUE THREAD

**Issue by jj-mm** [NextINpact/Next#63]
Je suppose un problème provisoire: les vignettes des deux articles de Mathilde du 25 octobre ne s'affichent pas. (Ctrl F5 essayé).
Nota: en vérifiant dans l'article, l'illustration de l'article a le même problème.
![Next4](https://github.com/NextINpact/Next/assets/25002000/73c99096-d33a-47b9-bcd6-1bf959fdf99a)

**Comment by dragonis41** [comment]
Bonjour, tu as dû aller sur le site pendant la migration, as-tu toujours le souci ?
