### ISSUE TITLE
Partage de l'article : doublon entre les icônes et le menu déroulant

### ISSUE THREAD

**Issue by bansan85** [NextINpact/Next#64]
Sur Firefox PC.

![image](https://github.com/NextINpact/Next/assets/9248729/63990e56-e2ba-421e-81cf-26115ce48ba4)

**Comment by pipoupoip** [comment]
Hello, 

Oui le menu contextuel est destiné à changer. 
Ça arrive bientôt :)

**Comment by pipoupoip** [comment]
Ça y est, le menu contextuel a changé. 
Seul le bouton copier le lien de l'article est dupliqué (on pense que c'est celui qui sera le plus utilisé, les corrections pouvant être proposées directement en sélectionnant le texte, et n'ayant pas de stats sur l'utilisation de la fonctionnalité "offrir un article")
Je ne sais pas s'il est tout à fat définitif mais c'en est probablement pas loin
