### ISSUE TITLE
Ou est Travolta ? Page 404

### ISSUE THREAD

**Issue by guillaume-rico** [NextINpact/Next#66]
La page 404 mériterait d'être créée.

Sur l'ancien site, nous avions le droit à une petite vidéo de Travolta : https://www.nextinpact.com/54212145

Sur Next, plus rien : https://beta.next.ink/40245454

Et sur certaines page, c'est complétement vide (et le favicon n'est pas le bon ) : 
https://beta.next.ink/wp-admin/ 
 - wp-content/plugins/ 
 - wp-content/themes/
 - wp-admin

**Comment by dragonis41** [comment]
Bonjour, une page est actuellement en cours de création avec une magnifique illustration de Flock. Elle n'est juste pas encore en ligne :)

**Comment by pipoupoip** [comment]
Hé ho 
Spoilo NO

**Comment by guillaume-rico** [comment]
J'ai échangé avec Flock au café. Il m'a dit qu'il ferait un Gif reprenant la vidéo de Travolta mais avec un dessin caricaturant Ferd. J'ai hâte de voir le résultat

**Comment by dragonis41** [comment]
@pipoupoip a dit spoilo no ! :rofl:

**Comment by xavierforestier** [comment]
À clore, ce n'est pas Travolta, mais ça passe :)

**Comment by Glandos** [comment]
Ouais, même si ce n'est pas la première fois qu'on voit ça : https://www.peugeot.fr/kapoue
