### ISSUE TITLE
Le Brief du jour et de la veille ne s'affichent pas dans la colonne de droite

### ISSUE THREAD

**Issue by SpectacularBird** [NextINpact/Next#67]
<img width="332" alt="2023-10-27_16-28-33" src="https://github.com/NextINpact/Next/assets/59343527/292ccb70-0594-4878-8ad0-3c08c39669f8">

Aujourd'hui vendredi, cela ne s'affiche pas. Ni jeudi. Ok pour mercredi et les autres jours.
C'est ainsi depuis la version alpha 0.

_(Navigation sur Safari MacOs version 17.0)_

**Comment by dragonis41** [comment]
Bonjour, ce n'est pas un bug, c'est juste que les briefs du jour n'ont pas été importés, le dernier import date de mercredi soir (d'où la présence du brief pour mercredi)
