### ISSUE TITLE
Au cœur des débats : Date au lieu de l'heure

### ISSUE THREAD

**Issue by Jipem** [NextINpact/Next#68]
Bonjour,

Dans le bandeau "Au cœur des débats", il est actuellement affiché l'heure de l'article. 
Sachant que ces articles peuvent dater, cela n'a pas de sens.
Il serait souhaitable d'y afficher la date à la place.

![Image](https://github.com/NextINpact/Next/assets/2027318/169acdac-9654-49ce-a026-7dc303fe1130)

**Comment by AIMAR-S** [comment]
Puis perso, ça veux avoir quel sens le compteur 01 ? 02 ? et on y gagnerait en taille sans cela.

**Comment by jj-mm** [comment]
J'espère que dans la personnalisation pour les abonnés, il sera possible d'éliminer le bloc totalement, Ça prend une place énorme, même réduit, et n'apporte rien à un visiteur fréquent.
