### ISSUE TITLE
Articles manquants

### ISSUE THREAD

**Issue by qwazer14** [NextINpact/Next#69]
Bonjour.

Les derniers articles sont manquants sur le nouveau site.

A l'heure où j'écris, le dernier article est du 25/10, alors que sur le site "classique" il y a des articles datés du 28/10...

**Comment by dragonis41** [comment]
Bonjour, même réponse que pour #67 : on n'a juste pas lancé d'export depuis la semaine dernière, on va le mettre à jour d'ici quelques minutes :)
