### ISSUE TITLE
Formulaire de connexion et touche entrée

### ISSUE THREAD

**Issue by LukeMarlin** [NextINpact/Next#70]
Firefox 118.0.2

Lorsque je clique sur le bouton connexion, il y a bien un POST sur /authenticate et tout se passe normalement
Cependant, après avoir tapé le mot de passe, si j'utilise la touche entrée, le POST /authenticate apparaît complètement vide dans les logs firefox. Pas de données de requête, pas de réponse, pas de timing. Je suis redirigé vers l'accueil _sans être connecté_

**Comment by dragonis41** [comment]
Bonjour, je n'ai pas réussi à reproduire ton issue, est-ce que ça te le fait aussi en navigation privée ? Dans ce cas c'est surement que ton navigateur a mis en cache une ancienne version du site où il y avait un bug avec le login (donc un clear du cache devrait corriger le problème

**Comment by pipoupoip** [comment]
Hello 

@LukeMarlin est-ce toujours le cas ?

**Comment by LukeMarlin** [comment]
Hey, désolé pour le délai de réponse.

Je n'arrive effectivement plus à reproduire ce comportement
