### ISSUE TITLE
Mise en forme des commentaires "perdues"

### ISSUE THREAD

**Issue by francois-dorin** [NextINpact/Next#72]
La mise en forme (au moins l'italique) est perdue lors de l'affichage dans les commentaires.

Rien de bien grave, juste un problème de CSS a priori, puisque le texte est décoré de balise `<em>`

Exemple sur la page https://beta.next.ink/116807/quoi-neuf-a-redac-5-voyages-forment-jeunesse-ou-pas-horaires-chaotique-brief/, premier commentaire de Trit', où _Passport to the Future_ est censé être en italique.

**Comment by villisek** [comment]
Autre élément perdu : les citations des articles.

Exemples :

- https://www.nextinpact.com/article/72826/les-lidd-sont-retour-sur-next#comment/2164632 => https://beta.next.ink/117795/les-lidd-sont-retour-sur-next/
- https://www.nextinpact.com/blog/72813/quoi-neuf-a-redac-7#comment/2164547 => https://beta.next.ink/117796/quoi-neuf-a-redac-7/
- https://www.nextinpact.com/article/72850/protection-mineurs-en-ligne-questions-actions-et-craintes-avec-ton-crush-secret#comment/2164473 => https://beta.next.ink/117791/protection-mineurs-en-ligne-questions-actions-et-craintes-avec-ton-crush-secret/

Cela enlève du contexte dans les commentaires...
