### ISSUE TITLE
Commentaire: reply

### ISSUE THREAD

**Issue by francois-dorin** [NextINpact/Next#73]
Lors de la réponse à un commentaire, le reply est disproportionné par rapport au texte du commentaire.

De plus, il apparait sous la forme `(reply:2162324:Trit’)`

Exemple : https://beta.next.ink/116807/quoi-neuf-a-redac-5-voyages-forment-jeunesse-ou-pas-horaires-chaotique-brief/, le 2e commentaire, celui de Vincent, en réponse à Trit'

Un petit filtre dans wordpress pour parser les commentaires devraient vite faire l'affaire ;)

**Comment by dragonis41** [comment]
Le problème est toujours présent sur la dernière version, [Exemple](https://next.ink/brief_article/microsoft-fete-20-ans-patch-tuesday/#:~:text=(quote%3A2164331%3Aalex.d.))
On regarde ça !

**Comment by Opwi** [comment]
Bonjour,

Le problème n'est plus d'actualité avec la version actuelle des commentaires.
