### ISSUE TITLE
blocs javascript dupliqués

### ISSUE THREAD

**Issue by francois-dorin** [NextINpact/Next#74]
J'ai constaté qu'il y avait des blocs javascripts qui étaient dupliqué. 

Par exemple, au niveau de l'agora, sous le div `<div class="artice-text-comment">`, le bloc qui définit la fonction `filterCategories` est répétée sous chaque article.

Je n'ai pas vérifier si c'est le seul, mais il y aura peut être une passe à faire à ce sujet

**Comment by MosieurClement** [comment]
On fera une passe sur la qualité, duplicata dans les prochains jours, merci pour le retour

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug.

Merci du signalement :smile:.
