### ISSUE TITLE
Les apostrophes dans les titres de sections de l'article cassent la navigation.

### ISSUE THREAD

**Issue by qbuache** [NextINpact/Next#75]
Les apostrophes dans les titres de sections de l'article cassent la navigation.

`goToElementTitle('Des « points d'interrogation » sur la conformité avec le DSA', this)">`
 ----------------------------------- ^

**Comment by Alexandre-Gliganic** [comment]
Nous avons bien noté le bug, il sera corrigé dans une version future. Merci pour votre aide.

**Comment by Opwi** [comment]
Hello,

Problème résolu.
Merci de votre retour.😁
