### ISSUE TITLE
Affichage des images avec "zoom" incorrect

### ISSUE THREAD

**Issue by brunof0d2** [NextINpact/Next#77]
Bonjour,
Dans les articles, les images ne sont pas affichés correctement, elles sont agrandies à l'extrême et coupées. (voir image jointe).
![image](https://github.com/NextINpact/Next/assets/25545427/60042bbd-ee62-4369-9e97-7d0b22054c5f)
Bien à vous.

(PS : pas trouvé d'Issue sur ce même sujet, désolé si au final c'est un doublon).

**Comment by brunof0d2** [comment]
(exemple capturé ici : https://beta.next.ink/116805/chatcontrol-commissaire-europeenne-visee-par-plusieurs-plaintes-et-enquetes/)

**Comment by Alexandre-Gliganic** [comment]
Dupliqué de l'issue #61
