### ISSUE TITLE
Liste de catégorie trop longue et liens ne fonctionnent pas en dehors de la home

### ISSUE THREAD

**Issue by xavierforestier** [NextINpact/Next#83]
La liste des catégories me semble un peu trop longue : 
- Droit
- Économie
- Flock
- Hardware
- IA et algorithmes
- Internet
- Logiciel
- Next
- Réseaux sociaux
- Science et espace
- Sécurité
- Société numérique

Rien que ça :) Le but de filtrer les articles pour faire son Next est bon mais si il faut faire 10 clics pour y arriver... personne n'aura la patience, je crois.

Flock / Next : désolé, mais c'est pas vraiment une catégorie à fusionner en "Humeur de la rédac" ou "la rédac"
Internet / Réseaux Sociaux / Société Numérique : ça ne serait pas la même rubrique ?
le reste est pas mal peut-être fusionner Droit et Économie même si c'est moins évident.

Aucun lien sur ces catégories ne fonctionne en dehors de la home.

**Comment by Opwi** [comment]
Bonjour,

Nous avons corrigé ce bug. Concernant la liste des catégories trop longue c'est un choix éditorial.

Merci du signalement :smile:.
