### ISSUE TITLE
Répondre en 3éme et 4éme position ne permet pas de voir le bouton "répondre" pour valider

### ISSUE THREAD

**Issue by Julkikod** [NextINpact/Next#84]
Bonjour,
C'est peut-être voulu, parce que ça va être compliqué de suivre les discussion si on se perd dans les fil, mais répondre en 3éme et 4éme position ne permet pas de voir le bouton "répondre" pour valider :
![image](https://github.com/NextINpact/Next/assets/40038856/c6facb53-5aed-445b-ba18-93d70cafca8e)

Il faut décaler vers la droite (j'ai fait ça au clavier car je n'ai pas vu d'ascenseur général ou spécifique à mon cadre de réponse):
![image](https://github.com/NextINpact/Next/assets/40038856/38107625-ce91-465c-9b3d-935b0641b69f)

Bon courage et bonne vacances aux chanceux ;-)
Jul

**Comment by Julkikod** [comment]
Haaa !! et du coup le timestamp est pas à jour dans la première capture: j'ai mis le commentaire "ca marche, je confirme" il y a à peine 10 minutes (17h12 le 1er novembre, à la louche).

**Comment by MosieurClement** [comment]
Les commentaires sont en refonte, ils arrivent très bientôt 😛

**Comment by MosieurClement** [comment]
Je vais fermer cette issue, on peut continuer d'en discuter là-bas -> #3 😉
