### ISSUE TITLE
[NextInpact] Le certificat HTTPS a expiré

### ISSUE THREAD

**Issue by AIMAR-S** [NextINpact/Next#85]
Pour info le certificat à expiré !

Fin de validité  `Fri, 03 Nov 2023 05:13:19 GMT`

Voilà !

**Comment by francois-dorin** [comment]
Yep, j'ai constaté ça aussi.  J'ai eu un retour de l'équipe et elle est au courant. 

Je cite : 

> nous sommes sur la brèche pour résoudre ce vilain problème de certificat

Il faut juste attendre...

**Comment by xavierforestier** [comment]
Pour les impatiens, ouvrir https://api-v1.nextinpact.com dans un nouvel onglet et choisir l'option Avancer > "accepter le risque et poursuivre"
Rafraichir l'onglet next d'origine (Ctrl+Shift+R)
Bon de toute façon y'a pas de brief :-/

**Comment by AIMAR-S** [comment]
C'est amusant car j'ai l'impression que cette option n'est plus dispo sur Firefox !

**Comment by xavierforestier** [comment]
> C'est amusant car j'ai l'impression que cette option n'est plus dispo sur Firefox !

Bah je suis sous Firefox 119.0 et j'ai bien l'option :
![Screenshot_20231103_095538](https://github.com/NextINpact/Next/assets/23277701/25520481-02df-4bd7-bcda-cdefa49d377e)

**Comment by francois-dorin** [comment]
L'option HSTS étant activée sur le site, le navigateur doit bloquer la possibilité d'outrepasser la sécurité malgré les alertes sur le certificat, s'il sait que le site l'utilise (via le cache).

Il faut supprimer le cache (ou passer en navigation privée) pour que le navigateur ne se sache pas que le site requiert HSTS.

[edit]
Et encore, se sera pour la première connexion. Je ne sais pas comment cela se passe si la première requête indique "utilise HTST" mais que le certificat est invalide !

**Comment by xavierforestier** [comment]
oui d'où le Ctrl+Shift+R :)

**Comment by francois-dorin** [comment]
> oui d'où le Ctrl+Shift+R :)

Le Ctrl+Shift+R apparait à la fin de ta procédure, sur le site normal, pas au début, sur l'adresse liée à l'API  ;)

[edit]
De toute façon, rafraichir le cache n'est pas sensé corriger le problème : juste dire pour les données, je force la version qui provient du serveur. Mais si le site utilise HSTS, l'option restera active.

**Comment by xavierforestier** [comment]
Bon Next la commande est  
> sudo certbot renew 

:)

**Comment by francois-dorin** [comment]
> Bon Next la commande est
> 
> > sudo certbot renew
> 
> :)

Oui, mais non. Le certificat est un certificat wilcard. C'est souvent plus complexe que ça dans ce cas, notamment s'il n'existe pas (ou qu'il n'a pas été configuré) de plugin permettant de gérer le DNS ;)

Le certificat wilcard nécessite un challenge DNS. Impossible d'utiliser un challenge HTTP.

Donc la commande va permettre de lancer le processus, doit indiquer les différentes étapes, mais n'est pas suffisante dans ce cas ;)

**Comment by AIMAR-S** [comment]
> > C'est amusant car j'ai l'impression que cette option n'est plus dispo sur Firefox !
> 
> Bah je suis sous Firefox 119.0 et j'ai bien l'option : ![Screenshot_20231103_095538](https://user-images.githubusercontent.com/23277701/280225796-25520481-02df-4bd7-bcda-cdefa49d377e.png)

Bien, sous Win 11 FF 120.0b5 nope 
![image](https://github.com/NextINpact/Next/assets/13015224/6d404875-a983-4666-8fca-796eb10ec707)

Et en navigation privée c'est "pire"
![image](https://github.com/NextINpact/Next/assets/13015224/6e1f3f47-5a54-497c-908b-9332fb867dd3)

**Edit:**
Ah non c'est comme ça partout, privée ou pas maintenant !

**Comment by Opwi** [comment]
Hello!
Nous rencontrons actuellement des problèmes avec Cloudflare pour renouveler le certificat. Nous sommes en train de basculer `nextinpact.com` vers `beta.next.ink` le temps que les problèmes de Cloudflare soient résolus.

**Comment by francois-dorin** [comment]
"Nous sommes heureux de vous annoncer que le problème de certificat a été résolu. Malheureusement, nous avons juste flingué notre serveur donc prions !" :)

**Comment by francois-dorin** [comment]
> Hello! Nous rencontrons actuellement des problèmes avec Cloudflare pour renouveler le certificat. Nous sommes en train de basculer `nextinpact.com` vers `beta.next.ink` le temps que les problèmes de Cloudflare soient résolus.

Aie mince. Bon courage alors !

**Comment by francois-dorin** [comment]
> "Nous sommes heureux de vous annoncer que le problème de certificat a été résolu. Malheureusement, nous avons juste flingué notre serveur donc prions !" :)

Du coup, pas possible de squeezer simplement CloudFlare temporairement et d'exposer le serveur en direct ?

**Comment by pipoupoip** [comment]
Videz vos caches :) 
La redirection est effective vers la beta. 
En fait le certificat expiré empeche certains pods de démarrer. On ne peut pas juste squeezer CF.

**Comment by pipoupoip** [comment]
Maintenant que nextinpact est joignable (disons en mode dégradé) nous allons voir comment nous pouvons renouveler le certificat et relancer nextinpact.com

**Comment by eglyn** [comment]
Ah les joies de Cloudflare :D

**Comment by pipoupoip** [comment]
C'est en train de revenir. 
Est-ce que vous pouvez nous confirmer ça ? :)

**Comment by francois-dorin** [comment]
oui ! C'est revenu.

Merci :)

**Comment by remip74** [comment]
c'est ok à dans 3 mois :)
