### ISSUE TITLE
Page d'accueil : choix d'ergonomie de la limitation d'affichage semaine par semaine

### ISSUE THREAD

**Issue by Nozalys** [NextINpact/Next#86]
**Mon avis et ma question :**
Bonjour, je n’apprécie pas la limite d'affichage de la page d’accueil à 1 semaine de contenu. Est-ce nécessairement un choix éditorial ou technique ? Si ce n'est pas le cas, est-il prévu à l'avenir une modification ?

**La raison :**
Sans filtrer, la page de NXI affiche 11 articles de + que Next. quand on active un filtre à thème, on se retrouve avec des pages vides (ou avec 1 seul article) à cliquer sur "semaine précédente" jusqu'à trouver ce qu'on veut (et avec un reload de la page qui force le scrolling en haut). On se retrouve à cliquer plein de fois pour retrouver un article ou parcourir les actualités quand on n'est pas venu depuis un certain temps. Ce n'est pas pratique et donne l'impression d'un site vide.
Autre comparaison : sur NXI, quand on sélectionne un thème, la page affiche toujours les 35 derniers articles, ce qui, selon le thème, peut faire remonter loin en date, mais je trouve ça largement plus pratique.

**Propositions :**

- On peut imaginer remettre une limite au nombre d'article, ou garder "par date" mais augmenter le nombre de jours. Ou les deux, du genre _max(30 derniers articles, 3 dernières semaines)_

- On pourrait imaginer une option dans le profil utilisateur pour passer d'une limite hebdomadaire à une limite mensuelle ou trimestrielle.

Qu'en pensent les autres lecteurs ? Et qu'en pensez-vous ?

**Comment by pipoupoip** [comment]
La présentation par semaine est un choix éditorial. Voir les n derniers jours est envisageable. 

Les filtres vont changer, il n'y aura plus une limitation par semaine, ça fait effectivement trop peu d'articles à présenter quand on filtre. 
C'est dans les tuyaux, ça arrive bientôt :)

**Comment by Nozalys** [comment]
Merci d'avoir amélioré ça !
Il reste néanmoins un bug : quand je change les catégories, la sélection s'effectue bien et l'URL de la page change (ex: https://beta.next.ink/?category=13) mais aucune image d'article ne se charge. Il me faut rafraichir la page pour qu'elles apparaissent. idem quand je retire le choix de la catégorie : le retour à la homepage par défaut se fait sans les images.

**Comment by pipoupoip** [comment]
Effectivement on a un souci à ce niveau, on est dessus :)

**Comment by pipoupoip** [comment]
Le problème de base est résolu et il existe une issue pour le nouveau problème (#97) 
Je ferme donc cette issue (c'est pour les stats ;))
