### ISSUE TITLE
Impossible de me réabonner

### ISSUE THREAD

**Issue by ruihildt** [NextINpact/Next#87]
Le lien n'aboutit sur rien pour ma part: https://compte.nextinpact.com/gestion/abonnement

**Comment by Opwi** [comment]
Qu'entendez-vous par "le lien n'aboutit sur rien" ? Vous est-il possible de fournir une capture d'écran ?

**Comment by ruihildt** [comment]
> Qu'entendez-vous par "le lien n'aboutit sur rien" ? Vous est-il possible de fournir une capture d'écran ?

Le lien n'aboutissait a rien, comme si la page n'existait pas.

Je viens de retester, et la page fonctionne actuellement. Je cloture donc cette issue.
