### ISSUE TITLE
extension .ink et blocages

### ISSUE THREAD

**Issue by eglyn** [NextINpact/Next#89]
Bonjour !

Je tiens juste à signaler que dans mon groupe le .ink est bloqué (et ne peut pas être débloqué après m'être renseigné :))

Je me demande si cette extension ne va pas vous priver d'un public professionnel, sachant que beaucoup consultent ce genre de sites depuis leur taff :)

voilà, je ne sais pas si c'est le cas pour d'autres inpactiens, mais je tenais à vous faire la remarque :)

**Comment by Opwi** [comment]
Hello,

Nous avons bien la problématique en tête et à ce jour, nous n'avons pas de solutions magiques. Nous restons cependant ouverts au débat.

Bonne soirée 😁
