### ISSUE TITLE
Mauvaise pagination des articles

### ISSUE THREAD

**Issue by Nozalys** [NextINpact/Next#91]
Le problème est visible avec cet article : https://beta.next.ink/117164/mozilla-propose-depot-debian-pour-firefox-nightly-changement-plus-important-quil-ny-parait/

Au second chapitre, les lignes présentant du code dépassent largement la bande prévue et elles viennent s'encastrer sous les div flottantes de droite :

![image](https://github.com/NextINpact/Next/assets/15943230/0c538485-517c-4f47-bb72-b72a9ab4fc32)

**Comment by pipoupoip** [comment]
C'est corrigé :)
