### ISSUE TITLE
Lisibilité des commentaires (et des articles)

### ISSUE THREAD

**Issue by Nozalys** [NextINpact/Next#92]
J'ai du mal à lire les commentaires... tellement que je n'y arrive plus : la police n'est pas adapté (pour moi), et elle est trop petite, trop dense (espacement) et trop condensée (interligne).

J'ai joué avec l'inspecteur de FFox et j'ai trouvé un compromis qui me semble plus raisonable :
Taille : 15 px
hauteur de ligne : 24 px
Espacement : 0.03 em

Avec ces réglages, on se rapproche de la lisibilité existante sur NXI. Voici une capture pour comparer le rendu (1er commentaire) avec celui du site par défaut (2nd commentaire) :

![image](https://github.com/NextINpact/Next/assets/15943230/d28f522a-df3c-46b0-b5c4-a8887738863d)

Reste que la police Open Sans est pour moi beaucoup plus claire et lisible que Rubik Regular qui ajoute du flou sur tous les arrondis.

Sur ce point, concernant les articles eux-mêmes, la police utilisée est également assez dissuasive pour moi pour une lecture qui dépasse 2 minutes :(
Serait-il envisageable, là aussi, de paramétrer ça dans son profil, à l'avenir ? Je sais que les polices avec Sérif dominent largement les sites de presse, mais la majorité me sont trop difficiles à lire sur écran. La seule que je connaisse que je lis correctement c'est Garamond.

**Comment by dragonis41** [comment]
Bonjour, les commentaires sont en cours de refactoring, je t'invite à en discuter sur l'issue #3 
Merci :)

**Comment by Nozalys** [comment]
Ca marche, merci, je n'avais pas vu ce ticket.
