### ISSUE TITLE
[feature request] RSS feed : ajout des sous-titres des articles

### ISSUE THREAD

**Issue by typhoe** [NextINpact/Next#94]
Hello,

les sous-titres n'ont jamais été inclus dans les flux RSS sur l'ancienne version...

Vu que vous êtes sur le sujet, je me permets de le demander pour que ça soit si possible ajouté dans la todo list :-)

Merci

**Comment by dragonis41** [comment]
Bonjour, effectivement c'est une bonne idée ! J'ajoute ça pour la prochaine mise en prod

**Comment by dragonis41** [comment]
Hop, c'est en prod :)
N'hésite pas à suivre le point dev ou l'issue #1 pour avoir des infos sur les URLs disponibles et comment générer un token (il faut qu'on ajoute un bouton pour regénèrer un nouveau token d'ailleurs car le format a changé)

**Comment by typhoe** [comment]
Alors, c'est justement en lisant le point dev de ce matin que je suis venu sur le github. 
Et je viens de générer mon token (clé RSS) ce matin.
Au passage, c'est pas "clair" pour récupérer le flux RSS ...
La page profil permet de générer le token et l'affiche... mais le lien du flux n’apparaît pas... et le bouton "copier"... rien n'indique qu'il contient justement le lien RSS avec la syntax du token :-p
Sachant que chez moi, le lien RSS en bas de la page d'accueil ne fait que renvoyer sur cette même page d'accueil

Dans tous les cas, merci pour l'ajout HYPER rapide!
Et je confirme que ça marche parfaitement, GRAND MERCI !

![image](https://github.com/NextINpact/Next/assets/881171/8655f8d2-504b-4367-85d7-3f4c918a6631)

**Comment by dragonis41** [comment]
Oui tout à fait, on est au courant du souci ^^
Je suis en discussion avec l'équipe pour voir si on intègre les 4 liens dans une page tuto comme sur l'ancien site ou si on met directement 4 boutons dans le profil

Si tu veux tester les différents liens dès maintenant, ce sont ces derniers :
* `/feed/full?rsskey=xxx`  ->  Flux par défaut avec 1 article par post et un article de brief par post (c'est le même flux que /feed )
* `/feed/nobrief?rsskey=xxx`  ->  Flux avec seulement les articles
* `/feed/briefonly`  ->  Flux avec seulement les articles de brief (un article par post)
* `/feed/condensedbrief?rsskey=xxx`  ->  Flux avec 1 article par post et un Brief par post (tous les articles de brief sont condensés dans un seul post)
