### ISSUE TITLE
[feature request] RSS feed : ajout des images

### ISSUE THREAD

**Issue by arena94** [NextINpact/Next#96]
Comparatif avant/après

![avant:après](https://github.com/NextINpact/Next/assets/1025411/112f5e0e-a3a7-4b48-8dbc-ec9068f8d354)

**Comment by dragonis41** [comment]
Bonjour, je t'invite à continuer la conversation ici : #1 :)
La mise en prod des différents flux est prête, on va bientôt faire une annonce avec tous les liens des différents flux et comment obtenir sa clé d'authentification pour avoir les articles complets pour les abonnés premium
