### ISSUE TITLE
Les illustrations des articles disparaissent suite au filtre par catégorie

### ISSUE THREAD

**Issue by dchatelain** [NextINpact/Next#97]
Lorsqu'on filtre par catégorie les articles de la page d’accueil, les vignettes des articles disparaissent pour laisser un vide d'une blancheur éblouissante
![image](https://github.com/NextINpact/Next/assets/17156860/c3d7db84-48ca-4ab3-95c8-caea458b1ec3)

**Comment by dragonis41** [comment]
Bonjour, l'équipe travail actuellement à la correction du problème :)

**Comment by pipoupoip** [comment]
C'est parfaitement corrigé maintenant :)
