### ISSUE TITLE
Image avec height supérieure à 450 px dans article

### ISSUE THREAD

**Issue by mczslw** [NextINpact/Next#98]
Les images de plus de 450px de hauteur incluses dans une balise `<figure>` "débordent" un peu.
Exemple [ici](https://beta.next.ink/117501/le-nouveau-champion-francais-cybersurveillance-veut-aider-handicapes-mentaux-a-communiquer/)

![next-ink-img-450](https://github.com/NextINpact/Next/assets/2486201/8310b737-d1de-4934-9eed-4f41d8c4c607)

_Firefox 119.0_

**Comment by MosieurClement** [comment]
C'est résolu normalement :)
